### ISSUE TITLE
xgboost

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#10]
XGBoost.jl is using BinDeps. It would be nice to have BB binaries.

https://github.com/dmlc/XGBoost.jl/blob/master/deps/build.jl

https://github.com/dmlc/XGBoost.jl/issues/51

**Comment by staticfloat** [comment]
I have built XGBoost binaries for everything except FreeBSD (unsupported) and Windows (toolchain doesn't have OpenMP integrated properly).  I'm attempting to integrate OpenMP into our windows BB toolchains properly (just need to change how I'm building mingw) and that should open up our Windows builds as well.

**Comment by ablaom** [comment]
@ViralBShah 

So, to clarify, what remains to be done here that @staticfloat has not taken care of? 

And if there is more to be done, what part of that is @staticfloat willing to undertake?

Sorry for the dumb questions, but I am not that familiar with building binary dependencies from Julia.

**Comment by ViralBShah** [comment]
@staticfloat I assume we have openmp binaries on all platforms and single threaded on Windows. If so, maybe we can close. I am happy to ignore freebsd.

**Comment by aviks** [comment]
@staticfloat another vote for uploading what you already have.

**Comment by ViralBShah** [comment]
Is it possible for others to also upload binaries?

**Comment by aviks** [comment]
@staticfloat bump?

**Comment by staticfloat** [comment]
I have generated XGBoost binaries, but unfortunately they crash Julia when loaded on Windows.  I have some debugging information [in my PR](https://github.com/dmlc/XGBoost.jl/pull/68#issuecomment-503381225).
