### ISSUE TITLE
Build HDF5 for Power

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/Yggdrasil#1009]
x-ref: https://github.com/JuliaLang/julia/issues/35801

https://github.com/JuliaPackaging/Yggdrasil/blob/0e26517dc7b99618a2dece1de7e51c7d41d8bca6/H/HDF5/build_tarballs.jl#L120-L128

**Comment by giordano** [comment]
See #567

**Comment by ViralBShah** [comment]
Closing since I see power binaries in https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/tag/HDF5-v1.14.3%2B3
