### ISSUE TITLE
OpenSSL_jll v3.0.15+2 breaking on Apple Silicon: LoadError: ArgumentError: Platform `riscv64-linux-gnu` is not an officially supported platform

### ISSUE THREAD

**Issue by svilupp** [JuliaPackaging/Yggdrasil#10149]
HTTP.jl and any depending package fail to load if they have `OpenSSL_jll v3.0.15+2` installed. 
Downgrading to v3.0.14 solves the problem. 

Error: `ERROR: LoadError: ArgumentError: Platform `riscv64-linux-gnu` is not an officially supported platform`

Version info

> Julia Version 1.11.2
> Commit 5e9a32e7af2 (2024-12-01 20:02 UTC)
> Build Info:
>   Official https://julialang.org/ release
> Platform Info:
>   OS: macOS (arm64-apple-darwin24.0.0)
>   CPU: 8 × Apple M1 Pro
>   WORD_SIZE: 64
>   LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
> Threads: 1 default, 0 interactive, 1 GC (on 6 virtual cores)
> Environment:
>   JULIA_EDITOR = code

**Comment by giordano** [comment]
You likely have stacked environments, one of which has JLLWrappers < 1.7.  Update your environments to make sure you have JLLWrappers 1.7 everywhere.  See https://github.com/MakieOrg/Tyler.jl/issues/122 for extensive proof of what I'm saying.

**Comment by svilupp** [comment]
That was quick! Thank you
