### ISSUE TITLE
Improve access to the corresponding source for better GPL Compliance

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/Yggdrasil#1030]
Disclaimer: the following is not meant to annoy anybody, but rather made in a good-faith effort to perhaps prevent future grief for the good people working on this nice project!

Here is the point: you are distributing "executable or object code" on e.g. https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases for GPL'ed software. But as far a I can tell, you are neither offering equivalent access to the source code, nor a written offer for the source code. That would mean that (again, unless I am missing something!) currently there is a violation of the GPL here (granted, in my eyes a pretty harmless one, but also one that's pretty easy to fix, I think). To explain why I think that, I'll quote the relevant section of the GPL v3 below with some comments (similar text can be found in the GPL v2)

>   You may convey a covered work in object code form under the terms
> of sections 4 and 5, provided that you also convey the
> machine-readable Corresponding Source under the terms of this License,
> in one of these ways:
> 
>     a) Convey the object code in, or embodied in, a physical product
>     (including a physical distribution medium), accompanied by the
>     Corresponding Source fixed on a durable physical medium
>     customarily used for software interchange.

This option is irrelevant here, as there is no physical product.

> 
>     b) Convey the object code in, or embodied in, a physical product
>     (including a physical distribution medium), accompanied by [...]

Again: irrelevant.

>     c) Convey individual copies of the object code with a copy of the
>     written offer to provide the Corresponding Source.  This
>     alternative is allowed only occasionally and noncommercially, and
>     only if you received the object code with such an offer, in accord
>     with subsection 6b.

AFAIK no such written offer is provided, and anyway, this is in general a bad and annoying way to be compliant, so I'd not recommend it.

>     d) Convey the object code by offering access from a designated
>     place (gratis or for a charge), and offer equivalent access to the
>     Corresponding Source in the same way through the same place at no
>     further charge.  You need not require recipients to copy the
>     Corresponding Source along with the object code.  If the place to
>     copy the object code is a network server, the Corresponding Source
>     may be on a different server (operated by you or a third party)
>     that supports equivalent copying facilities, provided you maintain
>     clear directions next to the object code saying where to find the
>     Corresponding Source.  Regardless of what server hosts the
>     Corresponding Source, you remain obligated to ensure that it is
>     available for as long as needed to satisfy these requirements.

This is I think the easiest way to be compliant in this case: Just upload a copy of the source tarball(s) into the GitHub release system along with the binaries. It's just one more file, so the infrastructure should be mostly there already, I guess?

It might even be OK to just generate custom "release notes" for those GitHub release items which contain a link to the sources (taken from the `build_tarballs.jl` file). However, this seems to be a bit of a gray area to me (because if that link for whatever reason grows stale, there is again a breach of the licensing terms; while if one just uploads the source files there right alongside the binaries, they are basically guaranteed to be always be available (or not) at the same time.

> 
>     e) Convey the object code using peer-to-peer transmission, provided
>     you inform other peers where the object code and Corresponding
>     Source of the work are being offered to the general public at no
>     charge under subsection 6d.

Not relevant here.

**Comment by staticfloat** [comment]
I don't think that we need to include source with JLLs.  We only need to point the way towards where the original source came from.  This falls under the third bullet point of [this issue](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/635#issuecomment-580018826), that basically says that we should include a link to the list of original sources within the JLL somewhere, possibly under a `SOURCES.txt` file that lists the source URLs and hashes for everything that was an input to the builder.  That should satisfy the GPL requirements.

**Comment by fingolfin** [comment]
No, you don't need to include source with JLLs -- but a pointer to the source of the original source is needed, and missing. One quibble is where this text needs to be; the GPL3 says:
> [...] provided you maintain clear directions next to the object code saying where to find the Corresponding Source.

It's not 100% clear what "next to the object code" means. I wonder whether providing a "SOURCES.txt" inside the JLL is enough to satisfy this. Note that people may download the binaries of a JLL without using the JLL. But I think that if one referenced the sources at https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases that would be enough (e.g. in that the "release notes" there could contain a text which says something like 
> For instructions obtaining the source code used to make the binaries below, please consult `SOURCES.txt` (link)


And yeah, you can just point to the "original" server from where the source code came, *but* then you must make sure to track changes on that server, per this part of the license;

> Regardless of what server hosts the Corresponding Source, you remain obligated to ensure that it is available for as long as needed to satisfy these requirements.

That can of course be done, but it's very easy to slip up on this. This is why I still think it would be much simpler to upload the source code alongside the other (generated) files (am I missing any downside to this). But that's just IMHO *shrug* :-)

**Comment by fingolfin** [comment]
Ah, perhaps I misunderstood: if you meant that `SOURCES.txt` will be in the .tar.gz archives containing the object code, then that would of course be perfectly fine, too

**Comment by Keno** [comment]
I don't think there's actually a legal problem here. The build_tarballs.jl are machine readable instructions for obtaining the corresponding source code. That's about as good as it gets. Of course, we can always make things easier. As dicussed elsewhere, it would be good to build a separate source archive, for various reasons.

**Comment by fingolfin** [comment]
I disagree: the build_tarballs.jl are not accessible from the JLL. That's actually an issue of its own: if a user stumbles over a JLL for the first time and thinks "nice, how do I make those", they have no way to find out about Yggdrasil, let alone the correct file in there.

**Comment by Keno** [comment]
Ah, I thought the jlls were linking to the build_tarballs that generated them. They probably should. That said, the source code provision argument has been read very broadly, so I still don't think there's a problem in practice. We should of course do better as I said.

**Comment by ViralBShah** [comment]
Can we change the title of this issue to something less scary sounding?

**Comment by fingolfin** [comment]
You are free to do that, it's your project, and it won't change the issue anyway. But I think the title is spot on. I do not agree with your assessment that everything is basically fine, I believe packages on https://github.com/JuliaBinaryWrappers are violating the GPL both in letter and in spirit. That said, I also believe there is no bad will, and healing the violation is rather easy.

I also think that If the FSF was aware of this (note: I won't tell them!), there is a good chance their email would have an equally or more so scary subject line :-).  I was at the wrong end of such an email exchange once for hosting a simple emacs lisp file w/o proper license on a website *shrug*.  (To be clear: that's not meant as a threat or anything, plus I am also hopeful the FSF would first try to resolve any such issue amicably; but they also wouldn't mince words).

Anyway, IANAL so I may be totally wrong in my assessment (though I *did* employ one specialized in GPL cases a decade ago, to litigate a GPL violation, and learned a lot from that, albeit focused on the German jurisdiction, which is different from US). Which is why I suggested in my initial comment that you might want to ask an actual lawyer (but one with a relevant specialization, ideally on software licensing).

**Comment by Keno** [comment]
I think the only issue is that we currently don't store the source that generated a JLL, so if the server that serves it goes away, we have a problem, because nobody has the source anymore (which is a problem for reasons unrelated to GPL compliance). As discussed that's a planned future enhancement, but not necessarily the most pressing issue right now. That said, if a GPL copyright holder wanted to request removal of a binary artifact for which they have removed the source from the internet or generally request removal, or even would just like additional acknowledgement, we would happily comply (if necessary by removing their code from Yggdrasil until we have better systems).

That said, I'm a little confused as to what you're trying to accomplish here. If it's "I'm trying to save the Julia people legal trouble", then we appreciate the concern and take it seriously, but the situation we're imagining here is that somebody is bringing a law suit that claims that our instructions aren't "next to" enough for the GPL purposes. That's possible of course, but having talked to people who do GPL enforcement as well as some of the people involved in drafting of the GPL, that does not seem like the kind of thing that they would really want to do.

If you're trying to improve the standard of GPL compliance, then sure this is reasonable, but also you've won here. We've agreed that it would be good to improve the way we manage the corresponding source and it'll probably happen in a future version. The problem with statements "the FSF will send you scary emails if you don't do what I think needs to be done right now and oh boy then you'll be in trouble" (I apologize if I exaggerated your intent - but that's how it read to me) is that it makes people less enthusiastic about working on this kind of thing. Just as threatening legal action is the fastest way to stop any technical progress when working with a big company, threatening drama is the quickest way to stop technical progress in an open source community (and of course here there's a bit of both).

I'm not saying you shouldn't have opened the issue - I'm happy it's being discussed and I'm glad people care about open source licensing, since it sometimes feels like I'm the only one that does :), but what I am saying is that there is a plan to fix it and I think letting that just happen in the natural course of development is the fastest way to actually get done what you want to have happen.

**Comment by ViralBShah** [comment]
@fingolfin Appreciate  your thoughts on the matter. While you are offering your best understanding, the title seems to suggest that the project is not in compliance. Hence I suggested updating the title. Perhaps something like "Discussion about GPL compliance"? I could of course have changed it myself - but didn't want to do that.

**Comment by Keno** [comment]
I have adjusted the title to reflect what I hope is the spirit of @fingolfin's request and to capture what the actionable problem here is (Improving access to the corresponding source). That jinxed a bit with @ViralBShah's latest comment, but @fingolfin if you feel the new title misrepresents the request, I'm happy to change it back or to something else.

**Comment by ViralBShah** [comment]
(I deleted my comment)

**Comment by fingolfin** [comment]
Just emphasis this once more: I really did not mean to threaten anybody, or cause drama. Sorry if I come across like that. And I was plain honest when I said that I don't mind if you rename the issue as you see fit (and I don't even think my opinion on this matters -- from my POV, this is your bug tracker, you decide what works best for you). Finally, I would be happy to let this issue sit untouched until it is resolved one day (in particular, I don't feel there is any particular urgency to resolve this), however that is -- the only reason I commented again was because I felt triggered to do so :-). But I'll shut up now (happily, trusting you'll resolve this as outlined).

**Comment by fingolfin** [comment]
I think this is now pretty much resolved *for new JLLs* resp. newly updated ones, see https://github.com/JuliaBinaryWrappers/GMP_jll.jl. Of course old one such as https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl do not yet benefit from this. One would need to regenerate old JLLs for that (see #876); it'd (probably) be fine to reuse the existing tarballs.

**Comment by ViralBShah** [comment]
Closing this as the original issue has been addressed, and new JLLs have pretty much been regenerated across the board (or will soon be). It would be best to open a specific issue with packages that are not compliant (if there are still some).
