### ISSUE TITLE
GR binaries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#11]
Currently, GR binaries are served from the GR repo on github. It seems like building GR in BB maybe difficult, but it would be nice to be able to serve the pre-built binaries through BinaryProvider (to make the experience and infrastructure of serving binaries uniform):

https://github.com/jheinen/GR.jl/blob/6e01760db801e5637a48d240069f1447d05c6077/deps/build.jl#L95

cc @jheinen

**Comment by jheinen** [comment]
Should we (just) host pre-built libraries there? Have there been problems with downloads from Github?  I only got such feedback from users in China, but that's probably another case ...

**Comment by ViralBShah** [comment]
Yes, I believe @staticfloat suggested somewhere that hosting the pre-built binaries is the easiest solution. And we can transition to using BinaryProvider to provide them.

**Comment by ViralBShah** [comment]
Should we plan to serve the GR binaries through BinaryProvider?

It is currently served from github by default:
https://github.com/jheinen/GR.jl/blob/master/deps/build.jl

**Comment by giordano** [comment]
I think GR requires QT, right? That's a pretty big beast

**Comment by ViralBShah** [comment]
Yes, I was just suggesting doing what is currently being done with pre-built binaries but in a more standard way.

**Comment by giordano** [comment]
@jheinen what's the difference between the different tarballs for Linux distributions?  I'm not sure BinaryProvider has currently the ability to install different libraries depending on the specific distribution flavour

**Comment by staticfloat** [comment]
BinaryProvider _can_ do it, but I also am interested to know what the difference is.  I bet it is related to the fact that GR doesn't ship its GUI toolkit, so the different versions are linked against different GUI toolkits, right?

**Comment by jheinen** [comment]
It's important to have dedicated binaries for different Linux flavours. Yes, Qt5 is the main reason for that. Please keep in mind, that GR is currently used by different communities (Python, C/C++, Julia, Ruby). Some users (including us) our using **one** GR installation for different languages (for many years). I don't want to break such installations.

We put a lot of effort in building a complete CI/CD environment at our site. Right now, we can build binaries for all supported platforms (ranging from Raspberry PIs to HPC systems) in a reasonable time. There's also support for different build systems (make, cmake), which was required by several scientific communities - the latter may build GR in seconds.

I am aware, that the GR `build.jl` script for Julia is ugly. As soon as there is more time, I can take care of a `BinaryProvider` solution for GR. At the moment, however, we have to concentrate on other things in order to move forward.

I ask for your understanding.

**Comment by ViralBShah** [comment]
@jheinen I was proposing using the pre-built GR binaries you provide, but make them available through the standard BinaryProvider infrastructure.

**Comment by ViralBShah** [comment]
We literally should just vendor the upstream GR.jl binaries through the BB infrastructure for now. Anyone interested?

**Comment by giordano** [comment]
The binaries are Linux distribution-dependent, right?  That makes it tricky to provide them through an automatically generated JLL package.

**Comment by ViralBShah** [comment]
I didn't realize that - having only dealt with non-linux GR binaries.

**Comment by giordano** [comment]
It's still possible to use `Artifacts.toml` instead of `BinaryProvider.jl`, at the cost of supporting Julia 1.3+.  This is for example what David Anthoff did in [`Electron.jl`](https://github.com/davidanthoff/Electron.jl)

**Comment by ViralBShah** [comment]
Perhaps I should update the issue - I do mean Artifacts and 1.3+ today would be fine. BinaryProvider was just what I thought we needed to do back then.

**Comment by ViralBShah** [comment]
How does Artifacts support linux distros?

**Comment by giordano** [comment]
The `Artifacts.toml` file simply contains the files of files to be downloaded, then one has to write some code to decide which file to actually download.  This is what JLL packages do, see for example [`FFTW_jll`](https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/blob/704f8580a0c9395721016c85a9ea376e272074fe/src/FFTW_jll.jl#L29-L40).  This isn't much different from `BinaryProvider.jl`, but it's cleaner.

**Comment by ViralBShah** [comment]
Ok - so GR.jl's [build.jl](https://github.com/jheinen/GR.jl/blob/master/deps/build.jl) file does the logic to pick the right file.

**Comment by giordano** [comment]
Exactly, that would need to be adapted to download an artifact listed in `Artifacts.toml`, instead of remote files hardcoded in `deps/build.jl`.  The difference would be really minimal.

If/when @barche will manage to build Qt with BinaryBuilder (https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/393) we may be able to directly build GR with BB as well.

**Comment by ViralBShah** [comment]
Would we upload the GR binaries to JuliaBinaryWrappers then, or pull them from the existing servers?

**Comment by giordano** [comment]
> Would we upload the GR binaries to JuliaBinaryWrappers then, or pull them from the existing servers?

I don't have a strong preference, but I don't see any advantage in moving the tarballs under JuliaBinaryWrappers

**Comment by ViralBShah** [comment]
The files are already published as github releases by @jheinen 
https://github.com/jheinen/GR.jl/blob/6e01760db801e5637a48d240069f1447d05c6077/deps/build.jl#L95

**Comment by ViralBShah** [comment]
With QT built in BB, it may be possible to attempt building GR.

**Comment by barche** [comment]
Yes, I think it is. Might take a stab at this, since it will fix https://github.com/barche/QML.jl/issues/92

**Comment by giordano** [comment]
See https://github.com/jheinen/GR.jl/issues/314#issuecomment-667664353

**Comment by barche** [comment]
I have put my WIP in PR #1506 , @jheinen feel free to comment / correct as needed.

**Comment by ViralBShah** [comment]
Nice to see that all this just came through! However, Do I really need all these X libraries on MacOS? It took about 10-20 sec to download Qt_jll which is about 58M (@staticfloat Is this reasonable?). The rest flew by.

```
(@v1.5) pkg> add GR_jll
   Updating registry at `~/.julia/registries/General`
######################################################################## 100.0%
  Resolving package versions...
  Installed Xorg_xcb_util_keysyms_jll ──── v0.4.0+0
  Installed Qt_jll ─────────────────────── v5.15.0+3
  Installed Wayland_protocols_jll ──────── v1.18.0+3
  Installed Gettext_jll ────────────────── v0.20.1+6
  Installed GLFW_jll ───────────────────── v3.3.2+0
  Installed Xorg_libX11_jll ────────────── v1.6.9+3
  Installed Xorg_libXrandr_jll ─────────── v1.5.2+3
  Installed GR_jll ─────────────────────── v0.51.2+0
  Installed Xorg_libXi_jll ─────────────── v1.7.10+3
  Installed Libuuid_jll ────────────────── v2.34.0+6
  Installed Xorg_xcb_util_image_jll ────── v0.4.0+0
  Installed Xorg_libXcursor_jll ────────── v1.2.0+3
  Installed Xorg_xcb_util_wm_jll ───────── v0.4.1+0
  Installed LZO_jll ────────────────────── v2.10.0+2
  Installed Libmount_jll ───────────────── v2.34.0+2
  Installed Xorg_xcb_util_jll ──────────── v0.4.0+0
  Installed Pixman_jll ─────────────────── v0.38.4+4
  Installed Cairo_jll ──────────────────── v1.16.0+5
  Installed Libglvnd_jll ───────────────── v1.3.0+1
  Installed Xorg_libXfixes_jll ─────────── v5.0.3+3
  Installed Wayland_jll ────────────────── v1.17.0+3
  Installed Xorg_libXau_jll ────────────── v1.0.9+3
  Installed Qhull_jll ──────────────────── v2019.1.0+2
  Installed Expat_jll ──────────────────── v2.2.7+5
  Installed Xorg_xcb_util_renderutil_jll ─ v0.3.9+0
  Installed Xorg_xkeyboard_config_jll ──── v2.27.0+3
  Installed Libgpg_error_jll ───────────── v1.36.0+2
  Installed xkbcommon_jll ──────────────── v0.9.1+3
  Installed PCRE_jll ───────────────────── v8.42.0+3
  Installed Libgcrypt_jll ──────────────── v1.8.5+3
  Installed Xorg_libXdmcp_jll ──────────── v1.1.3+3
  Installed Xorg_libXrender_jll ────────── v0.9.10+3
  Installed Xorg_libpthread_stubs_jll ──── v0.1.0+2
  Installed XSLT_jll ───────────────────── v1.1.33+3
  Installed Xorg_libxcb_jll ────────────── v1.13.0+2
  Installed Glib_jll ───────────────────── v2.59.0+3
  Installed Xorg_xtrans_jll ────────────── v1.4.0+2
  Installed Xorg_libxkbfile_jll ────────── v1.1.0+3
  Installed Xorg_xkbcomp_jll ───────────── v1.4.2+3
  Installed Xorg_libXext_jll ───────────── v1.3.4+3
  Installed Fontconfig_jll ─────────────── v2.13.1+13
  Installed Libffi_jll ─────────────────── v3.2.1+3
  Installed Xorg_libXinerama_jll ───────── v1.1.4+3
Downloading artifact: GR
Downloading artifact: Qt
Downloading artifact: Wayland_protocols
Downloading artifact: GLFW
Downloading artifact: Gettext
Downloading artifact: LZO
Downloading artifact: Cairo
Downloading artifact: Pixman
Downloading artifact: Qhull
Downloading artifact: Expat
Downloading artifact: Libgpg_error
Downloading artifact: PCRE
Downloading artifact: Libgcrypt
Downloading artifact: Glib
Downloading artifact: XSLT
Downloading artifact: Fontconfig
Downloading artifact: Libffi
Updating `~/.julia/environments/v1.5/Project.toml`
  [d2c73de3] + GR_jll v0.51.2+0
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [83423d85] + Cairo_jll v1.16.0+5
  [2e619515] + Expat_jll v2.2.7+5
  [a3f928ae] + Fontconfig_jll v2.13.1+13
  [0656b61e] + GLFW_jll v3.3.2+0
  [d2c73de3] + GR_jll v0.51.2+0
  [78b55507] + Gettext_jll v0.20.1+6
  [7746bdde] + Glib_jll v2.59.0+3
  [dd4b983a] + LZO_jll v2.10.0+2
  [e9f186c6] + Libffi_jll v3.2.1+3
  [d4300ac3] + Libgcrypt_jll v1.8.5+3
  [7e76a0d4] + Libglvnd_jll v1.3.0+1
  [7add5ba3] + Libgpg_error_jll v1.36.0+2
  [4b2f31a3] + Libmount_jll v2.34.0+2
  [38a345b3] + Libuuid_jll v2.34.0+6
  [2f80f16e] + PCRE_jll v8.42.0+3
  [30392449] + Pixman_jll v0.38.4+4
  [784f63db] + Qhull_jll v2019.1.0+2
  [ede63266] + Qt_jll v5.15.0+3
  [a2964d1f] + Wayland_jll v1.17.0+3
  [2381bf8a] + Wayland_protocols_jll v1.18.0+3
  [aed1982a] + XSLT_jll v1.1.33+3
  [4f6342f7] + Xorg_libX11_jll v1.6.9+3
  [0c0b7dd1] + Xorg_libXau_jll v1.0.9+3
  [935fb764] + Xorg_libXcursor_jll v1.2.0+3
  [a3789734] + Xorg_libXdmcp_jll v1.1.3+3
  [1082639a] + Xorg_libXext_jll v1.3.4+3
  [d091e8ba] + Xorg_libXfixes_jll v5.0.3+3
  [a51aa0fd] + Xorg_libXi_jll v1.7.10+3
  [d1454406] + Xorg_libXinerama_jll v1.1.4+3
  [ec84b674] + Xorg_libXrandr_jll v1.5.2+3
  [ea2f1a96] + Xorg_libXrender_jll v0.9.10+3
  [14d82f49] + Xorg_libpthread_stubs_jll v0.1.0+2
  [c7cfdc94] + Xorg_libxcb_jll v1.13.0+2
  [cc61e674] + Xorg_libxkbfile_jll v1.1.0+3
  [12413925] + Xorg_xcb_util_image_jll v0.4.0+0
  [2def613f] + Xorg_xcb_util_jll v0.4.0+0
  [975044d2] + Xorg_xcb_util_keysyms_jll v0.4.0+0
  [0d47668e] + Xorg_xcb_util_renderutil_jll v0.3.9+0
  [c22f9ab0] + Xorg_xcb_util_wm_jll v0.4.1+0
  [35661453] + Xorg_xkbcomp_jll v1.4.2+3
  [33bec58e] + Xorg_xkeyboard_config_jll v2.27.0+3
  [c5fb5394] + Xorg_xtrans_jll v1.4.0+2
  [d8fb68d0] + xkbcommon_jll v0.9.1+3
```

**Comment by ViralBShah** [comment]
Is there a way to speed this up? This would add significantly to Plots.jl precompile times, and this is all pre-built libraries.
```
julia> @time using GR_jll
[ Info: Precompiling GR_jll [d2c73de3-f751-5644-a686-071e5b155ba9]
 34.933056 seconds (3.38 M allocations: 205.577 MiB, 0.12% gc time)
```

**Comment by barche** [comment]
The X libraries are just empty shells on all platforms except linux/freeBSD as far as I understand. The JLLs probably still get precompiled, though. Note that many or all of these are also needed for GLFW and Cairo.

Qt is bigger than it needs to be, but at about 60MB still a lot smaller than the hundreds of megabytes from the official download (which includes examples and so on). It can probably be trimmed down to maybe 30 - 40MB, but then we would have to make separate packages for things like the QML graphing and 3D libraries. I don't really think that is worth the effort. We are wasting a lot of memory by dlopening all the libraries, but this is soon to be fixed by the lazy loading.
