### ISSUE TITLE
Looking for Leptonica and Tesseract binaries under JuliaBinaryWrappers

### ISSUE THREAD

**Issue by sambitdash** [JuliaPackaging/Yggdrasil#118]
Binary builder needed for Tesseract OCR and Leptonica Image Processing Library

https://github.com/tesseract-ocr/tesseract
http://www.leptonica.org/source/leptonica-1.78.0.tar.gz

Tesseract utilizes Leptonica internally. It's best both are built together.

**Comment by giordano** [comment]
For reference, packages on Arch Linux:

* https://www.archlinux.org/packages/community/x86_64/tesseract/
* https://www.archlinux.org/packages/community/x86_64/leptonica/

I had a quick look at giflib, one of the dependencies, the latest version is quite painful to build as it has only a `Makefile`, (no configuration script) with hardcoded extensions (`.so` for shared libraries) and flags (like `-shared`), this would work only on Linux/FreeBSD, if at all.  It would probably require a lot of work to patch the Makefile.
