### ISSUE TITLE
Add SDL2 plugins ?

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaPackaging/Yggdrasil#122]
We would  like to switch SimpleDirectMediaLayer.jl to BinaryProvider, I've tried to setup a builder but @giordano pointed out it was already here. One remaining problem is that we need SDL_ttf, and SDL_mixer as well. I also have a PR ready for SDL_image in SimpleDirectMediaLayer.jl, and people might want other [ones](http://www.libsdl.org/projects/ ) in the future:

https://github.com/jonathanBieler/SimpleDirectMediaLayer.jl/pull/39

**Comment by NHDaly** [comment]
CC: @aviks We'll probably want to fix this before encouraging widespread use of SDL2 in julia!

**Comment by giordano** [comment]
Any idea about how to tackle #123 would be welcome 🙂

**Comment by aviks** [comment]
`libSDL2_ttf` seems done? We need `libSDL2_mixer` and `libSDL2_image` now, I think.

**Comment by aviks** [comment]
There seems to be windows binaries available: 

Mixer: http://www.libsdl.org/projects/SDL_mixer/
Image: http://www.libsdl.org/projects/SDL_image/

However, they'll still require dependencies (libvorbis, libpng etc), so it may be better to build them ourselves?

**Comment by aviks** [comment]
WiP in #428 and #429

**Comment by giordano** [comment]
So this can be closed now?

**Comment by aviks** [comment]
This can now be closed.
