### ISSUE TITLE
[Qt] Issues using the Qt package

### ISSUE THREAD

**Issue by barche** [JuliaPackaging/Yggdrasil#1274]
## Windows
On Windows, the Qt5Core dll doesn't load:

```
julia> using jlqml_jll
[ Info: Precompiling jlqml_jll [6b5019fb-a83d-5b4e-a9f7-678a36c28df7]
ERROR: LoadError: LoadError: InitError: could not load library "C:\Users\bartj\.julia\artifacts\783542c006fe1b57d402aecf4a50cd3756ee5a8f\bin\Qt5Core.dll"
The specified module could not be found.
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109
 [2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
 [3] __init__() at C:\Users\bartj\.julia\packages\Qt_jll\BGH7E\src\wrappers\x86_64-w64-mingw32-cxx11.jl:94
 [4] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
 [5] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:781
 [6] _require(::Base.PkgId) at .\loading.jl:1006
 [7] require(::Base.PkgId) at .\loading.jl:927
 [8] require(::Module, ::Symbol) at .\loading.jl:922
 [9] include(::Module, ::String) at .\Base.jl:377
 [10] include(::String) at C:\Users\bartj\.julia\packages\jlqml_jll\leQSD\src\jlqml_jll.jl:1
 [11] top-level scope at C:\Users\bartj\.julia\packages\jlqml_jll\leQSD\src\jlqml_jll.jl:50
 [12] include(::Module, ::String) at .\Base.jl:377
 [13] top-level scope at none:2
 [14] eval at .\boot.jl:331 [inlined]
 [15] eval(::Expr) at .\client.jl:449
 [16] top-level scope at .\none:3
during initialization of module Qt_jll
in expression starting at C:\Users\bartj\.julia\packages\jlqml_jll\leQSD\src\wrappers\x86_64-w64-mingw32-cxx11.jl:5
in expression starting at C:\Users\bartj\.julia\packages\jlqml_jll\leQSD\src\jlqml_jll.jl:43
```

Directly dlopening doesn't work either:

```julia
dlopen(raw"C:\Users\bartj\.julia\artifacts\783542c006fe1b57d402aecf4a50cd3756ee5a8f\bin\Qt5Core.dll")
ERROR: could not load library "C:\Users\bartj\.julia\artifacts\783542c006fe1b57d402aecf4a50cd3756ee5a8f\bin\Qt5Core.dll"
The specified module could not be found.
```

However, after a cd to the artifact bin dir:

```julia
julia> cd(raw"C:\Users\bartj\.julia\artifacts\783542c006fe1b57d402aecf4a50cd3756ee5a8f\bin")
julia> dlopen(raw"./Qt5Core.dll")
Ptr{Nothing} @0x0000000041870000
```

Any ideas on why this would happen? I don't need to add all libraries in the bin directory as products, do I?

## MacOS

Fails because the platform plugin can't be initialized. I think I know how to fix this one.

**Comment by giordano** [comment]
> I don't need to add all libraries in the bin directory as products, do I?

All products are automatically dlopened, so you need to list as products everything you want to be sure will be open.  I hope the order is not important, because we'd need https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/669.

**Comment by giordano** [comment]
The need to `cd` to the directory sounds very much like https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/669#issuecomment-586546677

**Comment by giordano** [comment]
BTW, to find out what module is missing, try using https://github.com/giordano/DependencyWalker.jl

**Comment by barche** [comment]
Thanks for the suggestions, DependencyWalker was a big help. What I found out is:
* Need to call `dlopen("libz")` in the Qt_jll init function. Not sure why that doesn't happen automatically?
* Need Fontconfig_jll as a real dependency after all (was also the problem on Mac)
* Need to add Qt5QmlWorkerScript.dll as a product

**Comment by giordano** [comment]
> Not sure why that doesn't happen automatically?

You know, you insisted to not have any runtime dependency, not sure why you expected it to magically work :slightly_smiling_face: 

> Need Fontconfig_jll as a real dependency after all (was also the problem on Mac)

:slightly_smiling_face:

**Comment by barche** [comment]
> > Not sure why that doesn't happen automatically?
> 
> You know, you insisted to not have any runtime dependency, not sure why you expected it to magically work 🙂

Yes, the fontconfig thing is entirely my fault ;)

But libz never was a dependency, should it be added explicitly? It is used from the Julia lib directory now?

**Comment by giordano** [comment]
> But libz never was a dependency, should it be added explicitly?

It's probably pulled by something else (Fontconfig maybe?), Qt finds it and links to it.  Since Qt links to it, yes, it may be better to list it explicitly.

> It is used from the Julia lib directory now?

```julia
julia> using Libdl

julia> filter!(lib -> occursin("z", lib), dllist())
0-element Array{String,1}
```

**Comment by barche** [comment]
Everything is now working for me, on Mac and Windows :)
