### ISSUE TITLE
Git_jll: `fatal: unable to find remote helper for 'https'`

### ISSUE THREAD

**Issue by omus** [JuliaPackaging/Yggdrasil#1299]
It appears that the `git` compiled in Git_jll does not have support for HTTPS:
```julia
julia> using Git_jll


julia> function julia_versions(url)
           output = git() do git_path
               read(`$git_path ls-remote --tags $url`, String)
           end
           tags = split(replace(output, r".*\/" => ""))
           return VersionNumber.(filter!(v -> !endswith(v, "^{}"), tags))
       end
julia_versions (generic function with 1 method)

julia> julia_versions("git@github.com:JuliaLang/julia.git")
93-element Array{VersionNumber,1}:
 v"0.1.0"
 v"0.1.1"
 v"0.1.2"
 v"0.2.0"
 v"0.2.0-rc1"
 v"0.2.0-rc2"
 v"0.2.0-rc3"
 v"0.2.0-rc4"
 v"0.2.1"
 v"0.3.0"
 v"0.3.0-rc1"
 ⋮
 v"1.3.0-rc4"
 v"1.3.0-rc5"
 v"1.3.1"
 v"1.4.0"
 v"1.4.0-rc1"
 v"1.4.0-rc2"
 v"1.4.1"
 v"1.4.2"
 v"1.5.0-beta1"
 v"1.5.0-rc1"

julia> julia_versions("https://github.com/JuliaLang/julia.git")
fatal: unable to find remote helper for 'https'
ERROR: failed process: Process(`/Users/omus/.julia/artifacts/31106432777b044b8cf9d8b3a40a49d0312a535f/bin/git ls-remote --tags https://github.com/JuliaLang/julia.git`, ProcessExited(128)) [128]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] read(::Cmd) at ./process.jl:412
 [3] read(::Cmd, ::Type{String}) at ./process.jl:421
 [4] (::var"#3#5"{String})(::String) at ./REPL[2]:3
 [5] (::Git_jll.var"#8#9"{var"#3#5"{String}})() at /Users/omus/.julia/packages/Git_jll/FLjrv/src/wrappers/x86_64-apple-darwin14.jl:43
 [6] withenv(::Git_jll.var"#8#9"{var"#3#5"{String}}, ::Pair{String,String}, ::Vararg{Pair{String,String},N} where N) at ./env.jl:161
 [7] git(::var"#3#5"{String}; adjust_PATH::Bool, adjust_LIBPATH::Bool) at /Users/omus/.julia/packages/Git_jll/FLjrv/src/wrappers/x86_64-apple-darwin14.jl:42
 [8] git at /Users/omus/.julia/packages/Git_jll/FLjrv/src/wrappers/x86_64-apple-darwin14.jl:25 [inlined]
 [9] julia_versions(::String) at ./REPL[2]:2
 [10] top-level scope at REPL[4]:1
```

**Comment by giordano** [comment]
Duplicate of #284 and #452.  You need to set the environment variables `GIT_EXEC_PATH` and `GIT_SSL_CAINFO`:
```julia
ENV["GIT_SSL_CAINFO"] = joinpath(dirname(Sys.BINDIR), "share", "julia", "cert.pem")
ENV["GIT_EXEC_PATH"] = joinpath(dirname(Git_jll.artifact_dir, "libexec", "git-core")
```

In general, you may want to use [`GitCommand.jl`](https://github.com/bcbi/GitCommand.jl) which already takes care of everything, instead of `Git_jll` directly

**Comment by omus** [comment]
Thanks for the quick response. One follow up question: why does the `git()` command from Git_jll not define those environmental variables? Seems like it would be a reasonable default if they aren't already defined

**Comment by giordano** [comment]
Because the function wrappers are very thin wrappers automatically generated that only set the variables needed to find the required libraries, nothing else.  See https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/687 for a broader discussion about relocatability.

**Comment by omus** [comment]
I just noticed this was also asked in https://github.com/JuliaPackaging/Yggdrasil/issues/284#issuecomment-565409669. Looking at GitCommand.jl I noticed it has additional dependencies which I was hoping to avoid. Maybe there's room for a Git.jl too.

**Comment by DilumAluthge** [comment]
> I just noticed this was also asked in [#284 (comment)](https://github.com/JuliaPackaging/Yggdrasil/issues/284#issuecomment-565409669). Looking at GitCommand.jl I noticed it has additional dependencies which I was hoping to avoid. Maybe there's room for a Git.jl too.

@omus I'm removing the REPL code from GitCommand.jl and moving it to GitRepl.jl. So then GitCommand.jl will only have one dependency (Git_jll.jl).

**Comment by DilumAluthge** [comment]
Will this meet your use case?
