### ISSUE TITLE
tree-sitter-* wrappers?

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaPackaging/Yggdrasil#1302]
Currently there's only one as far as I can see, namely [tree_sitter_c/build_tarballs.jl](https://github.com/JuliaPackaging/Yggdrasil/blob/master/T/tree_sitter_c/build_tarballs.jl), which builds `libtreesitter_c` as well as the runtime lib `libtreesitter`. I'd like to add additional tree-sitter parsers, but wasn't sure whether we'd what them as separate jlls for each individual parser, or just a single one for all those available?

I'd prefer to split them up into separate jlls so that packages don't have to install tonnes of binaries just to access a single parser. If I followed the way tree_sitter_c is being built we'd end of with lots of `libtreesitter.so`s floating around needlessly, I think? Would it be alright to split that out into a separate `tree_sitter_jll` and then have individual `tree_sitter_*_jll`s for each of the built parsers?

**Comment by giordano** [comment]
Sorry, I missed this issue before.  In general I agree that modularity is better, however one point is not clear: would they all come from the same source or different sources?

**Comment by MichaelHatherly** [comment]
> would they all come from the same source or different sources?

Difference sources, each parser is a separate repo.

For reference here's some of the build scripts I've put together so far: https://github.com/MichaelHatherly/tree-sitter-binaries.

**Comment by giordano** [comment]
> Difference sources, each parser is a separate repo.

Then a jll package for each source looks totally fine
