### ISSUE TITLE
[Qt] Windows without OpenGL driver error

### ISSUE THREAD

**Issue by barche** [JuliaPackaging/Yggdrasil#1330]
When using Qt (especially QML or another OpenGL-using component) on a Windows system without an OpenGL 2.0 driver, the application will crash. To solve this we need to:

1. Build Qt using `- opengl dynamic` for WIndows (easy enough, got it working locally)
2. Ship opengl32sw.dll, which will require building it from MESA, i.e. this requires adding a build_tarballs for that and setting it as dependency for Qt ( possibly useful but old guide: https://wiki.qt.io/Cross_compiling_Mesa_for_Windows )

As a workaround for QML, we can set the `QT_QUICK_BACKEND=software` environment variable. Due to the way Qt treats environment variables this needs to be set outside of Julia, even setting it in `ENV` before loading the Qt JLL will not pass it along.

**Comment by giordano** [comment]
@barche can this be closed?

**Comment by barche** [comment]
Ah, yes, forgot about that, sorry :)
