### ISSUE TITLE
Julia_jll 1.4.1 binary for macOS contains wrong header files

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/Yggdrasil#1372]
The file Julia.v1.4.1.x86_64-apple-darwin14-libgfortran4-cxx11.tar.gz contains the wrong header files. For example, it has this `julia_version.h`:
```C
// This is an autogenerated header file
#ifndef JL_VERSION_H
#define JL_VERSION_H
#define JULIA_VERSION_STRING "1.6.0-DEV"
#define JULIA_VERSION_MAJOR 1
#define JULIA_VERSION_MINOR 6
#define JULIA_VERSION_PATCH 0
#define JULIA_VERSION_IS_RELEASE 0
#endif
```
There are other diffs compared to the actual Julia 1.4.1 headers.

The headers seem fine in 1.4.2.

However, all packages in Yggdrasil using Julia_jll right now specifically ask for Julia_jll 1.4.1, so perhaps this should still be addressed?

**Comment by fingolfin** [comment]
I wonder if we should just withdraw Julia_jll? If one can even do that... ah well *shrug*

**Comment by vchuravy** [comment]
Yes you can yank all versions, better than leaving something broken around.
