### ISSUE TITLE
Binaries broken on julia master

### ISSUE THREAD

**Issue by thofma** [JuliaPackaging/Yggdrasil#1436]
The FLINT binaries bundled in `FLINT_jll` are broken on julia > 1.5 and here is the reason: Yggdrasil runners are using julia 1.4 something (or something newer, but nothing beyond julia 1.5). This means that they will pull in GMP version 6.1.2 when adding GMP as a binary dependency during the build. On the other hand, for the latest julia version, GMP was bumped to 6.2. In particular, if you add `FLINT_jlll` on julia master (via `]pkg add`), you will get `GMP_jll` version 6.2. So if you `]add FLINT_jll`, you will get GMP 6.2. Here the problem starts:

- FLINT built against GMP 6.1.2 will work with runtime GMP 6.1.2 (no surpise), but is broken with runtime GMP 6.2 (they changed the way how allocations are done, but details are not important).
- FLINT bulit against GMP 6.2 will work with runtime GMP 6.2 and GMP 6.1.2.

So, is there a way to put FLINT binaries into JuliaBinaryWrappers/ that are built against GMP 6.2?

**Comment by fingolfin** [comment]
I'd prefer if FLINT gets a new release which contains https://github.com/wbhart/flint2/pull/814 and then we don't need to care about the GMP version (CC @wbhart).

**Comment by thofma** [comment]
Even better.

**Comment by thofma** [comment]
Fixed it upstream.

**Comment by fingolfin** [comment]
Is there already a PR with Flint 2.6.3 then? I didn't find one

**Comment by thofma** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/1443
