### ISSUE TITLE
Need a libjulia_jll

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#1525]
As discussed in https://github.com/JuliaPackaging/Yggdrasil/pull/1478#issuecomment-678551191, we need a libjulia_jll package to simplify the build process for libraries using libcxxwrap_julia_jll.

The packaging process is similar to what is done for Julia_jll.

**Comment by fingolfin** [comment]
Could someone briefly explain what the difference between libjulia_jll and Julia_jll would be ? Thanks!

**Comment by giordano** [comment]
It would ship _only_ `libjulia`, which has looser ABI constraint (only the C++ string ABI, nothing about libgfortran) than the whole "Julia" with binary libraries used by the standard libraries, which include OpenBLAS

**Comment by fingolfin** [comment]
would it also include the headers?

**Comment by giordano** [comment]
Maybe?

**Comment by fingolfin** [comment]
Actually that was a stupid question, sorry: to be useful the headers need to be there. So naively this could be created by adapting the Julia_jll recipe and only keeping PREFIX/include and PREFIX/lib/libjulia.*. I could give that a try tonight, and also adding a variant for 1.3

**Comment by barche** [comment]
> It would ship _only_ `libjulia`, which has looser ABI constraint (only the C++ string ABI, nothing about libgfortran)

I'm not sure it even needs the string ABI, isn't `libjulia` pure C?

**Comment by giordano** [comment]
No idea to be honest :joy:

**Comment by giordano** [comment]
```
% ldd libjulia.so
        linux-vdso.so.1 (0x00007ffc8f5ee000)
        libunwind.so.8 => /usr/lib/./julia/libunwind.so.8 (0x00007fda0a20d000)
        libLLVM-9jl.so => /usr/lib/./julia/libLLVM-9jl.so (0x00007fda06aaa000)
        libdl.so.2 => /usr/lib/./libdl.so.2 (0x00007fda06aa4000)
        librt.so.1 => /usr/lib/./librt.so.1 (0x00007fda06a99000)
        libpthread.so.0 => /usr/lib/./libpthread.so.0 (0x00007fda06a77000)
        libstdc++.so.6 => /usr/lib/./julia/libstdc++.so.6 (0x00007fda066f9000)
        libm.so.6 => /usr/lib/./libm.so.6 (0x00007fda065b1000)
        libgcc_s.so.1 => /usr/lib/./julia/libgcc_s.so.1 (0x00007fda06399000)
        libc.so.6 => /usr/lib/./libc.so.6 (0x00007fda061d0000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fda0ac16000)% nm libjulia.so | c++filt| grep "\[abi:cxx11\]"
000000000003dfb0 t jl_format_filename[abi:cxx11](llvm::StringRef)
000000000012d820 t jl_get_llvm_target[abi:cxx11](bool, unsigned int&)
000000000003de90 t jl_get_cpu_name_llvm[abi:cxx11]()
000000000003ee00 t jl_get_cpu_features_llvm[abi:cxx11]()
000000000012c520 t jl_get_llvm_disasm_target[abi:cxx11]()
00000000007cc8f0 b guard variable for jl_get_llvm_disasm_target[abi:cxx11]()::res
000000000009b3d0 t function_sig_t::generate_func_sig[abi:cxx11](char const*)
                 U llvm::sys::getProcessTriple[abi:cxx11]()@@JL_LLVM_9.0
0000000000130790 t JuliaOJIT::getMangledName[abi:cxx11](llvm::StringRef)
0000000000130860 t JuliaOJIT::getMangledName[abi:cxx11](llvm::GlobalValue const*)
00000000001425e0 t llvm::ErrorInfoBase::message[abi:cxx11]() const
                 U llvm::SubtargetFeatures::getString[abi:cxx11]() const@@JL_LLVM_9.0
00000000007cc900 b jl_get_llvm_disasm_target[abi:cxx11]()::res
00000000001f3b00 r function_sig_t::generate_func_sig[abi:cxx11](char const*)::__PRETTY_FUNCTION__
```
There is some C++ string ABI specificness here

**Comment by barche** [comment]
Aha, good to know!

**Comment by giordano** [comment]
Valentin pointed out on slack that it might be possible to cross-compile `libjulia` from source with BinaryBuilder.  That would be a much better option as we could build it for all versions of Julia and all platforms.  Provided that it'll actually build :stuck_out_tongue:

**Comment by vchuravy** [comment]
I don't see why it wouldn't! We cross-compile Julia from Linux to Windows
(granted that is with MingW), but the build system support is there.

**Comment by giordano** [comment]
> I don't see why it wouldn't!

FreeBSD can be quite nasty :trollface:
