### ISSUE TITLE
PETSc libraries with scalar types

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/Yggdrasil#1527]
PETSc can only be built supporting a single scalar type: the current uses the default (`Float64`).

One way around this is to build a library for each scalar type (`Float32`, `ComplexF32`, `ComplexF64`): something similar is done for FFTW.

cc: @jd-lara @giordano @stevengj

**Comment by jd-lara** [comment]
Is this related to the comment in the original PETSc PR?

**Comment by simonbyrne** [comment]
No.
