### ISSUE TITLE
Builder Request: LAGraph

### ISSUE THREAD

**Issue by Wimmerer** [JuliaPackaging/Yggdrasil#1627]
This library: https://github.com/GraphBLAS/LAGraph contains a number of algorithms based on SuiteSparseGraphBLAS which is already here. It would be very nice to include it as well.

**Comment by DrTimothyAldenDavis** [comment]
LAGraph is getting polished and reorganized (see the reorg branch).  We're actively working on it, and the API getting more and more polished but hasn't been finalized yet.  We hope to have a robust v1.0 soon.

**Comment by Wimmerer** [comment]
Alright I will build and wrap once v1.0 is out.
