### ISSUE TITLE
The CI plan

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/Yggdrasil#173]
I'd like to set up a CI system to make both both building and deploying more painless.  In short, users should be able to submit PRs, have a CI bot attempt to build it, and then when it gets merged it, it should be rebuilt and registered automatically.  We want this CI to run on our own hardware (so that we have no time limits and so that we can cache artifacts and whatnot) so we'll use GitLab CI.

Here's the general overview:
* GitHub PRs and commits to `master` trigger a GitLab CI runner
* GitLab CI runner launches inside docker container that has BB already built (this docker image already exists, it gets built automatically every time I push something to BB [0], you can run it with `docker run -ti staticfloat/binarybuilder.jl`)
* The GitLab CI script looks at environment variabled provided by the GitLab CI runner [1] and `git` info to figure out the following pieces of information:
  - What files were just changed?  Use that to build up a list of recipes I need to build for this changeset.
  - Am I a PR or a push to `master`?  If I'm a PR, I'm going to be building with just `--verbose`.  If I'm a push to `master`, I'm going to be building with `--verbose --deploy --register`.
* We will need to be able to exclude certain builders, for instance LLVM should probably never be done automatically, since it takes dozens of hours to do a full rebuild of that.  Same with the rootfs.

For now, we're just going to run the builds and we'll inspect the textual output.  Long-term, I would like to have a system where things like audit passes and whatnot have their information saved in a machine-parsable way so that we can quickly summarize the auditor output.  Right now, we ignore most audit output and just keep it around so that we can look back once something breaks to try and find a hint as to why it broke; we are only ever going to get stricter though, so having this information easily viewable will eventually be important.  :)

[0] https://cloud.docker.com/u/staticfloat/repository/docker/staticfloat/binarybuilder.jl
[1] https://docs.gitlab.com/ee/ci/variables/

**Comment by ararslan** [comment]
> so we'll use GitLab CI.

FYI, GitHub is planning to introduce GitHub Actions using self-hosted machines, akin to GitLab Runner. So we may eventually be able to integrate this process entirely with GitHub at some point.

**Comment by staticfloat** [comment]
Mosè is currently in the process of convincing me that we should use Azure pipelines. XD

The main argument to me being that AP allows for dynamic job generation [0], so we can do something like write a little script that inspects the previous `git` commit, determines which builders need to be rebuilt, then creates a separate job for each.

[0] https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-configuration

**Comment by giordano** [comment]
Fixed by #175.  We eventually used Azure Pipellines: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build?definitionId=1
