### ISSUE TITLE
Builder Request: libudev

### ISSUE THREAD

**Issue by Gnimuc** [JuliaPackaging/Yggdrasil#1741]
In relative new Linux distributions, libudev is often integrated with systemd, but systemd is a relatively large project that is not trivial to build. An alternative one is eudev, the build script on the [LFS](http://www.linuxfromscratch.org/lfs/view/stable/chapter08/eudev.html) looks doable.

**Comment by giordano** [comment]
systemd/udev is the reason why I gave up on pulseaudio

**Comment by bramtayl** [comment]
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/2501
