### ISSUE TITLE
Openresty JLL not created

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/Yggdrasil#2006]
A build_tarballs.jl for OpenResty was submitted and merged at https://github.com/JuliaPackaging/Yggdrasil/pull/1016 but the JLL package doesn't seem to have been generated correctly: https://github.com/JuliaBinaryWrappers/Openresty_jll.jl

**Comment by tanmaykm** [comment]
Thanks @giordano 

But JLL registration seems to have failed again with this error: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=6999&view=logs&j=7d249280-941f-589f-e608-11cf16f226cd&t=d281276f-0fef-50c4-9b35-e3d6b37a2a46

Any idea why?

**Comment by tanmaykm** [comment]
I wonder if it is because folders inside `site` are all empty? Local build is going through if I remove `site` from list of products. Will send a PR.
