### ISSUE TITLE
clang executable in Clang_jll does not work on macOS

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/Yggdrasil#2025]
On macOS 10.14.6 with Julia 1.5.2, I get this:
```
(v1.5) pkg> status
Status `/private/tmp/JULIA_DEPOT_PATH/environments/v1.5/Project.toml`
  [0ee61d77] Clang_jll v9.0.1+4

julia> using Clang_jll

julia> Clang_jll.clang() do exe
           run(`$exe --help`)
       end
dyld: Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /tmp/JULIA_DEPOT_PATH/artifacts/74b247b0f53ce91c334e5a1c16a7d5d871cf8d79/tools/clang
  Reason: image not found
```

With Julia 1.6.0-DEV.1397 I don't even get that far because of an LLVM mismatch I assume that means a suitable Clang_jll variant for LLVM 11 is needed):
```
(v1.6) pkg> status
Status `/private/tmp/JULIA_DEPOT_PATH/environments/v1.6/Project.toml`
  [0ee61d77] Clang_jll v9.0.1+4

julia> using Clang_jll
ERROR: InitError: could not load library "/tmp/JULIA_DEPOT_PATH/artifacts/74b247b0f53ce91c334e5a1c16a7d5d871cf8d79/lib/libclang.dylib"
```

**Comment by staticfloat** [comment]
> dyld: Library not loaded: @rpath/libc++.1.dylib

Try adding `/usr/lib` to `DYLD_FALLBACK_LIBRARY_PATH`.


> With Julia 1.6.0-DEV.1397 I don't even get that far because of an LLVM mismatch I assume that means a suitable Clang_jll variant for LLVM 11 is needed):

Yep, we need to build a `Clang_jll` from LLVM 11.

**Comment by fingolfin** [comment]
Thanks! Seems rather obvious in hindsight, oops 😊 . Indeed, this works:
```julia
withenv("DYLD_FALLBACK_LIBRARY_PATH" => "/usr/lib") do
  Clang_jll.clang() do exe
    run(`$exe --help`)
  end
end
```
I managed to compile a simple C program on macOS and Linux x86_64 now, nice!

I guess some distros will have their headers/libraries in unusual places; or headers might not be installed at all (e.g. in Debian/Ubuntu, `libc6-dev` might not be installed). I wonder if one could adapt Glibc_jll and Musl_jll to provide headers as well and then use them to be able to compile binaries against the system C library in all cases...? Might be tricky given potential mismatch between the glibc/musl version in the JLL and on the system...

**Comment by staticfloat** [comment]
What you're asking for looks a lot like `BinaryBuilder.jl`.  :P

**Comment by fingolfin** [comment]
True enough, except that I'd be generating recipes at run time... and multi GB downloads for supporting binaries are something I don't want to incur on people who do have a working Compiler environment... ah well.

**Comment by ViralBShah** [comment]
Is this still a problem?
