### ISSUE TITLE
Incompatible library version about libgmp in Julia 1.5.2 in MacOS 10.15.7. 

### ISSUE THREAD

**Issue by cometscome** [JuliaPackaging/Yggdrasil#2027]
With using BinaryBuilder.jl, I made AlgRemez_jll which uses GMP. 
https://github.com/JuliaPackaging/Yggdrasil/blob/ec6570db077b3050a5c465a2819b3e98e836619b/A/AlgRemez/build_tarballs.jl
It works in Windows and Linux OS. But in MacOS it does not work in Julia 1.5. 

I got the following error on MacOS 10.15.7: 

```
julia> using AlgRemez_jll
julia> algremez() do exe
        run(`$exe 1 2 5 5 0.0004 64 40`)
       end
dyld: Library not loaded: @rpath/libgmp.10.dylib
  Referenced from: /Users/yuki/.julia/artifacts/a5290b6166b4f7d8de420178cd087663cb8238f3/bin/algremez
  Reason: Incompatible library version: algremez requires version 15.0.0 or later, but libgmp.10.dylib provides version 14.0.0
ERROR: failed process: Process(`/Users/yuki/.julia/artifacts/a5290b6166b4f7d8de420178cd087663cb8238f3/bin/algremez 1 2 5 5 0.0004 64 40`, ProcessSignaled(6)) [0]
```

If I run algremez, which was installed in .julia/artifacts/a5290b6166b4f7d8de420178cd087663cb8238f3/bin/algremez, it works on MacOS. 

I found several issues about GMP_jll. But I do not know how to resolve this error in AlgRemez_jll. 
Is there a way to resolve this problem by changing build_tarballs.jl?

**Comment by giordano** [comment]
Right, we need to rebuild using GMP v6.1 as dependency: that would be compatible with previous julia versions as well, see for example https://github.com/JuliaPackaging/Yggdrasil/blob/64803c80d0a11f901b40a605eba2bf809a8ef6db/P/polymake/build_tarballs.jl#L114  Mind opening a pull request?

**Comment by cometscome** [comment]
Thank you! I made a pull request.
