### ISSUE TITLE
[GDAL] broken on OSX

### ISSUE THREAD

**Issue by visr** [JuliaPackaging/Yggdrasil#2140]
Unfortunately GDAL is broken on OSX since #2138 (which unbroke another part of the build).
I found these issues in this GDAL.jl PR: https://github.com/JuliaGeo/GDAL.jl/pull/103#issuecomment-730626039

> Reason: Incompatible library version: libgdal.26.dylib requires version 35.0.0 or later, but libnghttp2.14.dylib provides version 34.0.0

Which happens here: https://travis-ci.com/github/JuliaGeo/GDAL.jl/jobs/443925712#L304

Could we get around this with, in https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/GDAL/build_tarballs.jl, set a newer version, like this one set in #2133 `Dependency("nghttp2_jll", v"1.40.0")`?

**Comment by giordano** [comment]
Yes, that should do the trick

**Comment by evetion** [comment]
Can confirm, current GDAL.jll is broken here. Latest Julia.

**Comment by visr** [comment]
With #2127 the `nghttp2` issue was fixed for OSX, but there seems to be another issue, so the build is still broken on OSX.

```
ERROR: LoadError: InitError: could not load library "/Users/travis/.julia/artifacts/748a9af711f154003ad1174bad6e277aee8d816e/lib/libgdal.26.dylib"
dlopen(/Users/travis/.julia/artifacts/748a9af711f154003ad1174bad6e277aee8d816e/lib/libgdal.26.dylib, 1): Library not loaded: @rpath/libmbedtls.13.dylib
  Referenced from: /Users/travis/.julia/artifacts/748a9af711f154003ad1174bad6e277aee8d816e/lib/libgdal.26.dylib
  Reason: image not found
```
from https://travis-ci.com/github/JuliaGeo/GDAL.jl/builds/203090604

Any ideas what I should do in https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/GDAL/build_tarballs.jl to fix this?

**Comment by giordano** [comment]
https://github.com/visr/Yggdrasil/blob/8f23bd062f9efd77cc87e2aa5e664006b72d32d1/N/NetCDF/build_tarballs.jl#L72-L74

**Comment by visr** [comment]
Ha should've guessed, thanks. Submitted #2149. I thought since this error was different something else may have been the matter.
