### ISSUE TITLE
LibCURL_jll with support for `file://` protocol

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaPackaging/Yggdrasil#2165]
See https://github.com/JuliaLang/Downloads.jl/issues/69.

**Comment by giordano** [comment]
Quoting from the log of https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/download/LibCURL-v7.73.0%2B3/LibCURL.v7.73.0.x86_64-linux-gnu.tar.gz
```
  Protocols:        DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS MQTT POP3 POP3S RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP
```

**Comment by giordano** [comment]
Also https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl/releases/tag/LibCURL-v7.66.0%2B0 has the `FILE` protocol, so by interpolation I assume all builds have this protocol enabled

**Comment by StefanKarpinski** [comment]
Yep, I was wrong about this. We already support it, there's an error in how Downloads handles it.
