### ISSUE TITLE
Bug in OpenSSL_jll

### ISSUE THREAD

**Issue by danielolsen** [JuliaPackaging/Yggdrasil#2210]
Not sure if this is the right place for this, but I'm encountering the following error:
`symbol lookup error: /home/dolsen/.julia/artifacts/e6e5f41352118bbeb44677765ebccab8c151c72a/lib/libssl.so: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0`. 

Looking for this hash, I find the following within the `Artifacts.toml` in `~/.julia/packages/OpenSSL_jll/l2Av2`:
```
[[OpenSSL]]
arch = "x86_64"
git-tree-sha1 = "e6e5f41352118bbeb44677765ebccab8c151c72a"
libc = "glibc"
os = "linux"

    [[OpenSSL.download]]
    sha256 = "77be5b30230b67396a691ba8be144824b515e8ea5070df7bd5b06026fdc5ca56"
    url = "https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/download/OpenSSL-v1.1.1+2/OpenSSL.v1.1.1.x86_64-linux-gnu.tar.gz"
```

**Comment by giordano** [comment]
How did you trigger that error?  The symbol is defined in `libcrypto.so`:
```
% nm OpenSSL.v1.1.1.x86_64-linux-gnu/lib/libcrypto.so | grep EVP_idea_cbc
000000000016fde0 T EVP_idea_cbc
```
Do you have by any chance loaded a different `libcrypto`?  What does
```julia
using Libdl
filter(l -> occursin("crypto"), dllist())
```
return in the same session?

**Comment by danielolsen** [comment]
I was running from python via pyjulia/PyCall, that was all the context I got. I will try to reproduce in Julia directly.

**Comment by giordano** [comment]
> I was running from python via pyjulia/PyCall, that was all the context I got.

It's very likely that a different libcrypto was loaded by Python.  Nothing we can really do about

**Comment by lazzarello** [comment]
I'm having this same bug. it seems to be caused by a binary in this repo.
