### ISSUE TITLE
Odd `Zlib_jll not installed` error (FreeType2?)

### ISSUE THREAD

**Issue by timholy** [JuliaPackaging/Yggdrasil#2224]
In [this CI run](https://github.com/timholy/MzPlots.jl/pull/6/checks?check_run_id=1498775196), compilation of FreeType2 seems to have failed due to a missing Zlib_jll dependency. But these things strike me as odd:
- it seems to be using `FreeType2_jll v2.10.1+5`, yet https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl suggests the latest version is 2.10.1+4
- Zlib_jll seems to be listed as a dependency in FreeType2's build script, https://github.com/JuliaPackaging/Yggdrasil/blob/master/F/FreeType2/build_tarballs.jl

**Comment by timholy** [comment]
I turned off `fail-fast` in CI, and now I can add the fact that this only happens on nightly (e.g., https://github.com/timholy/MzPlots.jl/pull/7/checks?check_run_id=1498905042 does install Zlib_jll).

**Comment by giordano** [comment]
I'm not 100% sure but I think that's the same issue as https://github.com/JuliaLang/julia/issues/38654

**Comment by fingolfin** [comment]
@timholy does it work agai now?

**Comment by timholy** [comment]
That PR merged, but thankfully GitHub lets me re-run CI even on a merged PR. Seems good now: https://github.com/timholy/MzPlots.jl/runs/1511479750
