### ISSUE TITLE
Some packages missing armv6 tarballs?

### ISSUE THREAD

**Issue by notinaboat** [JuliaPackaging/Yggdrasil#2232]
MbedTLS has a tarball for armv6: https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases
Ncurses does not: https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases

What needs to happen to trigger an armv6 build for these packages?

Related: #1707, https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/576

**Comment by giordano** [comment]
Only Julia v1.6 can handle JLL packages for armv6l.  For the time being we're building only dependencies for Julia itself for this platform.  After Julia v1.6 will be out, we'll probably start building packages for armv6l more regularly.

**Comment by notinaboat** [comment]
Thanks @giordano.

FYI i'm using armv6 JLL packages with Julia 1.5 on Raspberry Pi Zero by doing something like: `pkg> add CompilerSupportLibraries_jll#f50f017d1b787771dc2f73a309b0b00202a6acfd` to pull the latest version into my environment. This seems to work fine and is far more convenient than copying system libraries into the artefacts directory by hand.

**Comment by giordano** [comment]
I lied a bit because also Julia v1.5.2+ can handle JLLs for armv6l, but it's awkward to explicitly mention compatibility with a patch release, so for consistency we declare them compatible only with v1.6

**Comment by giordano** [comment]
Closing in favour of #2763
