### ISSUE TITLE
Git_jll is missing Win64 wrapper

### ISSUE THREAD

**Issue by crstnbr** [JuliaPackaging/Yggdrasil#233]
Has been noticed in a slack discussion with @giordano.

[Git_jll](https://github.com/JuliaBinaryWrappers/Git_jll.jl/tree/master/src/wrappers) has 12 wrappers. The one for 64bit Windows, `x86_64-w64-ming32`, is missing.

The [`build_tarballs.jl`](https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/Git/build_tarballs.jl) shows w64. Maybe there went something wrong in the build process?

**Comment by crstnbr** [comment]
Where do I find the build logs? Can we maybe just retrigger and see what happens?

**Comment by giordano** [comment]
There is a build log inside each tarball. But this doesn't show what happened for the creation of the wrappers

**Comment by crstnbr** [comment]
Hm, is there a log for the wrapper creation? Like an azure process log (I couldn't find one). Otherwise, how could I debug this?

**Comment by giordano** [comment]
> Like an azure process log (I couldn't find one)

This was created before we started using Azure Pipelines

> Otherwise, how could I debug this?

No idea to be honest, maybe we should just try to rebuild the JLL package and see what happens

**Comment by crstnbr** [comment]
> maybe we should just try to rebuild the JLL package and see what happens

How do I trigger this? (or can/should you do it?)

**Comment by giordano** [comment]
The wrapper is now there: https://github.com/JuliaBinaryWrappers/Git_jll.jl/tree/Git-v2.23.0+1/src/wrappers.  Pull request for the General registry: https://github.com/JuliaRegistries/General/pull/6222.  I'm going to close this ticket
