### ISSUE TITLE
GEOS library size is bloated

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPackaging/Yggdrasil#234]
Looks like dynamic libraries of GEOS are huge in size.

In .julia\artifacts\899bb0e10d4accc34dff74b1c82ffbfe56dc8b23\bin, libgeos-3-8-0.dll and libgeos_c-1.dll are 57339 KB and 3239 KB respectively, whereas in .julia\conda\3\pkgs\geos-3.8.0-h33f27b4_0\Library\bin, geos.dll and geos_c.dll are 1346 KB and 346 KB respectively.

The files at  https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/tag/GEOS-v3.8.0%2B1 contain a file `logs/GEOS.log` that suggest that `-O2` was already passed to the compiler, so PR https://github.com/JuliaPackaging/Yggdrasil/pull/232 was a clueless attempt to improve.

**Comment by giordano** [comment]
The sizes of the tarballs are now one twentieth as before. I guess we can close this ticket?
