### ISSUE TITLE
[AZP] Evaluate possibility of using Azure Artifacts

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#238]
We could look into using [Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/overview?view=azure-devops) to provide the tarballs of a pull requests build for inspection.

I'm not sure how it would work, especially with multiple projects built in the same pull request.

Also, there is a limit of 2 GiB of storage for the free plan, so we probably would need to have a very short retention period (like one day) and maybe limit to the latest build of a PR (if that's possible at all).  Even so, it's not that hard for us to hit the storage limit in one day.

**Comment by NHDaly** [comment]
https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven#automatically-delete-old-package-versions-with-retention-policies


The good news is it doesn't _charge youP_ if you hit the limit -- just stops working :heavy_check_mark:

> The usage limit allows you to control the maximum volume of storage that you're billed for. Once the maximum usage limit is reached, you can no longer upload artifacts.

However:

> A: Deletion of artifacts doesn't register immediately. It can take up to 24 hours for the usage level to be updated. If you're blocked from uploading artifacts, you can temporarily increase your usage level to continue publishing artifacts. Then, reduce the level once the storage metrics are updated.

So it might not work well if we upload things often. But if we have fewer than maybe 5-10 prs per day this might still be useful?

Probably worth a shot to set this up and see how it goes! :)

**Comment by giordano** [comment]
Superseded by using S3 cache in #535.
