### ISSUE TITLE
GR_jll fails on Windows

### ISSUE THREAD

**Issue by juliohm** [JuliaPackaging/Yggdrasil#2397]
Students on Windows are having this build error in the GR dependency of a project. There are no error messages in the package manager output, but it points to a build.log file:

![image](https://user-images.githubusercontent.com/3345261/104753249-7b18b780-5736-11eb-860f-98c459f9c60c.png)

This is a build with Julia v1.6.0-beta1.

**Comment by giordano** [comment]
The warning message doesn't come from installing `GR_jll`, but GR's own precompiled binaries: https://github.com/jheinen/GR.jl/blob/209dddb0c77aabcf9ac807e9c46144214733f98d/deps/build.jl#L137, so I'm going to close this ticket
