### ISSUE TITLE
Feature request: hyperlink from General PR to Yggradasil PR or commit?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPackaging/Yggdrasil#2433]
If a JLL registration is failing AutoMerge, it would be helpful for me to be able to quickly locate the PR in Yggradasil that triggered the JLL registration.

When `@jlbuild` creates or updates a registration PR to General, could it include in the PR body a link to the corresponding Yggradasil PR or commit?

**Comment by giordano** [comment]
There is already a link in the README of the JLL

**Comment by DilumAluthge** [comment]
Hmm. Could you walk me through it?

E.g. suppose I'm looking at this General PR:
- https://github.com/JuliaRegistries/General/pull/28467

As far as I can tell, this General PR was created and updated by these two Yggradasil PRs:
- https://github.com/JuliaPackaging/Yggdrasil/pull/2427
- https://github.com/JuliaPackaging/Yggdrasil/pull/2432

More specifically, 2427 triggered the creation of the General PR, and then 2432 updated and force-pushed the General PR.

If I look at the body of https://github.com/JuliaRegistries/General/pull/28467, it has a link to https://github.com/JuliaBinaryWrappers/GAP_jll.jl. So I click that link and it brings me to the GAP_jll.jl README. But now, it's not immediately obvious to me how I get from the Gap_jll.jl README to the Yggradasil PRs 2427 and 2432.

**Comment by giordano** [comment]
> [...] The originating [`build_tarballs.jl`](https://github.com/JuliaPackaging/Yggdrasil/blob/c44e2be38447a3b7f76b7cfe42603356e39322ff/G/GAP/build_tarballs.jl) script can be found [...]

points you to https://github.com/JuliaPackaging/Yggdrasil/blob/c44e2be38447a3b7f76b7cfe42603356e39322ff/G/GAP/build_tarballs.jl, which points you to https://github.com/JuliaPackaging/Yggdrasil/pull/2432.

Anyway, I don't know what we can do here, it looks like more a feature request for Registrator?

**Comment by DilumAluthge** [comment]
> > [...] The originating [`build_tarballs.jl`](https://github.com/JuliaPackaging/Yggdrasil/blob/c44e2be38447a3b7f76b7cfe42603356e39322ff/G/GAP/build_tarballs.jl) script can be found [...]
> 
> points you to https://github.com/JuliaPackaging/Yggdrasil/blob/c44e2be38447a3b7f76b7cfe42603356e39322ff/G/GAP/build_tarballs.jl, which points you to #2432.

Ah, that works.

**Comment by DilumAluthge** [comment]
> Anyway, I don't know what we can do here, it looks like more a feature request for Registrator?

I don't think `@jlbuild` actually uses Registrator to create/update PRs, does it? Looks like you do it yourself: https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/fe019a6f4e1c5a218be0be7dce8df6601d2e3810/src/wizard/github.jl#L118
