### ISSUE TITLE
SuiteSparse GraphBLAS should target a different repo with different version numbering

### ISSUE THREAD

**Issue by Wimmerer** [JuliaPackaging/Yggdrasil#2478]
I discussed this in the BinaryBuilder Slack, but thought I should open an issue before attempting to retarget the repo. Currently it targets [github.com/DrTimothyAldenDavis/SuiteSparse/](url). This is mostly fine but leaves us behind the upstream repo [https://github.com/DrTimothyAldenDavis/GraphBLAS](url). 

It should be relatively easy to update, and I'll make a PR shortly, but the version number will end up out of sync with the actual binary. GraphBLAS itself is on ~v4.0, while SuiteSparse is ~v5.x. After the Slack conversation we settled on updating the artifact to v6.0. Does that seem sensible? We won't match the versioning of the base repository but we'll avoid conflicts and ensure the latest version isn't below the previous.

**Comment by giordano** [comment]
CC: @ViralBShah

**Comment by ViralBShah** [comment]
Thanks I did not realize that it had its own upstream repo. In that case we should separate it out from `S/SuiteSparse`. @Wimmerer Can you do that and switch it to tracking the upstream repo?

I wouldn't worry about the version number. I doubt anybody has used it much. Let's use the upstream version number. If we receive too many complaints we can adopt 6.x I suppose.

**Comment by Wimmerer** [comment]
@ViralBShah I will put in a PR yeah. I'll put it in G/GraphBLAS, that may eventually be an issue - it's the reference but not sole implementation of the GraphBLAS standard - but it should be fine for the foreseeable future. The other implementations I'm aware of use different names.

**Comment by ViralBShah** [comment]
Yeah it occurred to me too. We can always do SSGraphBLAS if we want to leave the generic name open. My thought was that if that's the name Tim has chosen and others are picking different names, we should stick with the upstream name. If Tim changes it in the future, we can always adopt the change.

I'll ping @timothyaldendavis here, just in case he has thoughts.

**Comment by DrTimothyAldenDavis** [comment]
SuiteSparse is 5.8 but that doesn't mean is newer than SuiteSparse:GraphBLAS, which is current v4.0.x.  SuiteSparse is a meta-package, a package of packages, with its own version numbering (5.8 currently).  That version number has nothing to do with the internal versions of each package it contains, although when I update the packages inside SuiteSparse, I bump the SuiteSparse v5.8 to 5.9, etc.  The latest stable SuiteSparse:GraphBLAS is always in https://github.com/DrTimothyAldenDavis/GraphBLAS and then later on I update the version of GraphBLAS at https://github.com/DrTimothyAldenDavis/SuiteSparse .

Regarding the name:  yes, "GraphBLAS" is generic, and can apply to other implementations of the GraphBLAS C API Specification.  Calling my implementation just "GraphBLAS" is like calling the Intel MKL "the BLAS", or calling OpenBLAS as "the BLAS".  I would leave the generic name open.

I call my package SuiteSparse:GraphBLAS, or SS:GrB for short.

**Comment by Wimmerer** [comment]
Is SSGraphBLAS an acceptable name for everyone?

**Comment by ViralBShah** [comment]
Yes, let's go with that.

**Comment by DrTimothyAldenDavis** [comment]
That works great for me.

**Comment by Wimmerer** [comment]
@giordano 

I can't recall which you preferred. We've got these options:

- Create a new jll named SSGraphBLAS whether in G/GraphBLAS or S/SuiteSparse
- Change the version number of SuiteSparseGraphBLAS_jll to v4.0.3 and enforce version number in wrappers. Eventually we would have a v5.x.x+1 as I understand it. 
- Change the version number of the jll to 6 and disconnect it from the underlying GraphBLAS version number

**Comment by ViralBShah** [comment]
If we go with option 1, I would recommend putting it in S/SuiteSparse.

**Comment by DrTimothyAldenDavis** [comment]
I've updated SuiteSparse to v5.9.0, and it now includes the latest stable
GraphBLAS, v4.0.3.
See https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v5.9.0 .

So now they are in sync.  Both of these:
https://github.com/DrTimothyAldenDavis/SuiteSparse
https://github.com/DrTimothyAldenDavis/GraphBLAS
now have the same GraphBLAS v4.0.3, in their stable releases.

**Comment by giordano** [comment]
I agree with Viral that option 1 may be the cleanest one
