### ISSUE TITLE
Windows builds pass with build.jl, fail with JLL

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/Yggdrasil#253]
We recently registered [ASL_JLL.jl](https://github.com/JuliaBinaryWrappers/ASL_jll.jl). I used the `generage_buildjl.jl` script to generate this [`build.jl`](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/blob/master/deps/build.jl). All builds pass on Linux, macOS, Windows and FreeBSD:

* https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/builds/618635333
* https://ci.appveyor.com/project/dpo/amplnlreader-jl/branch/master
* https://cirrus-ci.com/github/JuliaSmoothOptimizers/AmplNLReader.jl

Now I'm trying to get rid of `build.jl` and depend on `ASL_jll` instead. In the process I test a variety of architectures on TravisCI, but some builds that used to pass no longer do:

* https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/builds/619403421
* https://ci.appveyor.com/project/dpo/amplnlreader-jl/builds/29240265

In particular:

* the [Appveyor/MinGW builds](https://ci.appveyor.com/project/dpo/amplnlreader-jl/builds/29240265/job/s1ksjty3ma5l9i75#L133) fail with the message
  ```
  ERROR: LoadError: LoadError: error compiling AmplModel: error compiling AmplModel#1: could not load library 
  "C:\Users\appveyor\.julia\artifacts\143fa69fa594c92770a91f9712d78d6c92bb7b47\bin\libasl-0.dll"
  The specified module could not be found.
  ```
* the [TravisCI/Linux/PPC build](https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/619403424#L51) fails with
  ```
  /home/travis/.travis/functions: line 109: /home/travis/julia/bin/julia: cannot execute binary file: Exec format error
  ```
  This error is probably not related to BinaryBuilder.jl / Yggdrasil.jl but I thought I'd report it.
* the [TravisCI/Windows/x64 build](https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/619403429#L123) fails with
  ```
  ERROR: LoadError: LoadError: error compiling AmplModel: error compiling AmplModel#1: could not load library 
  "C:\Users\travis\.julia\artifacts\143fa69fa594c92770a91f9712d78d6c92bb7b47\bin\libasl-0.dll"
  ```

Why are the Windows builds failing? Here is the [pull request](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/pull/87) with my changes.

I'll try and debug the Appveyor builds by ssh-ing into the VM but I thought you might have some ideas. Thanks in advance!

**Comment by giordano** [comment]
The shared library on Windows can't probably be dlopen'ed. This could mean that it's missing some dependencies.

If I remember correctly, the exec format error means that the library is for another platform. I didn't know that Travis has support for powerpc

**Comment by dpo** [comment]
> The shared library on Windows can't probably be dlopen'ed.

What I'm saying is that it was dlopen'ed when I used the build.jl script. Are you saying a different artifact is selected when I use ASL_jll.jl?

**Comment by giordano** [comment]
No, the files are the same

**Comment by dpo** [comment]
I know nothing about dlls, but here's what happened. Apparently, the correct binary was downloaded and installed to `C:\Users\appveyor\.julia\artifacts\some_long_sha\bin\libasl.dll`. (I make that claim based on the size of the dll.) That dll cannot be `dlopen`ed. If I manually download the same binary and extract it to `C:\Users\appveyor\Downloads`, I can `dlopen` the dll. If I copy this last dll to the `artifacts` location, I cannot `dlopen` it.

Does that make any sense?

What I don't understand if that all is well with the `build.jl`.

**Comment by giordano** [comment]
It's not completely clear to me what you tried, could you please elaborate more?  Did you try to `dlopen` the same DLL file in two fresh Julia sessions first while sitting in `C:\Users\appveyor\.julia\artifacts\some_long_sha\bin\libasl.dll` and then in `C:\Users\appveyor\Downloads`?  I don't think that only the position of the library should matter, maybe there was something else that you did?

**Comment by dpo** [comment]
I debugged the issue. The problem was coming from the fact that I copied the example https://github.com/JuliaMath/GSL.jl/pull/104, including the library name [here](https://github.com/JuliaMath/GSL.jl/pull/104/files#diff-b39ece7eab40a31fda78d0776814bc0fR14), which I thought was the name given by Yggdrasil, but turned out to be erroneous in my case.

We have all green lights now: https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/pull/87. Thanks.
