### ISSUE TITLE
Build LAPACK

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#2657]
Now that we have LBT, we have situations where some libraries provide both BLAS and LAPACK (OpenBLAS, MKL) and we can have situations where we only have a BLAS provider (Accelerate, BLIS, AmdBLIS). For situations, where we only have a BLAS provider, we should build the reference LAPACK and provide it through Yggdrasil.

cc @staticfloat

**Comment by ViralBShah** [comment]
Also worth looking at: https://github.com/HPAC/ReLAPACK

**Comment by DilumAluthge** [comment]
@ViralBShah can this be closed now that https://github.com/JuliaPackaging/Yggdrasil/pull/2658 is merged?

**Comment by ViralBShah** [comment]
We need to update the LAPACK build to have `64_` suffixes for ILP64 platforms. Leaving this open for now.

**Comment by ViralBShah** [comment]
@giordano What would be the easiest way to add `64_` suffixes for ILP64 platforms in LAPACK_jll? We need to ship it separately in cases where we have a vendor BLAS but not a good vendor LAPACK - like Accelerate.

It would be nice to have M1 switch over to Accelerate.

**Comment by giordano** [comment]
I guess remapping the symbols with macros?

**Comment by ViralBShah** [comment]
Anything in the LBT infrastructure I can reuse for that?

**Comment by giordano** [comment]
Strictly speaking, the fortran standard doesn't require preprocessor directives like `#define`, although some compilers do allow them (I know gfortran does that, I presume most common would do the same). I'm away from computer right now, I can't check whether `#include` directives would work. You can always use fortran's own `include` statement.

**Comment by ViralBShah** [comment]
I was trying to think about ways of doing this without having to edit the fortran files.

**Comment by giordano** [comment]
Then redefining the symbols on the command line with `-D` is your best bet. We haven't it yet, but we should provide a utility to generate the list of `-D` arguments to remap all BLAS symbols, we already do this in many places and it's cumbersome to do it manually
