### ISSUE TITLE
Upgrade sundials to use jll. 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#268]
What do we need to do to upgrade the sundials install to use the new infrastructure? Also, I notice that it downloads suitesparse to build KLU. I would prefer that we build KLU as part of the regular suitesparse in Julia, and have sundials use that. 

Not a huge problem, but sundials ships its own libsuitesparseconfig and is using a different version of suitesparse than upstream. Could lead to subtle issues.

cc @chrisrackauckas

**Comment by ViralBShah** [comment]
This came up in https://github.com/JuliaDiffEq/Sundials.jl/issues/223

**Comment by ViralBShah** [comment]
Looks like SuiteSparse does build KLU.

https://github.com/JuliaPackaging/Yggdrasil/blob/ae8de3aed3d9b68514c42f1594e3e871fb3d4e96/S/SuiteSparse/build_tarballs.jl#L82

**Comment by ChrisRackauckas** [comment]
Looping in @jd-lara who was doing some Sundials v5.0 stuff. How far along was that? Are there any pieces we should be aware of to get this going, like any updates to the build script or the API wrapper?

**Comment by jd-lara** [comment]
@ChrisRackauckas We have a working version of the BinaryBuilder here https://github.com/Energy-MAC/SundialsBuilder there is a hiccup with the integration of LAPACK through OpenBlas in 64 bits that the LLNL sundials team is tackling in a minor release. 

Also, the new clang wrapper is here https://github.com/Energy-MAC/Sundials.jl/blob/jd/Sundialsv5/src/wrap_sundials.jl and works well. 

I have not made new updates waiting for 1. the Sundials LAPACK fix for 64 bits and 2. reimplement the BinaryBuilder pipeline using the new Pkg traits.

**Comment by giordano** [comment]
For the record, the existing builder works for all platforms but FreeBSD, where there are unsatisfied dependencies, see pull request #269
