### ISSUE TITLE
Builder Request: a `Curl_jll.jl` package that includes the `curl` binary executable

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPackaging/Yggdrasil#2720]
From https://github.com/JuliaLang/julia/issues/40041#issuecomment-799577812:
> Perhaps we should create a separate CURL_jll that provides the executable, for users that want to be able to use it.

Since the Lib_CURL_jll stdlib in Julia 1.6 won't have the `curl` executable, it would be great to have a `CURL_jll` package for users that need the `curl` executable.

cc: @staticfloat @giordano

**Comment by ericphanson** [comment]
+1 for this; shelling out to curl is pretty simple and easy for a lot of stuff (esp when there's examples with it for whatever api you want to hit up), so it would be nice if there was a portable way to do it

**Comment by ericphanson** [comment]
Would the way to do this be to just copy https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibCURL into `C/CURL`? Since https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibCURL/build_tarballs.jl does build the executable product, but I guess since it's a stdlib we don't get that version?

**Comment by DilumAluthge** [comment]
@staticfloat or @giordano  can probably weigh in on the best way to implement this.

**Comment by DilumAluthge** [comment]
My understanding is that we needed to build a whole new JLL.

**Comment by giordano** [comment]
Since we're probably not going to touch `LibCURL_jll`, doing a separate package is the best course of action
