### ISSUE TITLE
FFTW_jll for Mac M1 (ARM)

### ISSUE THREAD

**Issue by storopoli** [JuliaPackaging/Yggdrasil#2738]
It would be really good to have `FFTW_jll` build for Mac M1. It will probably make `StatsPlots.jl` and other packages available for Mac Silicon.

**Comment by giordano** [comment]
https://github.com/JuliaMath/FFTW.jl/issues/187#issuecomment-801517648

But please, do not keep opening new issues about this. It's a complex general problem that we are completely aware of. Consider using Julia on the new architecture experimental and that most packages won't work for a while

**Comment by storopoli** [comment]
Thank you @giordano. Sorry about the inconvenience.

**Comment by giordano** [comment]
Closing in favour the meta issue #2763.
