### ISSUE TITLE
[Qt] Qt5 split packages

### ISSUE THREAD

**Issue by barche** [JuliaPackaging/Yggdrasil#2808]
I have been trying to convert QML.jl to the new Qt5 packages (`Qt5Base_jll` and dependents) but I hit a problem for which I don't see a solution: Qt assumes all the related packages for a distribution are installed under the same prefix. For shared-library only packages such as `Qt5Svg` that doesn't matter, but when using the QML packages everything must be in the same `qml` directory, and there are also some dynamically loaded plugins.

Is there any way to automatically set up symlinks or something to emulate having a common prefix?

**Comment by giordano** [comment]
This is unfortunate :confused: 

> Is there any way to automatically set up symlinks or something to emulate having a common prefix?

No, not really, that'd also go against the principle of keeping the artifacts immutable.

**Comment by barche** [comment]
I think this was a false alarm, I managed to run a basic example by setting the `QML2_IMPORT_PATH` environment variable, which does take a list of paths, fortunately. I panicked because I saw a "no platforms found" error on Windows, but that seems because there was a corrupt dll in my artifacts directory, unpacking the artifact release manually and overwriting the dll solved that.

**Comment by barche** [comment]
Just confirmed that setting `QML2_IMPORT_PATH` completely solves this also on Windows, and a clean start from an empty `.julia` didn't reproduce the corrupted dll, so all good. Sorry for the noise.
