### ISSUE TITLE
using SymEngine_jll makes Julia crash on 64-bit Windows

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#281]
Following up from #279, I can confirm that just doing
```julia
using SymEngine_jll
```
makes Julia crash on 64-bit Windows.  See for example these [AppVeyor](https://ci.appveyor.com/project/giordano/dependencywalker-jl/builds/29502464) and [Travis](https://travis-ci.com/giordano/DependencyWalker.jl/jobs/266622768) jobs.  The content of the test script is
```julia
@info "Before loading SymEngine_jll..."
using SymEngine_jll
@info "After loading SymEngine_jll..."
```

@isuruf [reported](https://github.com/JuliaPackaging/Yggdrasil/pull/279#discussion_r356936877) that with old BinaryBuilder he used `expand_gcc_version` to make this work, but we don't have that function anymore and he's using the pure C interface.  Any clue of what could be the problem and possible solutions?  Maybe we're hitting a compiler bug and building with a later version of GCC, without expanding, could help?

**Comment by giordano** [comment]
On [AppVeyor](https://ci.appveyor.com/project/giordano/dependencywalker-jl/builds/29502912) `BinaryProvider.platform_key_abi()` returns
```julia
Windows(:x86_64, compiler_abi=CompilerABI(:gcc7, :cxx11))
```
Let's try building with GCC7?

**Comment by isuruf** [comment]
If we build with GCC7, the binary would not work with a GCC4 build of julia as `libstdc++.dll` will be missing symbols.

**Comment by giordano** [comment]
So this is a C++ library (linked to libstdc++.so) but you use the C API? Why it would fail only on Windows x86_64?

**Comment by isuruf** [comment]
> So this is a C++ library (linked to libstdc++.so) but you use the C API?

Yes, it's a C++ library, but it has a C API which is what we use in the Julia wrapper.

> Why it would fail only on Windows x86_64?

I have no idea. From what I know, if we build with the oldest GCC supported (4.8) and use the library in julia compiled with GCC 4.8 or above and only use the C API, it should work.

**Comment by giordano** [comment]
@isuruf did you try the latest version?

**Comment by isuruf** [comment]
Yes, it works. Thanks
