### ISSUE TITLE
Qt6 packages

### ISSUE THREAD

**Issue by barche** [JuliaPackaging/Yggdrasil#2845]
So, I had been hoping that the split Qt5 packages would be a good basis for the Qt6 packages, but it turns out they changed everything 🙃

It's a change for the better ( see https://www.qt.io/blog/qt-6-build-system ), but it requires building Qt6Base for the host system, meaning linux-musl for us. Is there a way to specify the musl version of Qt6Base as a build dep for Qt6Base on the other platforms, with the musl version preferably installed in a different prefix?

**Comment by giordano** [comment]
https://docs.binarybuilder.org/dev/reference/#BinaryBuilderBase.HostBuildDependency

**Comment by barche** [comment]
Thanks :)
