### ISSUE TITLE
Organize into folders by first letter? like JuliaRegistries/General

### ISSUE THREAD

**Issue by ianshmean** [JuliaPackaging/Yggdrasil#29]
Just a thought.. It might make things more manageable.. easier to make that change at an earlier stage..

**Comment by ararslan** [comment]
I thought about this the other day as well. If Yggdrasil eventually becomes the One True Builder Repo, we'll have the same problem that METADATA had.

**Comment by ianshmean** [comment]
I guess one complication is which folder to put the many builders that start with `lib*`. Should `libCURL` go in `L` or `C`?! I'd probably vote for `C` but with a note in the readme

The Julia community... never scared to take on the tricky questions

**Comment by ararslan** [comment]
I'd say L since it builds libcurl, not curl.

**Comment by ianshmean** [comment]
True.. `libCURL != CURL`

**Comment by vtjnash** [comment]
True, but then almost all of these make `libsomething`. For instance, we can look through https://github.com/JuliaPackaging/Yggdrasil/tree/master/X and e.g. the output we get from XZ is liblzma.
