### ISSUE TITLE
Libiconv artifacts not available on storage servers

### ISSUE THREAD

**Issue by staples6** [JuliaPackaging/Yggdrasil#3077]
Artifacts for [Libiconv v1.16.1+0 ](https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/blob/3e5cdbf90dd186edd3838cb3e297fc079177c36b/Artifacts.toml) do not appear to be available on the storage servers.

For example, https://us-east.storage.juliahub.com/artifact/644f24d4876309d0b771bdad3cbd7ca58f8f24d4

**Comment by giordano** [comment]
CC: @staticfloat

**Comment by staticfloat** [comment]
Fixed now, sorry for the delay.
