### ISSUE TITLE
GEOS expanded cxx string ABIs are identical

### ISSUE THREAD

**Issue by visr** [JuliaPackaging/Yggdrasil#316]
*This already came up in https://github.com/JuliaPackaging/Yggdrasil/pull/293#issuecomment-566836254, but making a separate issue to keep GEOS issues out of the GDAL PR discussion.*

In #302 we expanded the cxx string ABIs for GEOS. However the files for both builds are identical apart from the log. Both are built with cxx11 string ABI.

Does anyone have an idea why `expand_cxxstring_abis` is not working here, and how we can make it work?

https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/tag/GEOS-v3.8.0%2B2
https://github.com/libgeos/geos

**Comment by giordano** [comment]
What I find interesting is that building locally twice for the same platform and the same string ABI I get non-identical files. I think it's very surprising that there are identical libraries in two different builds (moreover targeting different string ABIs)

**Comment by visr** [comment]
I just tried running these two on BinaryBuilder master:
```
julia --color=yes build_tarballs.jl --verbose --debug x86_64-linux-gnu-cxx03,x86_64-linux-gnu-cxx11
```

And still got tarballs that are identical apart from the log.

From doing a
```
nm -gCD libgeos.so | grep basic_string
```
on the `cxx03` build and getting only `std::__cxx11::basic_string` back, I gather that the `expand_cxxstring_abis` hasn't worked.

Is there anything else I can do to make it use the cxx03 string ABI?

**Comment by visr** [comment]
@staticfloat do you maybe have any insights here? Would love to get unstuck for the GEOS -> GDAL builds.

**Comment by staticfloat** [comment]
> However the files for both builds are identical apart from the log. Both are built with cxx11 string ABI.

That's not good!  That means there's probably a BB bug.  Can you point me to the resultant files?
