### ISSUE TITLE
Increase openblas threads defaults

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#33]
As discussed in https://github.com/JuliaLang/julia/issues/14857, the default number of threads on linux is probably too low as core counts have significantly gone up. My suggestion is to make the default NUM_THREADS at compile time to be 64 on Linux (until a better fix is found), and leave it at 16 on Windows, Mac and ARM.

Relevant line here:
https://github.com/JuliaPackaging/Yggdrasil/blob/7fcd72af9cb1a01ded151aa7a59ffee0f760dde4/O/OpenBLAS/build_tarballs.jl#L42

**Comment by vchuravy** [comment]
x-ref: https://github.com/JuliaLang/julia/pull/18638

**Comment by ViralBShah** [comment]
Also: https://github.com/xianyi/OpenBLAS/issues/2225#issuecomment-522302707
