### ISSUE TITLE
OpenLSTO

### ISSUE THREAD

**Issue by mohamed82008** [JuliaPackaging/Yggdrasil#3376]
Would be great to have a JLL package for https://github.com/M2DOLab/OpenLSTO. I tried many things but couldn't get BB to work on an M1, Linux Arm VM on the M1, JuliaHub and AWS. I am yet to try a basic Linux machine but unfortunately I don't have to access to one at the moment, so here I am...

**Comment by Wimmerer** [comment]
I'll give it a shot in the next few days. Is it urgent? I'd say I can definitely do it by Thursday.

**Comment by mohamed82008** [comment]
Not urgent. Please procrastinate at your convenience.

**Comment by Wimmerer** [comment]
You just need these command line interfaces right? I don't see a makefile for a shared lib/anything else.

**Comment by mohamed82008** [comment]
bump :)
