### ISSUE TITLE
Build MPI-dependent packages with MPItrampoline

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#3564]
I want to test building MPI-dependent packages with MPItrampoline as the MPI implementation. Currently, most MPI packages use MPICH (or OpenMPI). What would be the best way to do so?

I am currently using a "local deployment", and I am using `$HOME/.julia/dev` to host the generated jll packages. Is there a better way that would also allow others to test such package more easily? Is there e.g. a way to "tag" packages, so that there would be an "official" package called `ADIOS2#MPItrampoline` or similar?

**Comment by ViralBShah** [comment]
We probably need @staticfloat or @giordano to chime in on this.

**Comment by staticfloat** [comment]
The easiest way is for you to build locally, but provide `--deploy=eschnett/Foo_jll` as an argument to `build_tarballs.jl`.  Then, create an environment with those packages added by URL, e.g. `pkg> add https://github.com/eschnett/Foo_jll.git`, which should install that particular version of the package.

**Comment by eschnett** [comment]
I tried that; I cannot make it work. See https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1101. Something is off with authenticating to Github.

**Comment by ViralBShah** [comment]
Is it ok to close this one now?
