### ISSUE TITLE
libexpat?

### ISSUE THREAD

**Issue by vtjnash** [JuliaPackaging/Yggdrasil#36]
This is may be all that stands between the Julia Makefile and total BB dominance, at https://github.com/JuliaLang/julia/blob/828a2ecf3a8da5ac9ed85ef7646af46226105765/Makefile#L594-L612

(cause of CI failure https://build.julialang.org/#/builders/64/builds/5042)

**Comment by giordano** [comment]
https://github.com/JuliaGraphics/ExpatBuilder

**Comment by giordano** [comment]
PR in #44.

**Comment by staticfloat** [comment]
Ironically, I'm also working on a `7z` builder (for Pkg redistribution) so we hopefully will be able to wean ourselves there as well.
