### ISSUE TITLE
[yaml_cpp] revert back to building with standard platform toolchains

### ISSUE THREAD

**Issue by Crghilardi** [JuliaPackaging/Yggdrasil#3668]
@pepijndevos opening an issue here for discussion

I would like to add [GNU gama](https://www.gnu.org/software/gama/) which uses `yaml_cpp` as a dependency.
Currently, `yaml_cpp` is pinned to build with `gcc` across all platforms (see https://github.com/JuliaPackaging/Yggdrasil/pull/3524). It seems to build fine on using standard toolchains, but was patched to address issues with another library (`Scopehal`, see https://github.com/JuliaPackaging/Yggdrasil/pull/3522)

This causes issues with building `gama` on `x86_64-unknown-freebsd` at least, I have not worked through all platforms yet.

I would like to change the`build_tarballs.jl` back to building with standard toolchains. I did test to make sure everything works on all platforms.

```
#this builds for me locally with no problems.
cmake -DCMAKE_INSTALL_PREFIX=${prefix} \
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} \
    -DCMAKE_BUILD_TYPE=Release \
    -DYAML_BUILD_SHARED_LIBS=ON \
    -DYAML_CPP_BUILD_TESTS=OFF \
    ..

```
A search of `Yggdrasil` doesn't show any other projects other than `scopehal` using `yaml_cpp` as a dependency currently.

**Comment by pepijndevos** [comment]
I think in a later pr we reverted to building with llvm and skipped macos until there is a parallel thingy for llvm. Sorry I'm a bit vague I'm on my phone on holiday. Long story short I think it's OK to revert yaml to clang, but if you could verify it doesn't break scopehal that'd be great.
