### ISSUE TITLE
NetCDF 4.8.1 does not work on windows

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaPackaging/Yggdrasil#3731]
Unfortunately, there is an issue with my PR https://github.com/JuliaPackaging/Yggdrasil/pull/3620. 
The windows binary does not seem to work. The size of the library is also suspiciously small. Symbols like nc_inq_libvers are no longer found.

**Comment by Alexander-Barth** [comment]
You are right. I should look at libnetcdf-19.dll in bin. Still for some reasons I get this error in my package:

https://github.com/Alexander-Barth/NCDatasets.jl/runs/3870249033?check_suite_focus=true#step:7:85

**Comment by Alexander-Barth** [comment]
Unfortunately, this is still the same (from a fresh julia session):

```
julia> using NetCDF_jll, Libdl

julia> nclib = Libdl.dlopen(libnetcdf,RTLD_LAZY|RTLD_DEEPBIND|RTLD_GLOBAL)
Ptr{Nothing} @0x0000000066f40000

julia> dlsym(nclib,:nc_inq_libvers)
ERROR: could not load symbol "nc_inq_libvers":
The specified procedure could not be found.
Stacktrace:
 [1] #dlsym#1
   @ .\libdl.jl:56 [inlined]
 [2] dlsym(hnd::Ptr{Nothing}, s::Symbol)
   @ Base.Libc.Libdl .\libdl.jl:54
 [3] top-level scope
   @ REPL[5]:1
```

I am trying with the old NetCDF library to see what could be the difference.

**Comment by giordano** [comment]
I believe I'm crashing into this issue in #4344.  Honestly, I have zero clue about what's wrong with the Windows build, but I confirm it looks "broken"

**Comment by Alexander-Barth** [comment]
Here is a fresh attempt:
https://github.com/Alexander-Barth/Yggdrasil/tree/NetCDF-v4.8.1/N/NetCDF

I tried to find some volunteers to test the library before I make a PR:
https://github.com/Alexander-Barth/NCDatasets.jl/issues/165
