### ISSUE TITLE
Package mintty for windows

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#382]
It would be great if [mintty](https://github.com/mintty/mintty/) could be made available through BB:

https://github.com/JuliaLang/julia/issues/7267 
https://github.com/JuliaLang/julia/pull/33821

**Comment by ViralBShah** [comment]
Looks like it should be pretty straightforward: https://github.com/mintty/mintty/blob/master/INSTALL

**Comment by ViralBShah** [comment]
AFAICT, the easiest way to get mintty on a user system is to install MSYS2 and then either build it, or use `pacman` to install the binaries.

**Comment by ViralBShah** [comment]
Another possibility is to assume Windows 10 as minimum, and then go the WSL route with something like https://github.com/goreliu/wsl-terminal

**Comment by goggle** [comment]
From the Windows Terminal Readme:

> Windows Terminal requires Windows 10 1903 (build 18362) or later

As long as it doesn't run on Windows 8, it's probably no suitable choice for Julia, right?

**Comment by ViralBShah** [comment]
My thought was that it is better to have something that works rather than nothing.

**Comment by ViralBShah** [comment]
Shipping through the BB infrastructure is not the right thing. Follow the progress in https://github.com/JuliaLang/julia/issues/7267
