### ISSUE TITLE
Add Project.toml?

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/Yggdrasil#3830]
The README instructions simply state:
```
julia --color=yes generate_buildjl.jl Z/Zlib/build_tarballs.jl
```
but this doesn't out of the box as there is no project specified.

Should one be added to the main directory (there is one in the `.ci` directory: is this sufficient, if so, should it be moved up?)

**Comment by simonbyrne** [comment]
> there is one in the `.ci` directory: is this sufficient, if so, should it be moved up?

Apparently not:
```
> julia --project=.ci --color=yes generate_buildjl.jl Z/Zlib/build_tarballs.jl
ERROR: LoadError: ArgumentError: Package GitHub not found in current path:
- Run `import Pkg; Pkg.add("GitHub")` to install the GitHub package.
```

**Comment by simonbyrne** [comment]
Also, the sample in the README doesn't actually work even with the required dependencies:
```
├ julia --color=yes generate_buildjl.jl Z/Zlib/build_tarballs.jl
[ Info: Build tarballs script: Z/Zlib/build_tarballs.jl
[ Info: Repo name: JuliaBinaryWrappers/Zlib_jll.jl
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Error: Unable to determine latest version of Zlib,
│ please specify it as third argument to this script:
│     generate_buildjl.jl Z/Zlib/build_tarballs.jl JuliaBinaryWrappers/Zlib_jll.jl <tag_name>
```

**Comment by giordano** [comment]
Zlib may not be the best example since it's a stdlib now, so Pkg may have problems looking it up in the registry.  Try something else

**Comment by thofma** [comment]
Maybe `instantiate` first? Ah, this is for the BinaryProvider legacy stuff. You need to add a tag.

**Comment by thofma** [comment]
Before you was too much time, here is an example invocation:
```
julia --project=.ci generate_buildjl.jl F/FLINT/build_tarballs.jl JuliaBinaryWrappers/FLINT_jll.jl FLINT-v200.800.100+0
```
