### ISSUE TITLE
Request: Gtk4

### ISSUE THREAD

**Issue by tknopp** [JuliaPackaging/Yggdrasil#3898]
It would be great to have Gtk4 binaries in order to start working on
  https://github.com/JuliaGraphics/Gtk.jl/issues/540
I cannot estimate how large the effort is. They switched to meson, so probably it is higher.

---

Dependencies (may not all be actually needed, but show up in the log):

* [x] wayland-protocols (#3917, #3923)
* [x] graphene-gobject (<s>gobject types should be already in [`Graphene_jll`](https://github.com/JuliaPackaging/Yggdrasil/blob/44caec1161cf4550fa5aabad305b7a8df17e9cb4/G/Graphene/build_tarballs.jl), need to understand if we need something else</s>  it seems to be working fine now)
* <s>[ ] mutest</s> not idea what it is and it doesn't seem to be needed anymore (was it ever?)
* <s>[ ] gi-docgen</s> we can install it with `pip`, yay.  Edit: `gi-docgen` is only needed for docs, so we can just skip it
* <s>[ ] sassc</s> we can install it with `apk`.  It may still be nicer to have it built so we can use a `HostBuildDependency`, but not strictly necessary to get this working.  Edit: `SassC_jll` added with #4380 
* <s>[x] [libsass](https://github.com/lazka/libsass/tree/meson) (#4363)</s> it turns out this was only a dependency of sassc, so we don't directly need it

Relevant links:

* [`meson.build`](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/meson.build)
* [subprojects](https://gitlab.gnome.org/GNOME/gtk/-/tree/main/subprojects)

**Comment by giordano** [comment]
As an updated, I opened #3915 to build Gtk 4.  At the moment it's working everywhere except for macOS, where I'm having some linking errors I can't quite decipher (looks like we're building a corrupted static library or something like that).
