### ISSUE TITLE
openmpi launcher doesn't work

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/Yggdrasil#390]
```
julia> using OpenMPI_jll

julia> run(`$(joinpath(OpenMPI_jll.artifact_dir,"bin/mpiexec")) -n 1 echo "hello world"`)
/Users/simon/.julia/artifacts/f24c8af1d7b16743676909b7f55de55de4ffc8e0/bin/mpiexec: Error: unknown option "-n"
ERROR: failed process: Process(`/Users/simon/.julia/artifacts/f24c8af1d7b16743676909b7f55de55de4ffc8e0/bin/mpiexec -n 1 echo 'hello world'`, ProcessExited(1)) [1]
```

MPICH_jll seems to work fine.

Also, what is the correct way to launch binaries in artifacts?

**Comment by simonbyrne** [comment]
cc @ViralBShah

**Comment by simonbyrne** [comment]
Ah, so `ExecutableProduct`s should be registered for `mpiexec` (in both MPICH_jll and OpenMPI_jll).

**Comment by giordano** [comment]
I think you need to set `OPAL_PREFIX`:
```julia
julia> ENV["OPAL_PREFIX"] = OpenMPI_jll.artifact_dir
"/home/mose/.julia/artifacts/aa1eabb95405b46bd5fbe18a74e516e1eea3fb5e"

shell> $(joinpath(OpenMPI_jll.artifact_dir,"bin/mpiexec")) -n 1 echo "hello world"
hello world
```

**Comment by giordano** [comment]
> Ah, so ExecutableProducts should be registered for mpiexec (in both MPICH_jll and OpenMPI_jll).

Yes, that will make calling the executables much easier.

Note that the JLL packages are very thin wrappers and take care only of the standard environment variables.  It's the duty of the Julia packages using them to set all the other variables necessary.

Sometimes finding all the variables that you need to set is a fun ride, like in #284

**Comment by simonbyrne** [comment]
So you’re saying we can’t set the environment variable in the jll?

**Comment by giordano** [comment]
Yes, at least as it is now. We don't have any mechanism to inject custom code because the wrapper is supposed to be as small as possible.

**Comment by ViralBShah** [comment]
So far, I only got around to getting the builds going.

**Comment by giordano** [comment]
I assume the original issue has been clarified, so I'm going to close the issue

**Comment by simonbyrne** [comment]
Not really: we would need a way to set OPAL_PREFIX to make this useable

**Comment by giordano** [comment]
Can't you do it in MPI.jl?

**Comment by simonbyrne** [comment]
I guess this gets back to the debate of what interface the wrapper jll packages should provide.

I would argue that it should belong in the wrapper since it is specific only to Open MPI, and is only needed here because it was built to be relocateable.

**Comment by ViralBShah** [comment]
I am ok with deleting OpenMPI altogether, since we have settled on MPICH.

**Comment by simonbyrne** [comment]
Is there any harm to keeping it? It would be nice at some point to have the option to switch between them.

**Comment by ViralBShah** [comment]
No harm.

**Comment by giordano** [comment]
I've opened a more general issue at https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/687.
