### ISSUE TITLE
Request: Slate

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#3941]
https://icl.utk.edu/slate/

Quoting:

The ultimate objective of SLATE is to replace the venerable Scalable Linear Algebra PACKage (ScaLAPACK) library, which has become the industry standard for dense linear algebra operations in distributed memory environments. However, after two decades of operation, ScaLAPACK is past the end of its lifecycle and overdue for a replacement, as it can hardly be retrofitted to support hardware accelerators, which are an integral part of today’s HPC hardware infrastructure.

**Comment by jishnub** [comment]
Is this resolved by https://github.com/JuliaPackaging/Yggdrasil/pull/4093?
