### ISSUE TITLE
[MPICH] MPIX_Query_cuda_support triggers assertion error

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/Yggdrasil#4039]
Calling `MPIX_Query_cuda_support` from MPICH_jll triggers an assertion error (the one from Homebrew works correctly). This affects both Mac and Linux.

```julia
julia> using MPICH_jll

julia> ccall((:MPI_Init, MPICH_jll.libmpi), Cint, (Ptr{Cvoid}, Ptr{Cvoid}), C_NULL, C_NULL)
0

julia> ccall((:MPIX_Query_cuda_support, MPICH_jll.libmpi), Cint,())
Assertion failed: (mpi_errno), function MPIX_Query_cuda_support, file src/mpi/misc/gpu.c, line 90.

signal (6): Abort trap: 6
in expression starting at REPL[3]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 873305 (Pool: 873108; Big: 197); GC: 1
Abort trap: 6
```

cc: @vchuravy @giordano

**Comment by giordano** [comment]
Would a debug build help?  Actually, in the compilation log I can see many `-g` already, so your library may have debug symbols.

**Comment by simonbyrne** [comment]
It turns out it was an MPICH bug after all (assertions are only enabled in debug builds).
