### ISSUE TITLE
Error in LLVM

### ISSUE THREAD

**Issue by sclel016** [JuliaPackaging/Yggdrasil#4151]
Hi,

I ran into an error trying to precompile LLVM. Seems to be missing `libLLVMExtra-12.so` from the `LLVMExtra_jll` module. The `LLVM_jll` README suggested raise an issue here. See below for minimal reproduction steps. I am happy to help debug if needed.

- OS: Arch Linux
- Julia Version: 1.7

```
julia> using LLVM
 │ Package LLVM not found, but a package named LLVM is available from a registry. 
 │ Install package?
 │   (@v1.7) pkg> add LLVM 
 └ (y/n) [y]: y
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [929cbde3] + LLVM v4.7.0
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
[ Info: Precompiling LLVM [929cbde3-209d-540e-8aea-75f648917ca0]
ERROR: LoadError: InitError: could not load library "/home/user/.julia/artifacts/4386222cf8520251f2e187bad84e2ed299f4624a/lib/libLLVMExtra-12.so"
libLLVM-12jl.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/library_generators.jl:54 [inlined]
 [2] __init__()
   @ LLVMExtra_jll ~/.julia/packages/LLVMExtra_jll/RFVqe/src/wrappers/x86_64-linux-gnu-cxx11-julia_version+1.7.0.jl:8
 [3] top-level scope (repeats 2 times)
   @ none:1
during initialization of module LLVMExtra_jll
in expression starting at /home/user/.julia/packages/LLVM/shuW4/src/LLVM.jl:1
ERROR: Failed to precompile LLVM [929cbde3-209d-540e-8aea-75f648917ca0] to /home/user/.julia/compiled/v1.7/LLVM/jl_j8TZGo.
```

**Comment by vchuravy** [comment]
Which Archlinux package are you using? The only one we support is `julia-bin`.

**Comment by sclel016** [comment]
I'm using `julia` from the official repository. I don't see a `julia-bin` package offered in the offiicial repository or in the AUR.

```
$  pacman -Qi julia
Name            : julia
Version         : 2:1.7.1-2
Description     : High-level, high-performance, dynamic programming language
Architecture    : x86_64
URL             : https://julialang.org/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : cblas  fftw  hicolor-icon-theme  libgit2  libunwind  libutf8proc  openblas  suitesparse  mbedtls  openlibm  pcre2  llvm-libs  p7zip  libblastrampoline
Optional Deps   : gnuplot: If using the Gaston Package from julia [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : julia-docs
Installed Size  : 176.66 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Sat 25 Dec 2021 04:58:36 PM EST
Install Date    : Tue 28 Dec 2021 04:25:53 PM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by vchuravy** [comment]
The build from the official Archlinux repository uses the system LLVM which is currently LLVM 13. Julia 1.7 only support LLVM 12 and LLVM 13 is not a supported option. Indeed Archlinux has choosen to patch https://github.com/archlinux/svntogit-community/blob/837ddd33a2aca1f0579638d8fb0742d068acc82e/trunk/PKGBUILD#L53 Julia.

Additionally we require a set of patches to provide full functionality against LLVM 12 (or 13)  which are not carried. I have asked them in the past to not use the system LLVM, but they continue to provide an unsupported and untested configuration.

**Comment by sclel016** [comment]
Thanks for the detailed answer, I'll use `julia-bin` for the time being. Seems like a pretty major patch on the part of the `julia` maintainers. Is there any timeline for Julia to support LLVM 13?

**Comment by vchuravy** [comment]
Julia 1.8 is slated to support LLVM 13, baring no major regressions or delays. 

x-ref: https://github.com/JuliaLang/julia/pull/42602
