### ISSUE TITLE
Arb_jll needs updating

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaPackaging/Yggdrasil#4265]
https://github.com/JuliaBinaryWrappers/Arb_jll.jl  is out of date, the current version is 2.22.0 .. updating the jll should not cause anything to break. There are some helpful improvements in this version that others want to use.

**Comment by fingolfin** [comment]
I am very wary about claims that any given JLL update "shouldn't break anything" ;-). In theory this is true, in practice sadly it often isn't... Anyway, you can open a PR here similar to https://github.com/JuliaPackaging/Yggdrasil/pull/4090 but please ping @thofma (and perhaps me) for it, as we also use it, and as we learned, updates to it *can* break our stuff.

**Comment by JeffreySarnoff** [comment]
Thanks. Will do.

**Comment by JeffreySarnoff** [comment]
Where do I find / how do I generate the identifying hex string like this onw for the current version?
```
sources = [
    ArchiveSource("https://github.com/fredrik-johansson/arb/archive/refs/
                  "aecc9f55eb35a00a2490e9a7536a0babf8ac86bb13d32a4a95e1216f9f5cbfa8"),
]```
