### ISSUE TITLE
Adding Intel's Decimal Floating-Point Math Library

### ISSUE THREAD

**Issue by bicycle1885** [JuliaPackaging/Yggdrasil#427]
[DecFP.jl](https://github.com/JuliaMath/DecFP.jl) depends on [Intel's Decimal Floating-Point Math Library](https://software.intel.com/en-us/articles/pre-release-license-agreement-for-intel-decimal-floating-point-math-library), the binaries of which are now distributed at https://github.com/quinnj/DecFPBuilder. I think the package is widely used and thus it's worth adding its dependencies here. If you like it, I'm happy to work on it.

**Comment by giordano** [comment]
>  If you like it, I'm happy to work on it.

No need to ask, just do it :wink:

**Comment by randyzwitch** [comment]
Yes, please!

**Comment by randyzwitch** [comment]
Just a heads up that the current version of DecFP is not thread-safe, which there is an issue for:

https://github.com/JuliaMath/DecFP.jl/issues/39#issuecomment-573170555

**Comment by bicycle1885** [comment]
@randyzwitch Thank you. I'll try to make it thread-safe.

**Comment by ViralBShah** [comment]
It would be good to checkin the Intel codebase into a repo (maybe in JuliaMath) and then build from there.

**Comment by jmkuhn** [comment]
I've added some additional notes on making DecFP thread-safe in https://github.com/JuliaMath/DecFP.jl/issues/39#issuecomment-584707054
