### ISSUE TITLE
LibSndFile cannot precompile on Windows

### ISSUE THREAD

**Issue by justinjhlo** [JuliaPackaging/Yggdrasil#4303]
`LibSndFile` is now [failing to precompile on Windows](https://github.com/JuliaAudio/LibSndFile.jl/issues/51) with `libsndfile_jll v1.0.31+2`. Downgrading to `v1.0.31+1` seems to work just fine, though I have no idea what might be causing this issue. (Downgrading to `v1.0.31+0` breaks, but `v1.0.28+2` works.)

**Comment by aviks** [comment]
The downstream issue is closed, so maybe this should be as well.
