### ISSUE TITLE
[SDL2] SDL2 does not load on the Mac

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/Yggdrasil#434]
SDL2_jll fails to load on the Mac with the following error. Any idea why? Seems to work in Windows and Linux. 

cc: @giordano @NHDaly 

```
ERROR: LoadError: InitError: could not load library "/Users/travis/.julia/artifacts/07269157a430173d2493ced9ed3982219f62b22d/lib/libSDL2_image.dylib"

dlopen(/Users/travis/.julia/artifacts/07269157a430173d2493ced9ed3982219f62b22d/lib/libSDL2_image.dylib, 1): Library not loaded: @rpath/libiconv.2.dylib

  Referenced from: /Users/travis/.julia/artifacts/07269157a430173d2493ced9ed3982219f62b22d/lib/libSDL2_image.dylib

  Reason: Incompatible library version: libSDL2_image.dylib requires version 9.0.0 or later, but libiconv.2.dylib provides version 7.0.0
```

**Comment by giordano** [comment]
Yes, that's a known problem that thanks to https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/611 is now caught by the audit.

I'm rebuilding SDL2 in https://github.com/JuliaPackaging/Yggdrasil/pull/433 to fix other errors, but I'm having troubles exactly on macOS with iconv. I need to understand what's going on
