### ISSUE TITLE
SLICOT_jll macOS: image not found

### ISSUE THREAD

**Issue by RalphAS** [JuliaPackaging/Yggdrasil#4414]
I'm getting the following error when trying to run CI on a wrapper for SLICOT_jll:

  > could not load library "libslicot"
  >  dlopen(libslicot.dylib, 1): image not found

Context: https://github.com/RalphAS/SLICOTMath.jl/runs/5104058787

The BB run seemed to be successful, and the appropriate artifact has the library in the tarball, so I'm confused.  Any suggestions?

**Comment by giordano** [comment]
https://github.com/RalphAS/SLICOTMath.jl/blob/efe0ae7d97810dbd7809bb1862e3c4bbf75bf893/src/slicot_m.jl#L1081 You have to refer the variable `libslicot`, not the string `"libslicot"`.  See https://docs.binarybuilder.org/stable/jll/#LibraryProduct
