### ISSUE TITLE
GTK4 needs GLib 2.70

### ISSUE THREAD

**Issue by jwahlstrand** [JuliaPackaging/Yggdrasil#4458]
I am having trouble doing GObject introspection in Julia with GTK4. When my code fails, I see the following warning:

`** (process:1705108): WARNING **: 08:05:55.445: Failed to load shared library 'libgtk-4.so.1' referenced by the typelib: /lib64/libgtk-4.so.1: undefined symbol: g_source_set_static_name`

It looks like `g_source_set_static_name` was introduced in GLib 2.70. So contrary to the required version in meson.build, it looks like GTK4 requires GLib 2.70.

It looks like this was reported but hasn't been fixed yet:
https://gitlab.gnome.org/GNOME/gtk/-/issues/4195

**Comment by giordano** [comment]
`/lib64/libgtk-4.so.1` are you sure you're loading the right library from the artifacts?  It doesn't look like that.  Do you have `LD_LIBRARY_PATH` set?

**Comment by jwahlstrand** [comment]
Sorry, I see now that they solved the issue without requiring GLib 2.70 -- I'll close this.

The way I'm doing GObject introspection is currently sort of shady. It uses libgirepository installed on my system and the typelibs installed by my distribution, which reference the distribution libraries, not the ones installed as jll's. This has worked for everything I've tried, including GTK4 until now. My distribution version of GTK4 must have updated recently, because this worked back in December.

I was hoping to keep getting away with this, but it would be more correct to use the libraries in Yggdrasil. I will try compiling those locally, including the typelib outputs, and see if that fixes my problem.
