### ISSUE TITLE
macOS ARM (m1) packaging support for libisoband

### ISSUE THREAD

**Issue by Mixpap** [JuliaPackaging/Yggdrasil#4507]
Hi, pasting from GLMakie issues (https://github.com/JuliaPlots/Makie.jl/issues/1708):
Trying to make a contour plot through GLMakie in a mac-os m1 arm system (julia version macOS ARM) gives this error. 
`ERROR: UndefVarError: libisoband not defined`

Julia version: 1.7.2
GLMakie version: GLMakie v0.5.4

**Comment by jeremiahpslewis** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/4508
