### ISSUE TITLE
Cannot initialize Ncurses in macOS

### ISSUE THREAD

**Issue by ronisbr** [JuliaPackaging/Yggdrasil#455]
Hi!

For some reason, I cannot initialize Ncurses using `Ncurses_jll` in macOS.

```julia
julia> using Ncurses_jll

julia> ccall( (:initscr, libncurses), Cvoid, ())
Error opening terminal: xterm-256color.
```

After that, julia crashes. Passing the env. option `TERM=xterm` did not help also.

I can start Ncurses normally if I use the library that ships with macOS or the library in home-brew.

**Comment by giordano** [comment]
You probably need to set the environment variable `TERMINFINO_DIRS`:
```julia
julia> using Ncurses_jll

julia> withenv("TERMINFO_DIRS" => joinpath(Ncurses_jll.artifact_dir, "share", "terminfo")) do
           ccall( (:initscr, libncurses), Cvoid, ())
       end
```

**Comment by giordano** [comment]
Also `TERMINFO` should work.  In any case, it's better to wrap the calls in a `withenv` to avoid setting this variable for the whole Julia session

**Comment by ronisbr** [comment]
This work! However, I need to set for the whole Julia session, otherwise I will have to do a strange logic because I need to let the user to load its own ncurses version. Is there any downside?

**Comment by giordano** [comment]
> This work!

Great, then I'm going to close the ticket.

> Is there any downside?

The only problem can arise if there are other, different instances of ncurses loaded in the same session, that might be wrecked by this setting.  The probability of this situation is likely very low.  If all Julia packages needing ncurses use `Ncurses_jll` there will be no problem, of course.

You're free to set the variable with `ENV["TERMINFO"]`, just be aware that if someone will complain about `TextUserInterfaces.jl` breaking other packages that use ncurses, that's likely the issue.

**Comment by ronisbr** [comment]
Thanks very much for the quick help!
