### ISSUE TITLE
Weird CI/CD Issue when using Github's 'built in' VScode to generate PR

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaPackaging/Yggdrasil#4565]
When using the `.` shortcut to edit this project and then generate a PR, the CI/CD subsequently fails with this error:
<img width="761" alt="Screen Shot 2022-03-07 at 11 10 50" src="https://user-images.githubusercontent.com/4462211/157011374-506453b5-b73f-4c90-a121-ddb6e86d6e24.png">

**Comment by jeremiahpslewis** [comment]
A workaround to get things working again is to change the base branch to something else, then back to master:
<img width="684" alt="Screen Shot 2022-03-07 at 11 12 32" src="https://user-images.githubusercontent.com/4462211/157011517-95453657-0a5e-4c2f-b54e-99d273bc4852.png">


An example of where this happened is here: https://github.com/JuliaPackaging/Yggdrasil/pull/4564

**Comment by giordano** [comment]
Complain with github/azure pipelines support? I don't see what we can possibly do

**Comment by jeremiahpslewis** [comment]
Fair point, just wanted to make this 'easy to google'. :)

**Comment by giordano** [comment]
> just wanted to make this 'easy to google'

Screenshot aren't very easy to google.

I tried to do some debugging in #3877 (which at this point I guess was created in the same way), but it looks to me that when you open a PR in that way we get a repo with missing refs.
