### ISSUE TITLE
RDKit for windows

### ISSUE THREAD

**Issue by longemen3000** [JuliaPackaging/Yggdrasil#4714]
it seems that RDKit_jll is not being compiled for windows.
the main reason seems that it seems to require MSVC, see: https://github.com/eloyfelix/RDKitMinimalLib.jl/issues/13 
but there is nothing in RDKit saying that this is a requirement, and they even merged fixes for mingw https://github.com/rdkit/rdkit/issues?q=mingw so it could just work by adding windows as a compile target?

**Comment by giordano** [comment]
```
-- Could NOT find coordgen (missing: coordgen_INCLUDE_DIRS coordgen_LIBRARIES) 
Downloading https://github.com/schrodinger/coordgenlibs/archive/v3.0.0.tar.gz...
Downloading https://github.com/rareylab/RingDecomposerLib/archive/v1.1.3_rdkit.tar.gz...
CMake Error at Code/RDGeneral/CMakeLists.txt:29 (message):
  Please set MSVC_RUNTIME_DLL to the full path to a msvcrXXX.dll Microsoft
  Visual C Runtime DLL appropriate for your system; the most likely path is
  /System32, or /SysWOW64 in case you are building 32-bit RDKit under a
  64-bit Windows OS.
```

**Comment by longemen3000** [comment]
it is possible to use `RDK_THREADSAFE_SSS=OFF` only on windows? looking at https://github.com/rdkit/rdkit/pull/4349 , it seems that it adds locks to certain operations
