### ISSUE TITLE
Dependency tree for Pango and Cairo

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#48]
Ok, I feel like I need to clearly write somewhere a dependency tree of Pango and Cairo;

- [x] Pango (PR #41)
  - [x] Cairo (PR #39)
    - [x] libX11 (necessary only on Linux and FreeBSD)
    - [x] LZO
    - [x] Pixman
    - [x] libpng
    - [x] zlib
  - [x] HarfBuzz (necessary only on Linux and FreeBSD) (PR #50)
    - [x] Glib
    - [x] Graphite (PR #49)
    - [ ] ICU (maybe only compile-time?)
    - [x] FreeType2
    - [x] Cairo (PR #39)
  - [x] FriBidi
  - [x] Libffi
  - [x] Gettext
  - [x] Libiconv
  - [x] FreeType2
    - [x] bzip2
  - [x] Glib
    - [x] PCRE
  - [x] FontConfig (necessary only on Linux and FreeBSD)
    - [x] Expat
    - [x] Libuuid

**Comment by ViralBShah** [comment]
This is insane! Nicely done. IIRC, The last time we might have shipped all this stuff was in Julia 0.1. :-)

**Comment by giordano** [comment]
It seems that this can be closed, now :slightly_smiling_face:
