### ISSUE TITLE
Request: KMC

### ISSUE THREAD

**Issue by SabrinaJaye** [JuliaPackaging/Yggdrasil#4813]
Hi, I'd love to get the popular Kmer counter KMC into the tree. Sadly its makefile is a bit... blergh so I'm not sure I'm going about this correctly, assistance would be massively appreciated.

I've tried to use the wizard myself which resulted in the builder script below.

I had to do something a bit hacky and sed a line in the makefile that hardcoded a g++ path on MacOS.

Now, as far as I can make out from the Makefile, a lot of code gets compiled into a library (on Mac $prefix/bin/libkmc_core.mac.a) that has not been picked up by the wizard as a product.

Additionally in the build recipe, after the make step, I copy over some additional .h files in `kmc_api` to `$prefix/include` that I think I would use with said .a file in `$prefix/bin` to make my intended CxxWrap wrapper. - Since the makefile they provide does not have a `make install` option.

```
# Note that this script can accept some limited command-line arguments, run
# `julia build_tarballs.jl --help` to see a usage message.
using BinaryBuilder, Pkg

name = "KMC"
version = v"3.2.1"

# Collection of sources required to complete build
sources = [
    ArchiveSource("https://github.com/refresh-bio/KMC/archive/refs/tags/v$(version).zip", "b306c4761d468605e22344e8f3e8e0b4dffe059f8b1195764c7ff0d17972bec9")
]

# Bash recipe for building across all platforms
script = raw"""
cd $WORKSPACE/srcdir/KMC-3.2.1/
sed -i -e 's/CC = \/usr\/local\/bin\/g++-10/CC = g++/' Makefile
make kmc kmc_dump kmc_tools
cp kmc_api/*.h include/
cp -r bin $prefix/
cp -r include $prefix/
"""

# These are the platforms we will build for by default, unless further
# platforms are passed in on the command line
platforms = [
    Platform("x86_64", "linux"; libc = "glibc"),
    Platform("x86_64", "macos"; )
]


# The products that we will ensure are always built
products = [
    ExecutableProduct("kmc_dump", :kmc_dump),
    ExecutableProduct("kmc_tools", :kmc_tools),
    ExecutableProduct("kmc", :kmc)
]

# Dependencies that must be installed before this package can be built
dependencies = Dependency[
]

# Build the tarballs, and possibly a `build.jl` as well.
build_tarballs(ARGS, name, version, sources, script, platforms, products, dependencies; julia_compat="1.6", preferred_gcc_version = v"11.1.0")
```

**Comment by ViralBShah** [comment]
I would suggest submitting a PR and seeing how far it gets.
