### ISSUE TITLE
Proj_jll build fails on Mac OS 10.15.7 Incompatible library version libproj.22.2.1.dylib

### ISSUE THREAD

**Issue by NLaws** [JuliaPackaging/Yggdrasil#4854]
```julia
failed to precompile ArchGDAL [c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3] to ~/.julia/compiled/v1.7/ArchGDAL/jl_6UyohC.
ERROR: LoadError: InitError: could not load library "~/.julia/artifacts/bbbc9628a0d3d50c0295da474b6c09f2fb1712d4/lib/libproj.22.2.1.dylib"
dlopen(~/.julia/artifacts/bbbc9628a0d3d50c0295da474b6c09f2fb1712d4/lib/libproj.22.2.1.dylib, 1): Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: ~/.julia/artifacts/bbbc9628a0d3d50c0295da474b6c09f2fb1712d4/lib/libproj.22.2.1.dylib
  Reason: Incompatible library version: libproj.22.2.1.dylib requires version 12.0.0 or later, but libcurl.4.dylib provides version 11.0.0
```

Very similar to this issue: https://github.com/zdavatz/amiko_wx/issues/149, which was fixed by [Embed dylib to Mac App](https://github.com/zdavatz/amiko_wx/pull/151)

```julia
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:117
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
  [4] __init__()
    @ PROJ_jll ~/.julia/packages/PROJ_jll/8VPzD/src/wrappers/x86_64-apple-darwin.jl:60
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
  [7] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:783
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:843
  [9] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:783
 [10] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:843
 [11] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:783
 [12] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:843
 [13] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
 [14] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
 [15] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
 [16] include
    @ ./Base.jl:418 [inlined]
 [17] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1318
 [18] top-level scope
    @ none:1
 [19] eval
    @ ./boot.jl:373 [inlined]
 [20] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [21] top-level scope
    @ none:1
during initialization of module PROJ_jll
```

**Comment by giordano** [comment]
How did you install Julia?  What's the output of
```julia
julia> using Libdl

julia> filter!(x -> occursin("curl", x), dllist())
1-element Vector{String}:
 "/usr/bin/../lib/julia/libcurl.so"

```
?

**Comment by NLaws** [comment]
I installed Julia using the .dmg from julialang.org/downloads.
```
julia> filter!(x -> occursin("curl", x), dllist())
1-element Vector{String}:
 "/Applications/FICO Xpress/Xpres" ⋯ 32 bytes ⋯ "es/xpressmp/lib/libcurl.4.dylib"

julia> @info(filter!(x -> occursin("curl", x), dllist()))
[ Info: ["/Applications/FICO Xpress/Xpress Workbench.app/Contents/Resources/xpressmp/lib/libcurl.4.dylib"]
```
But looks like updating FICO Xpress messed with something?

**Comment by giordano** [comment]
I have no idea what FICO Xpress is, but it does look like you're loading the wrong LibCURL, instead of the one provided by Julia

**Comment by NLaws** [comment]
@giordano how do I load the correct LibCURL?

**Comment by giordano** [comment]
By understanding how an unrelated package is taking over julia libraries in the first place, but that's something you have to figure out, we can't possibly do anything from inside the julia process.

For example your `DYLD_FALLBACK_LIBRARY_PATH` may include `/Applications/FICO Xpress/Xpress Workbench.app/Contents/Resources/xpressmp/lib`.

**Comment by giordano** [comment]
> Can you point me towards documentation on how Julia/ Proj_jll affects the output of dllist so that I can figure out how to get the right LibCURL?

Again, this isn't specific to Julia, and proj has nothing to do with all of this (apart from the fact it needs a libcurl).  libcurl should be loaded at the start of the julia process (it's a dependency of julia itself), you should see the same if you check the content of `dllist` in a fresh session, without involving proj.

> Or should I just reinstall Julia perhaps?

I doubt reinstalling Julia would change much, it's your environment that is forcing loading an unrelated library.

**Comment by giordano** [comment]
You can maybe try to set the environment variable `DYLD_PRINT_LIBRARIES=1` to try and see where the external libcurl is coming from.  I can't give you much more help, I'm not too familiar with debugging on macOS, but once again, it's your system which somehow is forcing it and you should figure out why.  And maybe report back how you did it, so we learn the process :slightly_smiling_face:

**Comment by NLaws** [comment]
Should there be a `libcurl` dylib in the `dllist` in the Julia folder? I see one from Xpress but not Julia (showing all Julia dylibs):
```
 "/Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/sys.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 19 bytes ⋯ "ia/lib/julia/libpcre2-8.0.dylib"
 "/Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libgmp.10.dylib"
 "/Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libmpfr.6.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 28 bytes ⋯ "lia/libopenblas64_.0.3.13.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 20 bytes ⋯ "a/lib/julia/libgfortran.5.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 20 bytes ⋯ "a/lib/julia/libquadmath.0.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 24 bytes ⋯ "b/julia/libblastrampoline.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 24 bytes ⋯ "b/julia/libcholmod.3.0.14.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 19 bytes ⋯ "ia/lib/julia/libamd.2.4.6.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 22 bytes ⋯ "lib/julia/libcolamd.2.9.6.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 34 bytes ⋯ "bsuitesparseconfig.5.10.1.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 23 bytes ⋯ "ib/julia/libccolamd.2.9.6.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 20 bytes ⋯ "a/lib/julia/libcamd.2.4.6.dylib"
 "/Applications/Julia-1.7.app/Con" ⋯ 20 bytes ⋯ "a/lib/julia/libnghttp2.14.dylib"
 "/Applications/FICO Xpress/Xpres" ⋯ 32 bytes ⋯ "es/xpressmp/lib/libcurl.4.dylib"
 "/Applications/FICO Xpress/Xpres" ⋯ 33 bytes ⋯ "s/xpressmp/lib/libssl.1.1.dylib"
 "/Applications/FICO Xpress/Xpres" ⋯ 36 bytes ⋯ "pressmp/lib/libcrypto.1.1.dylib"
 ```

**Comment by giordano** [comment]
> Should there be a libcurl dylib in the dllist in the Julia folder?

Yes, as I said julia comes with libcurl, and we expect to load that one.  The library should be in the same directory as all the other libraries you're seeing.  If your environment if forcing the julia process to load a different libcurl, we're out of luck.

> I see one from Xpress but not Julia (showing all Julia dylibs):

And that's the wrong one :slightly_smiling_face:

More than reinstalling Julia, I think it'd be useful to uninstall FICO Xpress, whatever that is :stuck_out_tongue:  Jokes apart, programs shouldn't overtake other applications, that's quite annoying for them to do it.  What's the value of `ENV["DYLD_FALLBACK_LIBRARY_PATH"]` inside Julia?

**Comment by NLaws** [comment]
> What's the value of `ENV["DYLD_FALLBACK_LIBRARY_PATH"]` inside Julia?
```
julia> ENV["DYLD_FALLBACK_LIBRARY_PATH"]
ERROR: KeyError: key "DYLD_FALLBACK_LIBRARY_PATH" not found
```
Unfortunately I need FICO Xpress (it is a dependency of Xpress.jl). I did reinstall Julia but it did not change the `dllist`. Is there a manually way to update the symlinks or ? for Julia? I'm totally naive on how this works. I see libcurl.4.4dylib and libcurl.dylib in /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia, so I guess that those need to show up in `dllist`? Maybe the Julia libcurl.4.4dylib was superseded by the FICO Xpress libcurl.4.4dylib when I installed FICO Xpress.

**Comment by giordano** [comment]
> Maybe the Julia libcurl.4.4dylib was superseded by the FICO Xpress libcurl.4.4dylib when I installed FICO Xpress.

I'm not completely familiar with how things work on macOS, but at least on Linux it isn't sufficient to just have a package in your machine to have its libraries magically take over others.  There are mechanisms to control the order with which libraries are loaded.  For example one of those is `LD_LIBRARY_PATH` (the Linux equivalent of `DYLD_FALLBACK_LIBRARY_PATH`) which forces the dynamic loader to look for libraries listed in those directories before libraries listed in the runpath of a dynamic library.  Otherwise the dynamic loader wouldn't even think about searching for a library in `Applications/FICO Xpress/Xpress Workbench.app/Contents/Resources/xpressmp/lib`, that's an absurd path.

What I'm trying to tell you is that there is ***something*** in your environment which is hooking into this mechanism and letting the dynamic loader finding `Applications/FICO Xpress/Xpress Workbench.app/Contents/Resources/xpressmp/lib/libcurl.4.dylib` before julia's own libcurl when starting the Julia process.  Your now facing this issue with Julia, but there may be other applications needing libcurl which would have precisely the same issue of loading a wrong libcurl because something is telling libraries in `Applications/FICO Xpress/Xpress Workbench.app/Contents/Resources/xpressmp/lib` to have precedence of other libraries.  Again, I can't tell you much more than this because I'm not familiar with this kind of problems on macOS, but this is what it is.  I already mentioned a couple of things like `DYLD_FALLBACK_LIBRARY_PATH`, and also `DYLD_PRINT_LIBRARIES=1` for debugging (on Linux that'd be `LD_DEBUG=all`), I really don't know more.

**Comment by NLaws** [comment]
Ok thanks. Here is a very similar issue (but with git it seems):
https://github.com/Homebrew/legacy-homebrew/issues/15698
The issue was with `DYLD_LIBRARY_PATH`: FICO Xpress requires appending to `DYLD_LIBRARY_PATH`. I still had the older version of FICO Xpress `DYLD_LIBRARY_PATH` additions in my .bash_profile. 

I can now use ArchGDAL, which depends on Proj_jll (which depends on libcurl?). Oddly though I still get:
```julia
using Libdl
julia> filter!(x -> occursin("curl", x), dllist())
1-element Vector{String}:
 "/Applications/FICO Xpress/Xpres" ⋯ 32 bytes ⋯ "es/xpressmp/lib/libcurl.4.dylib"
```
I guess that the libcurl in FICO Xpress now has version 12.0.0 or later of curl.
