### ISSUE TITLE
Remove MPIconstants from MPICH and OpenMPI?

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#4938]
I believe that the build products from `MPIconstants` in the `MPICH` and `OpenMPI` packages are unused by `MPI.jl`. If this is so, then `MPIconstants` can be removed from these two packages. (It is still necessary for `MPItrampoline`.)

I introduced `MPIconstants` to provide a unified way to access these constants in `MPI.jl`, independent of any current or future MPI implementation. The respective code in `MPI.jl` has since been changed, and `MPI.jl` now supports only specific MPI implementations, with implementation-specific code to extract the respective constants. Thus `MPIconstants` is not necessary any more.

**Comment by giordano** [comment]
Solved
