### ISSUE TITLE
fftw

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#5]
https://github.com/JuliaMath/FFTWBuilder

**Comment by ViralBShah** [comment]
cc @ararslan We should try bring in FFTW in here.

**Comment by ararslan** [comment]
Sounds good to me. What's involved? Just copying the FFTWBuilder stuff into this repo? I haven't really been following Yggdrasil development so I'm not familiar with the process.

**Comment by ViralBShah** [comment]
I believe so. @staticfloat will review the PR anyways, I guess.

**Comment by ViralBShah** [comment]
Pinging @stevengj here as well. If there are no concerns, I can help move FFTWBuilder over once #12 is merged.
