### ISSUE TITLE
Cannot run Tectonic

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaPackaging/Yggdrasil#5022]
I wonder if the current build for Tectonic is correct, but I don't know enough about Yggdrasil and BinaryBuilder to say whether it is broken and if yes how to fix it.

When running the binary on NixOS, I have to patch the interpreter to the following
```
/nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ld-linux-x86-64.so.2
```
Well, that's just NixOS so that's okay.

However, next the following paths need to be available at `LD_LIBRARY_PATH`:

```nix
set -x LD_LIBRARY_PATH "${stdenv.cc.cc.lib}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.fontconfig.lib}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.freetype}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.harfbuzz}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.icu69}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.graphite2}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.libpng}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.zlib}/lib/:$LD_LIBRARY_PATH"
set -x LD_LIBRARY_PATH "${pkgs.openssl.out}/lib/:$LD_LIBRARY_PATH"
```

Is it really expected for the redistributed binary that the user needs to have these binaries installed? I see that the libraries are available in Julia:

https://github.com/JuliaPackaging/Yggdrasil/blob/49bfb2a797b4a5a3fdd58f563ba22bc748c9a3ad/T/tectonic/build_tarballs.jl#L41-L52

but can these also be coupled to the binary in some way? 

I'm happy to do the work here if someone who knows a lot about this stuff could give me some pointers. Thanks

**Comment by giordano** [comment]
Duplicate of #4046 or am I missing something?

**Comment by rikhuijzer** [comment]
> Duplicate of https://github.com/JuliaPackaging/Yggdrasil/issues/4046 or am I missing something?

Yes. You're right. It's a duplicate. 

Even better. It's fixed. The only thing needed is to manually patch `tectonic` at the artifacts path from
```
$ patchelf --print-interpreter tectonic
/lib64/ld-linux-x86-64.so.2
```
to
```
$ patchelf --print-interpreter tectonic
/nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ld-linux-x86-64.so.2
```

then
```julia
julia> ENV["LD_LIBRARY_PATH"]
""

julia> tectonic() do bin
       read(`$bin --version`, String)
       end
"Tectonic 0.9.0\n"
```

So, the main problem for NixOS users is now only to make `/lib64/ld-linux-x86-64.so.2` available which is probably gonna work out https://discourse.nixos.org/t/making-lib64-ld-linux-x86-64-so-2-available/19679.

I'll close this as fixed. Sorry for the noise @giordano
