### ISSUE TITLE
[NetCDF_jll] cannot open shared object file libmbedtls.so.13

### ISSUE THREAD

**Issue by tcarion** [JuliaPackaging/Yggdrasil#5054]
Hi all,

Precompilation of NetCDF_jll fails on julia 1.7.3 (I also tried on 1.8.0-rc1 and get the same error):
```julia
julia> using NetCDF_jll
ERROR: InitError: could not load library "/home/tcarion/.julia/artifacts/0a7f440ba143b238cc3dd0def2956d34d76755f3/lib/libnetcdf.so"
libmbedtls.so.13: cannot open shared object file: No such file or directory
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
 [2] __init__()
   @ NetCDF_jll ~/.julia/packages/NetCDF_jll/xjKDT/src/wrappers/x86_64-linux-gnu.jl:14
during initialization of module NetCDF_jll

julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

When I try on another machine with another linux distro, it works just fine:
```julia
julia> using NetCDF_jll

julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, broadwell)
```

Also, when using julia 1.6.5, it works fine on both machines.

It seems related to #2401, but I don't understand what exactly is happening here.

Thank you in advance for your help!

**Comment by giordano** [comment]
How did you install Julia?  What's the value of `LD_LIBRARY_PAHT`?  I'm 99.9% sure you're picking up a wrong libmbedtls, because Julia v1.7.3 ships `libmbedtls.so.13` (and so very inclined to close this issue).

**Comment by giordano** [comment]
@nalimilan this looks to be a Fedora build, could you please take a look?  I can't, since this doesn't happen in the official release, so I'm going to close this.

**Comment by tcarion** [comment]
@giordano Thank you for your help!

**Comment by nalimilan** [comment]
See https://github.com/Alexander-Barth/NCDatasets.jl/issues/126 (also https://github.com/JuliaGeo/NetCDF.jl/issues/144 on Arch). I don't have a good solution, given that mbedTLS bumps the SOVERSION all the time without any reasonable release policy.
