### ISSUE TITLE
Build Coin-OR and JuMP solvers

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#509]
To address https://github.com/JuliaOpt/Clp.jl/issues/73. CC@ @Yuya-Furusawa @juan-pablo-vielma

The [original builder](https://github.com/JuliaOpt/ClpBuilder/blob/c6d371efbd508f17d1f985adcb65aec85a9bdef4/build_tarballs.jl) mixes several packages in a single builder:
* [x] clp
* [x] osi
* [x] coinutils
* [x] ASL

Note by @ViralBShah: I updated this issue for Coin-OR libraries and solvers JuMP needs:
* [x] cbc
* [x] glpk
* [x] scs
* [x] ipopt
* [x] ecos
* [ ] sdpa
* [x] csdp

Instead of CoinBLAS and CoinLAPACK, we want to link CoinUtils etc. to Julia's openblas (#544), which may need some patching for 64-bit indices. Similarly for CoinMetis and CoinMUMPS, we want to be able to link to the libraries we build as JLLs here.

**Comment by giordano** [comment]
Ok, let's start with the first issue.  We already have a builder for a package called [ASL](https://github.com/JuliaPackaging/Yggdrasil/blob/dfc5d9580b5eee0dca7f52621e9a3b7e9478c13e/A/ASL/build_tarballs.jl).  @juan-pablo-vielma could you please confirm it's the same thing?

**Comment by dpo** [comment]
Yes it's the same thing. You can also eliminate COINLapack and COINBLAS and replace them with OpenBLAS_jll. COINMetis can be replaced with METIS_jll. I'm working on MUMPS as time allows.

**Comment by giordano** [comment]
> You can also eliminate COINLapack and COINBLAS and replace them with OpenBLAS_jll.

Oh, good to know that COINBLAS was a complete waste of time. Was fun patching a dead project

**Comment by dpo** [comment]
I'm not saying COINBLAS, etc., are dead projects. But COINBLAS and COINLapack will install generic (i.e., non optimized) BLAS/Lapack libraries and you're almost certainly better off with the somewhat optimized OpenBLAS (which ships both).

**Comment by giordano** [comment]
> I'm not saying COINBLAS, etc., are dead projects.

The maintainer of the project that closed my issue asking to fix the configure script told me so :slightly_smiling_face:

**Comment by dpo** [comment]
Ah ok. I've never used them for the reason above. I didn't know. Sorry you spent time on it.

**Comment by ViralBShah** [comment]
Is it possible to get COINMetis updated to use METIS 5?

**Comment by dpo** [comment]
What for though? There's already the METIS builder here, which builds METIS 5.

**Comment by ViralBShah** [comment]
Ah - I see. I thought COINMetis had a dependency on METIS 4 perhaps. Sorry about the noise.

**Comment by dpo** [comment]
As far as I can tell, it only builds METIS 4. But #530 should make it unnecessary.

**Comment by ViralBShah** [comment]
The problem we will face is that METIS 5 will start shipping with SuiteSparse in Julia base. My worry is that any use of METIS 4 will then conflict with SuiteSparse.

**Comment by giordano** [comment]
> My worry is that any use of METIS 4 will then conflict with SuiteSparse.

That's very true :confused:

**Comment by ViralBShah** [comment]
I wonder if METIS 4 can be built into clp directly. That might work fine.

**Comment by dpo** [comment]
We need METIS 4 for other packages than CLP though. This is the case of any application that uses SuiteSparse, and not just Julia, right? How is the situation different here than anywhere else? A user should be able to use METIS 4 if they need it.

**Comment by ViralBShah** [comment]
I am guessing it would work if you don't use SuiteSparse in the application. Do we know if the two libraries have the same APIs or global state? If they won't stomp on each other, may be we can get away with simultaneously shipping two versions.

**Comment by ViralBShah** [comment]
Actually, I don't think we have any other case where we have two versions of the same library in simultaneous use. Usually it is part of a transition - where older releases of a julia package use the older version of a library, and newer releases of that package use a newer version.

**Comment by dpo** [comment]
Wouldn't this be a good case for renaming the METIS 5 symbols inside SuiteSparse?

**Comment by ViralBShah** [comment]
I would have thought that more packages will adopt METIS 5 given its improvements and how old METIS 4 is. At that point we'd have to then make changes in every package that uses METIS 5. We would also have to update METIS.jl (which is much easier to do). 

I wonder if @fredrikekre knows about the APIs of both versions to say if they can co-exist.

**Comment by ViralBShah** [comment]
The METIS manual has quite a bit of information on the differences between the 2 versions: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/manual.pdf

**Comment by ericphanson** [comment]
If Clp gets built, maybe it'll be easy to build SDPA too, since they share a lot of the dependencies (https://github.com/JuliaOpt/SDPABuilder/blob/master/build_tarballs.jl).

**Comment by giordano** [comment]
I think I'll give up, all these packages have super broken build systems

**Comment by ViralBShah** [comment]
Yeah, many of these packages have really weird build systems.

**Comment by odow** [comment]
FWIW, the COIN build system is exceedingly difficult to work with. We bundled everything together to avoid this dependency mess. It's not the best solution, but it works.

**Comment by ViralBShah** [comment]
> FWIW, the COIN build system is exceedingly difficult to work with. We bundled everything together to avoid this dependency mess. It's not the best solution, but it works.

That is definitely experience speaking!

**Comment by ViralBShah** [comment]
@mlubin Moving the discussion here. 

Basically, BinaryBuilder is staying as it is. We used to have old builders in project specific repos. Those are now centralized into https://github.com/JuliaPackaging/Yggdrasil and the CI system builds all the architectures and registers the produced binaries as artifacts. For example, Clp binaries would be uploaded as the `Clp_jll.jl` Julia package. Basically, BinaryProvider and `deps/build.jl` goes away, and you then add a dependency for `Clp_jll` in the Julia package that needs to ccall that library.

While this issue is specifically for Clp, perhaps we should use it to discuss all the various JuMP dependencies?

**Comment by ViralBShah** [comment]
@odow In response to your message in https://github.com/JuliaPackaging/Yggdrasil/issues/653#issuecomment-605465844, the current BinaryProvider stuff will keep working for a while. The artifacts system does provide lot of benefits in terms of simplifying the user experience.

I suspect it should be possible to take the monolithic builders as they are and move them to the artifacts system.  Are the monolithic pieces in the ClpBuilder only used within Clp or do we need to reuse them elsewhere? I'm happy to help out as much as I can.

**Comment by giordano** [comment]
The problem of the monolithic builder of Clp is also that it uses static libraries in several places, hiding a lot of complexity.

Having a monolithic builder is very bad under many aspects:
* increases code/library duplication reducing possibility of reusing the same library in other contexts
* updating a single component requires updating the entire monolithic package

We followed the route of a monolithic builder for Xorg, it turned out to be extremely wrong: #92.

**Comment by ViralBShah** [comment]
I'll give Clp a shot without being monolithic just to see what it takes.

**Comment by juan-pablo-vielma** [comment]
Sorry for the long absence. I am trying to catch up now. 
Anything besides this thread I could read concerning the new Yggdrasil system. 

Originally we started having separate builders for each dependency as in:
https://github.com/JuliaOpt/ClpBuilder/blob/v1.16.11-1/build_tarballs.jl

However, we had several issues with the pre `jll` system so we made the monolithic builds as a temporary solution awaiting the `jll` system. Let me find my notes about this to be more precise and please feel free to point me to the any updated docs as I have not looked at BB/BP in a while. 

If I recall correctly the main issue was with multiple versions of the dependencies. 
For instance, we could have two solvers (lets say Clp and Cbc) that used different versions of some dependencies (lets say Osi or Metis). This was easily handled in the BinaryBuilder side in the builder above by picking the right dependency versions here: https://github.com/JuliaOpt/ClpBuilder/blob/e4d035b8b1d134e4a092370a570fe68e383b43fe/build_tarballs.jl#L73-L81

For the  BinaryProvider side we handled with something like the following in the `build/.jl`:
https://github.com/JuliaOpt/Clp.jl/blob/4a91647739db12cfecce9a5566b2eae7342e0ecf/deps/build.jl#L44-L47

This worked relatively ok if we had a single solver or if all solvers used the same versions for the dependencies. However, it was not clear what happened if we had two solvers with incompatible dependency versions: e.g. it was never clear to me if there could be a symbol clash. Hence, the static linking and the symbol hiding (e.g. https://github.com/JuliaOpt/ClpBuilder/blob/c6d371efbd508f17d1f985adcb65aec85a9bdef4/build_tarballs.jl#L277-L284) to avoid this. 

I assume the automatic install of the correct versions for "binary" dependency now works similar to "pure-julia" dependences (which is one of the things we were waiting for). How about the symbol clash issue? Would it be possible to use Clp and Cbc at the same time even if they require different versions of some of their binary dependencies?

**Comment by juan-pablo-vielma** [comment]
@ViralBShah Ok, took a quick look at the docs pointed out from https://github.com/JuliaPackaging/Yggdrasil and I think the only "serious" potential issue with the non-monolithic builds are the possible symbol clashes when multiple versions of the same `JLL` package are loaded. I am not sufficiently familiar with `dlopen`/`ccall` and dynamic libraries in general to know if this is really safe or potentially serious issue, but two questions come to mind:
1) **A Julia-side question:** if two packages use two different versions of Clp.jl (that use different versions of Clp_jll.jl), could there be a name clash in a `ccall` to the two versions of `libClp`? I think this may be ok in a call of the form `ccall(($f,libClp), $(args...))` because `:libClp` would point to the correct library in each case, correct?
2)**A dynamic library question:** if we are using two solvers (e.g. Clp.jl and Cbc.jl) and their binary artifacts (e.g. Clp_jll and Cbc_jll) depend on different versions of another dependency (e.g. Metis_jll). Could there be a symbol clash when the non-julia-code dynamic libraries (e.g. libClp.so and libCbc.so) call the non-julia-code dynamic library dependency (e.g. Metis.so)?

**Comment by giordano** [comment]
> when multiple versions of the same JLL package are loaded. I

There can't be multiple versions of the same JLL package loaded at the same time.  They're regular Julia packages, you can't have the same package in multiple versions in a given environment

**Comment by juan-pablo-vielma** [comment]
@ViralBShah If there is no issue with the questions above I think getting a non-monolithic build for Clp based on https://github.com/JuliaOpt/ClpBuilder/blob/v1.16.11-1/build_tarballs.jl should not be too difficult. You'll see that all the dependencies listed at the end have BB packages (looks like CoinUtils and Osi may be the only ones that need to be added before Clp). I will probably have a limited bandwidth to experiment with this, but let me know if you get stuck on the BB side of things.

**Comment by ViralBShah** [comment]
@juan-pablo-vielma Thanks. If different solvers need different versions of the same library, then those should be statically linked, which is what you are doing now. But things like BLAS and LAPACK probably can be linked to the Julia provided ones. As @giordano says, we certainly can't have two versions of the same library, as that will create all sorts of problems.

**Comment by ViralBShah** [comment]
I imagine Clp, Cbc, and Ipopt are the real difficult ones, but GLPK would be an easy one.

**Comment by juan-pablo-vielma** [comment]
I see, I thought I had heard you could use sub/stacked environments to hide dependencies (at least for pure-julia packages). 

Then a hybrid approach may be the best: try to make as many of the dependencies `jll`s and make them static again if/when needed (e.g. if a solver does not get updated and is dependent on a stale `jll`). 

I think a good order to add try to update would be:
1) ECOS.jl / ECOSBuilder: no-dependencies
2) SCS.jl / SCSBuilder: only depends on blas
3) GLPK.jl / GLPKBuilder: only depends on GMP

I expect all those should be straightforward to update for someone familiar with the new system. Again, happy help if there is something unclear with the current system. 

After testing those in the wild for a bit, maybe some brave soul can try to update all the COIN-OR solvers at the same time :-) I think the static linking could be completely avoided if these keep being updated at the same time.

**Comment by ViralBShah** [comment]
It might be a bit late, but perhaps we should try finding a GSoC student to upgrade JuMP BB packages?

**Comment by dpo** [comment]
I'm working on and off on IPOPT. I got MUMPS/MPI going. It should be easy to build MUMPS serial, and hopefully, IPOPT will follow.

**Comment by ViralBShah** [comment]
GLPK: https://github.com/JuliaPackaging/Yggdrasil/pull/671

**Comment by ViralBShah** [comment]
@juan-pablo-vielma It looks like CoinUtils is where the dispatch to BLAS happens, and we don't want to use CoinBLAS and CoinLAPACK. However, if we want to use OpenBLAS in Julia, we need to patch the library to do 64-bit BLAS and LAPACK. The code looks well structured, but I just wanted to check with you in case you have attempted it before, or if it is not a good idea.

**Comment by odow** [comment]
So I have a build of GLPK working: https://github.com/JuliaOpt/GLPK.jl/pull/130.

One thing that isn't clear to me: how are we supposed to continue to support Julia 1.0? Can Project.toml be conditional on the Julia version?

**Comment by ViralBShah** [comment]
Sorry - I merged GLPK yesterday. I thought I posted it in here.

**Comment by odow** [comment]
Yes, I meant I updated the package to use the .jll you created :)

**Comment by ViralBShah** [comment]
Yes, I realized it later, and deleted my comment. :-)

I believe what will happen is that for Julia 1.0, it will keep pulling the BinaryProvider versions. But for 1.3 and higher, it will use the new JLLs.

**Comment by odow** [comment]
Ah. This comment helped: https://github.com/JuliaBinaryWrappers/GLPK_jll.jl/blob/b63b263352d818fc6b96a668ab30b32c444588bb/src/GLPK_jll.jl#L4-L18
I'll implement that.

It's our preference to continue to support Julia 1.0 for the latest version of JuMP and related packages. One selling point of Julia 1.0 was that users wouldn't have to update for a long time. A Julia 1.5 LTS feels more like Julia 2.0 if there is going to be a strong pre-/post-Julia 1.5 support in packages.

**Comment by ViralBShah** [comment]
The thing is that with multi-threading and artifacts in 1.3, some packages are already lower bounding on 1.3.  A 1.5 LTS will obviously not be a breaking change in the language, but perhaps the pros and cons of that should be discussed elsewhere. In any case, supporting old way of getting binaries and new ones should be possible to support as you noted, so that you don't drop 1.0 support for JuMP releases.

**Comment by odow** [comment]
I'm super happy with this, and I now understand the push toward artifacts. The fact that we had binary version issues with both GLPK (4.64 v 4.65) and ECOS (2.0.5 v 2.0.7) demonstrates the need to use the artifact system.

We also have good work-arounds for continuing to support binary provider on Julia 1.0.

Kudos on the great design.

**Comment by ViralBShah** [comment]
Thanks @odow for quickly integrating these. It's great to see all the tests passing. For other packages, I am picking the exact versions that @juan-pablo-vielma had packaged.

**Comment by odow** [comment]
I can't offer much building help, but if you get the COIN solvers building, tag me in the PRs and I'll integrate them into the packages.

**Comment by ViralBShah** [comment]
We have coinutils and osi registered now. @dpo Is the existing Mumps_jll package good enough? It depends on MPI, but do we need a sequential mumps package for Clp? 

We almost have all the underlying things built to attempt a Clp build, and then test it out - which is when we'll really know what is broken.

@odow Is there a way to test out if the `CoinUtils_jll` and the `Osi_jll` packages are correctly built, or will that only be through testing `Clp` itself?

**Comment by ViralBShah** [comment]
Do we need SDPA as well?

**Comment by dpo** [comment]
I'm working on a sequential MUMPS as we speak. However, I'm planning to build IPOPT without relying on the COIN infrastructure. I asked on Slack but it's late. Is the best strategy to define a new package called, say, `MUMPS_seq`? Clearly a Julia project can't import both `MUMPS` and `MUMPS_seq`.

**Comment by ViralBShah** [comment]
Yes, I think we want `MUMPS_seq`. Although I suspect you could even use both in the same Julia process.

**Comment by dpo** [comment]
Wouldn't the shared libs conflict?

**Comment by ViralBShah** [comment]
I just recently learnt that it should be ok. That is why we have openblas32 now.

**Comment by giordano** [comment]
The two different openblas have different sonames: openblas32 always uses `libopenblas`, Julia's openblas uses `libopenblas` for ilp32 and `libopenblas_` for ilp64, this is why they can coexist

**Comment by odow** [comment]
@ViralBShah I'm not sure how to test them. I think the main problem was linking them into Clp correctly.

**Comment by ViralBShah** [comment]
I have a first build for Clp now (#718). I am using the ASL_jll.jl that is packaged from netlib that was already available. For everything else, I am using the same versions as JuMP is currently using. MUMPS is not linked in yet.

@odow If you could have a PR to use the new `Clp_jll`, I would love to learn how far we can get, and then fix up the build incrementally from there. If all is good, I can then add MUMPS support as well, although another possibility is that we can try to move to Clp 1.17, which can use SuiteSparse.

For now, I'd just like to know if even a few things work.  :-)

**Comment by dpo** [comment]
MUMPS_seq_jll is ready to be tested in #713.

**Comment by ViralBShah** [comment]
@dpo would you know if mumps 5 is API compatible with mumps 4?

**Comment by dpo** [comment]
I don't know.

**Comment by odow** [comment]
I have a PR for Clp: https://github.com/JuliaOpt/Clp.jl/pull/77. Can confirm that it is passing all tests on 
```Julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Outstanding work.

**Comment by ViralBShah** [comment]
Wow that was a bit unexpected! Do we not need the sparse solver to be plugged into Clp?

**Comment by odow** [comment]
I guess there is a non-sparse fallback somewhere? All tests pass on the PR across all platforms.

The tests are all very small problems. So we won't notice any performance issues. 

On a larger instance (linked to in https://github.com/JuliaOpt/Clp.jl/issues/53 about testing the LAPACK fallback), the Clp_jll takes 70 seconds, compared to 27 seconds for the BinaryBuilder version.

**Comment by mlubin** [comment]
Based on my experience from 10 years ago, Clp doesn't use MUMPS. It has its own sparse linear algebra implemented in CoinUtils.

**Comment by ViralBShah** [comment]
Huh - why does it then offer to link to mumps in the build? I would imagine it would be faster if you use external solvers. In Clp 1.17, they are also offering the ability to use suitesparse.

**Comment by ViralBShah** [comment]
@mlubin @odow are there large benchmark problems sense and sparse I can easily try to see if the external direct linear solvers help? If it does in experiments, I can provide the BB updates.

**Comment by mlubin** [comment]
No idea. Maybe it's for Clp's barrier code (that's mostly unused).

The standard benchmark instances to run are at http://plato.asu.edu/ftp/lpsimp.html.

**Comment by odow** [comment]
Here's the script I used before:

```Julia
using Clp
const MOI = Clp.MOI
download(
    "ftp://ftp.numerical.rl.ac.uk/pub/cuter/netlib/QAP12.SIF",
    "QAP12.mps"
)
mps = MOI.FileFormats.MPS.Model()
MOI.read_from_file(mps, "QAP12.mps")
model = Clp.Optimizer()
MOI.copy_to(model, mps)
MOI.optimize!(model)
```


```
Clp0000I Optimal - objective value 522.89435
Clp0032I Optimal objective 522.8943506 - 25514 iterations time 28.962

julia> 

(clp) pkg> st
    Status `/private/tmp/clp/Project.toml`
  [e2554f3b] Clp v0.7.1
```

Compared to
```
Clp0000I Optimal - objective value 522.89435
Clp0032I Optimal objective 522.8943506 - 25951 iterations time 66.952

(clp2) pkg> st
    Status `/private/tmp/clp2/Project.toml`
  [e2554f3b] Clp v0.7.1 #od/jll (https://github.com/JuliaOpt/Clp.jl.git)
```

**Comment by odow** [comment]
Yes, which I take to mean that Juan-Pablo's BinaryBuilder version of Clp (v0.7.1) is using mumps.

**Comment by ViralBShah** [comment]
I have the first binaries for Cbc as well. You'll have to update Clp_jll to 1.17.5 as well (I hope it works). Basically Clp and Cbc were using different versions of the Coin-OR dependencies, and we want to use a consistent set across all Coin-OR solvers. 

Can you let me know how Clp 1.17.5 does? And if Cbc 2.10.3 works? None of these are using Mumps just yet, but once we have the basic set up all working, I'll add Mumps across the board.

**Comment by ViralBShah** [comment]
@dpo Note I am cosolidating all the Coin-OR solvers in one place: https://github.com/JuliaPackaging/Yggdrasil/pull/775

**Comment by odow** [comment]
@ViralBShah: can confirm that Clp_jll 1.17.5 passes tests locally (Mac). I've updated the PR.

I can also confirm that Cbc 2.10.5 passes tests locally. Here's the PR: https://github.com/JuliaOpt/Cbc.jl/pull/133

Now to see how it does on Windows and linux...

**Comment by ViralBShah** [comment]
That's comforting!

**Comment by odow** [comment]
Spoke too soon. Clp errors on linux: https://travis-ci.org/github/JuliaOpt/Clp.jl/jobs/671375887#L307 (Fine on Mac though.)

**Comment by ViralBShah** [comment]
Seems like the tests all pass, but there's a crash afterwards.

**Comment by ViralBShah** [comment]
Does it happen on Julia 1.4 too?

**Comment by odow** [comment]
Yes, identical failure: https://travis-ci.org/github/JuliaOpt/Clp.jl/jobs/671375888

The first block of tests pass, but there is still a second `@testset` that didn't finish running:
https://github.com/JuliaOpt/Clp.jl/blob/c6121a52c6c980afa231d88944b71d90884494c0/test/runtests.jl#L6-L12

**Comment by ViralBShah** [comment]
Is it possible to do `ENV["OPENBLAS_NUM_THREADS"]=1` before running the tests?

**Comment by blegat** [comment]
Another Coin-OR solver used in JuMP is CSDP: https://github.com/JuliaOpt/CSDP.jl
It is currently not working for windows so switching to a jll might be a noticeable improvements for windows users.

**Comment by ViralBShah** [comment]
@dpo has now published `Ipopt`. So that's one more! I will also enable Mumps.

**Comment by amontoison** [comment]
@blegat, @odow CSDP builder is working on all platforms.
https://github.com/JuliaPackaging/Yggdrasil/pull/795

**Comment by blegat** [comment]
@amontoison Thank you so much ! Would it be possible to build the version of CSDP of this PR:
https://github.com/coin-or/Csdp/pull/12
The CSDP.jl Julia wrapper uses this version but the CSDP maintainers have not merged it yet upstream.

**Comment by ViralBShah** [comment]
I feel comfortable closing this one. There'll still be issues to work through in individual packages, but by and large I feel we are in a good place.
