### ISSUE TITLE
Boost artifacts missing for aarch64-apple-* and armv6l-*

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#5141]
I notice that the Boost artifacts for the architectures aarch64-apple-* and armv6l-* are missing.

I don't think there is a good reason for that. A few local tests show that these artifacts for these architectures can probably all be built without problems.

The package CryptoMiniSat depends on Boost. To make this package build, I have to exclude these architectures.

**Comment by giordano** [comment]
Uh: https://github.com/JuliaBinaryWrappers/boost_jll.jl/blob/631b46f63e6504c84f45ab280e7427a0471fb900/README.md#platforms?  Are you looking at an old version?  Note that Boost breaks the ABI in every single release.

**Comment by eschnett** [comment]
I looked at the error messages in Azure. These errors said that "there is no artifact (?) for this architecture provided by boost_jll".
