### ISSUE TITLE
BinaryBuilder chooses wrong MPItrampoline (?)

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#5176]
I am seeing this error (see https://github.com/JuliaPackaging/Yggdrasil/pull/5168):

```
sandbox:${WORKSPACE}/srcdir/MSTM/code # mpifort
/workspace/destdir/bin/mpifort: exec: line 78: /opt/bin/i686-linux-gnu-libgfortran3-cxx03-mpi+mpitrampoline/i686-linux-gnu-gfortran: not found
sandbox:${WORKSPACE}/srcdir/MSTM/code # ls -l /opt/bin/i686-linux-gnu-libgfortran3-cxx*-mpi+mpitrampoline/i686-linux-gnu-gfortran
-rwxrwxr-x    1 root     root          1405 Jul 18 20:39 /opt/bin/i686-linux-gnu-libgfortran3-cxx11-mpi+mpitrampoline/i686-linux-gnu-gfortran
```

Note that `mpifort` from MPItrampoline looks for `gfortran` in `cxx03`, whereas it is installed in `cxx11`.

Does this mean that BinaryBuilder chooses an `MPItrampoline_jll` built for `cxx11` when one for `cxx03` is needed?

I checked the `build` directory of the Sandbox, and this seems to be so:
- MPItrampoline is installed into the directory `i686-linux-gnu-libgfortran3-cxx11-mpi+mpitrampoline`
- The file `mpifort` therein is calling `/opt/bin/i686-linux-gnu-libgfortran3-cxx03-mpi+mpitrampoline/i686-linux-gnu-gfortran`

**Comment by vchuravy** [comment]
cc: @staticfloat @giordano

**Comment by giordano** [comment]
> The file `mpifort` therein is calling `/opt/bin/i686-linux-gnu-libgfortran3-cxx03-mpi+mpitrampoline/i686-linux-gnu-gfortran`

Does this mean there is a hard-coded compile-time path?

**Comment by eschnett** [comment]
MPITrampoline captures the C, C++, and Fortran compilers that are used to build it, and uses these when `mpicc` etc. are called. This can be overridden via environment variables.

The compilers are captured with their full path. This is the path I am seeing in `mpifort`.

**Comment by eschnett** [comment]
@giordano Are hard-coded compile-time paths bad?

**Comment by giordano** [comment]
Yes, because the compiler toolchain is in a path which depends on the exact platform triplet, which may very well be different for different packages

**Comment by eschnett** [comment]
Is it possible to set environment variables in `MPItrampoline_jll` that are then available in all its dependencies?

**Comment by giordano** [comment]
Are you talking about environment variables to be used during the build? If so, the answer is no, but in practice you can save a shell script to be sourced by downstream packages. But is it necessary to use these full absolute paths? Can't it refer to `gfortran` by just its name (or `FC` environment variable), which would always work?

**Comment by eschnett** [comment]
I'm now setting the respective environment variables directly in the build script.
