### ISSUE TITLE
ADIOS2_jll hard-codes MPItrampoline dylib version

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#5194]
I encounter this error on macOS:
```
julia> using ADIOS2
[ Info: Precompiling ADIOS2 [e0ce9d3b-0dbd-416f-8264-ccca772f60ec]
ERROR: LoadError: InitError: could not load library "/Users/eschnett/.julia/artifacts/864350d9d0153126baee156589fb1216cbf07098/lib/libadios2_c_mpi.2.8.2.dylib"
dlopen(/Users/eschnett/.julia/artifacts/864350d9d0153126baee156589fb1216cbf07098/lib/libadios2_c_mpi.2.8.2.dylib, 0x0001): Library not loaded: @rpath/libmpitrampoline.4.1.1.dylib
  Referenced from: /Users/eschnett/.julia/artifacts/864350d9d0153126baee156589fb1216cbf07098/lib/libadios2_c_mpi.2.8.2.dylib
  Reason: tried: '/workspace/destdir/lib/libmpitrampoline.4.1.1.dylib' (no such file), '/Users/eschnett/.julia/artifacts/864350d9d0153126baee156589fb1216cbf07098/lib/../lib/libmpitrampoline.4.1.1.dylib' (no such file), '/workspace/destdir/lib/libmpitrampoline.4.1.1.dylib' (no such file), '/Users/eschnett/.julia/artifacts/864350d9d0153126baee156589fb1216cbf07098/lib/../lib/libmpitrampoline.4.1.1.dylib' (no such file), '/Users/eschnett/.julia/juliaup/julia-1.8.0-rc3+0~x64/lib/julia/libmpitrampoline.4.1.1.dylib' (no such file), '/Users/eschnett/.julia/juliaup/julia-1.8.0-rc3+0~x64/bin/../lib/libmpitrampoline.4.1.1.dylib' (no such file), '/usr/local/lib/libmpitrampoline.4.1.1.dylib' (no such file), '/usr/lib/libmpitrampoline.4.1.1.dylib' (no such file)
```

I assume the following happened:
- `ADIOS2_jll` was built against `MPItrampoline_jll` 4.1.1
- `ADIOS2_jll` somehow hard-coded the explicit dylib version (4.1.1) instead of using only the major version number (4)
- `MPItrampoline_jll` was then updated to version 4.2.0

Would you have a pointer where the error lies? Is this a problem with BinaryBuilder, which should not permit this? Is this a problem with ADIOS2, which shouldn't hard-code the version number? Or is this a problem with MPItrampoline?

**Comment by eschnett** [comment]
I fixed MPItrampoline (I think). How to I fix the jll packages?

My idea:
- Release a new major version of MPItrampoline
- Require this version from all build scripts

Alternatively:
- Release a new minor version of MPItrampoline (for unrelated changes)
- Manually trigger a rebuild of all build scripts that use MPItrampoline

**Comment by eschnett** [comment]
@giordano

**Comment by giordano** [comment]
I don't personally care whether you do a major or minor bump in MPITrampoline, but in any case you'll need to rebuild the dependents with the new version of the package, preferably specifying the compat bound, since that's now relevent.

**Comment by eschnett** [comment]
This has been corrected for `ADIOS2_jll`. I will open pull requests for all other packages requiring MPItrampoline.

**Comment by eschnett** [comment]
All packages have been updated.
