### ISSUE TITLE
Request: libsodium

### ISSUE THREAD

**Issue by christopher-dG** [JuliaPackaging/Yggdrasil#523]
[The very popular crypto library](https://download.libsodium.org/doc/)

I'll get to this myself eventually as I have a use case in mind for it, but in case someone wants something to do :slightly_smiling_face:

**Comment by giordano** [comment]
#516

**Comment by giordano** [comment]
Apparently everybody wants it, also @davidanthoff was interested in it

**Comment by christopher-dG** [comment]
Welp... I swear I looked for it! :sweat_smile: We're both wanting to use the GitHub repo secrets API.

**Comment by davidanthoff** [comment]
Wow, that was fast :)

**Comment by Gnimuc** [comment]
And [the wrapper is here](https://github.com/Gnimuc/Sodium.jl).
