### ISSUE TITLE
Build `ReadStat_jll` for MacOS Apple Silicon

### ISSUE THREAD

**Issue by junyuan-chen** [JuliaPackaging/Yggdrasil#5290]
Hi, I am not sure whether this is the right place to report. But, it would be really nice to see `ReadStat_jll` being available for MacOS aarch64 (and in its latest version). Thank you!

**Comment by jeremiahpslewis** [comment]
Let’s see how easy this is, test PR is here. :) https://github.com/JuliaPackaging/Yggdrasil/pull/5295

**Comment by jeremiahpslewis** [comment]
@junyuan-chen the pull request is ready to go, just need someone to merge :)

**Comment by junyuan-chen** [comment]
@jeremiahpslewis Thank you so much!
