### ISSUE TITLE
Issues with MPI and CMake

### ISSUE THREAD

**Issue by dpo** [JuliaPackaging/Yggdrasil#531]
I'm trying to build a JLL for PARMETIS. Here is my build script: https://github.com/dpo/Yggdrasil/tree/parmetis/P/PARMETIS

I tried using OpenMPI_jll but running `mpicc` results in an error saying that the `cc` compiler can't be found.

The linux builds go through with MPICH_jll, but I get a failure on macOS at the time of linking the shared library:
```
/workspace/destdir/bin/mpicc -fPIC  -DLINUX -D_FILE_OFFSET_BITS=64 -DNDEBUG -DNDEBUG2 -DHAVE_EXECINFO_H -DHAVE_GETLINE -O3  -shared -Wl,-soname,libparmetis.so -o libparmetis.so CMakeFiles/parmetis.dir/akwayfm.c.o CMakeFiles/parmetis.dir/ametis.c.o CMakeFiles/parmetis.dir/balancemylink.c.o CMakeFiles/parmetis.dir/comm.c.o CMakeFiles/parmetis.dir/csrmatch.c.o CMakeFiles/parmetis.dir/ctrl.c.o CMakeFiles/parmetis.dir/debug.c.o CMakeFiles/parmetis.dir/diffutil.c.o CMakeFiles/parmetis.dir/frename.c.o CMakeFiles/parmetis.dir/gkmetis.c.o CMakeFiles/parmetis.dir/gkmpi.c.o CMakeFiles/parmetis.dir/graph.c.o CMakeFiles/parmetis.dir/initbalance.c.o CMakeFiles/parmetis.dir/initmsection.c.o CMakeFiles/parmetis.dir/initpart.c.o CMakeFiles/parmetis.dir/kmetis.c.o CMakeFiles/parmetis.dir/kwayrefine.c.o CMakeFiles/parmetis.dir/match.c.o CMakeFiles/parmetis.dir/mdiffusion.c.o CMakeFiles/parmetis.dir/mesh.c.o CMakeFiles/parmetis.dir/mmetis.c.o CMakeFiles/parmetis.dir/move.c.o CMakeFiles/parmetis.dir/msetup.c.o CMakeFiles/parmetis.dir/node_refine.c.o CMakeFiles/parmetis.dir/ometis.c.o CMakeFiles/parmetis.dir/pspases.c.o CMakeFiles/parmetis.dir/redomylink.c.o CMakeFiles/parmetis.dir/remap.c.o CMakeFiles/parmetis.dir/renumber.c.o CMakeFiles/parmetis.dir/rmetis.c.o CMakeFiles/parmetis.dir/selectq.c.o CMakeFiles/parmetis.dir/serial.c.o CMakeFiles/parmetis.dir/stat.c.o CMakeFiles/parmetis.dir/timer.c.o CMakeFiles/parmetis.dir/util.c.o CMakeFiles/parmetis.dir/wave.c.o CMakeFiles/parmetis.dir/weird.c.o CMakeFiles/parmetis.dir/wspace.c.o CMakeFiles/parmetis.dir/xyzpart.c.o ../libmetis/libmetis.a -lm
ld: unknown option: -soname
```

Using `-soname` is incorrect on macOS. It should be `-install_name` instead. But the Makefiles are generated by CMake.

Any ideas on how to get the linker to use the correct option? I thought that was CMake's job...

**Comment by dpo** [comment]
You can see the error [here](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1698&view=logs&j=bc5557d8-6a3d-5239-4253-69c65334da00&t=7d2dac40-f79d-5011-0a3f-fcdb3442ca6c&l=509).

**Comment by giordano** [comment]
What I'd do is to read the cmake file to see ho this flag is set

**Comment by giordano** [comment]
Ok, I had a look at the setup of PARMETIS.  I was more happy before looking at it.

**Comment by dpo** [comment]
Welcome to the old world of scientific software. I didn't see anything wrong with the CMakeFiles, thought I'm not a CMake expert by any measure. The linux builds succeed and the macOS build succeeds outside of BinaryBuilder, which makes me think it's either something with the environment setup or some fallout from erroneous settings in MPICH. Unfortunately, trying to build MPICH's `build_tarballs` locally filled up my disk :-(, so I'm none the wiser.

**Comment by giordano** [comment]
The problem is that they have a `Makefile` to call `cmake`.  However, this brilliant `Makefile` doesn't allow passing custom extra arguments, but we need to set the toolchain file, as explained in the [documentation](https://juliapackaging.github.io/BinaryBuilder.jl/dev/build_tips/#CMake-builds-1).

I'm trying to bypass the useless `Makefile` and call `cmake` directly.

**Comment by giordano** [comment]
Done in https://github.com/JuliaPackaging/Yggdrasil/commit/f0cc5735a4408ae224fa6d936a89fe0af40f6d01
