### ISSUE TITLE
mpicc and MPITrampoline_jll

### ISSUE THREAD

**Issue by amontoison** [JuliaPackaging/Yggdrasil#5332]
When we compile a package with `MPITrampoline_jll` and `libgfortran3` (https://github.com/JuliaPackaging/Yggdrasil/pull/5309), `mpicc` try to find `gcc` / `clang` in the wrong folder on some platforms.
It adds a `cxx03` in the path:
```julia
# Platform i686-linux-gnu-libgfortran3-mpi+mpitrampoline
/opt/bin/i686-linux-gnu-libgfortran3-cxx03-mpi+mpitrampoline/i686-linux-gnu-gcc

# Platform x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline
/opt/bin/x86_64-linux-gnu-libgfortran3-cxx03-mpi+mpitrampoline/x86_64-linux-gnu-gcc

# Platform aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline
/opt/bin/aarch64-linux-gnu-libgfortran3-cxx03-mpi+mpitrampoline/aarch64-linux-gnu-gcc

# Platform armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline
/opt/bin/armv6l-linux-gnueabihf-libgfortran3-cxx03-mpi+mpitrampoline/arm-linux-gnueabihf-gcc

# Platform armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline
/opt/bin/armv7l-linux-gnueabihf-libgfortran3-cxx03-mpi+mpitrampoline/arm-linux-gnueabihf-gcc

# Platform powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline
/opt/bin/powerpc64le-linux-gnu-libgfortran3-cxx03-mpi+mpitrampoline/powerpc64le-linux-gnu-gcc

# Platform x86_64-apple-darwin14-libgfortran3-mpi+mpitrampoline
/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03-mpi+mpitrampoline/x86_64-apple-darwin14-clang
```

With a `expand_cxxstring_abis(platforms)`, the problem is solved for these platforms.
However additional platforms with `libfortran4` and/or `cxx11` have the same problem (`cxx03` instead of `cxx11` in the path for instance).

**Comment by eschnett** [comment]
`MPItrampoline_jll` captures the paths to the compiler wrappers. Instead of expanding C++ ABIs, you can set environment variables that point the compiler wrappers to the actual compilers before calling `cmake` for the package:
```sh
export MPITRAMPOLINE_CC=cc
export MPITRAMPOLINE_CXX=c++
export MPITRAMPOLINE_FC=gfortran
```
See e.g. `T/TempestModel/build_tarballs.jl` where this is done.

**Comment by amontoison** [comment]
Thanks @eschnett, it works (https://github.com/JuliaPackaging/Yggdrasil/pull/5333) !
