### ISSUE TITLE
libnode cannot be cross-compiled for Windows and macOS

### ISSUE THREAD

**Issue by sunoru** [JuliaPackaging/Yggdrasil#5363]
As I commented in this old PR (https://github.com/JuliaPackaging/Yggdrasil/pull/4140#issuecomment-1050427803), the `libnode` library can only be built for Linux platforms, given the toolchains that BinaryBuilder.jl provides.

It would be really handy if Windows and macOS were also supported, but officially NodeJS only has executables. It can be compiled as shared libraries on those platforms, but not possible through cross-compilation. I am wondering if it is OK to directly use existing builds from other sources, or if I can build them myself. For example, I found some are using Github Actions to build them: https://github.com/linroid/libnode Maybe a similar approach can be used?

**Comment by Wimmerer** [comment]
There are some Yggsrasil binaries that just use pre builds from elsewhere. Especially CUDA related stuff: https://github.com/JuliaPackaging/Yggdrasil/blob/master/T/TensorRT/build_tarballs.jl

Eventually I believe the plan is to support macOS and Windows builders for those rare libraries that don't support cross compilation. But of course cross compilation is the preferred path.

**Comment by sunoru** [comment]
Thanks for the reply. If I want to do it this way, should I also change the existing building scripts for Linux platforms to downloading prebuilds?

**Comment by Wimmerer** [comment]
No probably not
