### ISSUE TITLE
Clipper v2

### ISSUE THREAD

**Issue by cormullion** [JuliaPackaging/Yggdrasil#5381]
On my quest for useful polygon tools I came across [Clipper2](https://github.com/AngusJohnson/Clipper2). This new version (1.0.3) appears to replace Clipper1, which I'm guessing is the original v6.4.2 one currently supported in Yggdrasil [here](https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/Clipper/build_tarballs.jl), and Clipper1 is no longer being maintained by the author.

Is it better to upgrade the current recipe or to add a new one? Happy to try to do something myself, but advice always welcome first!

**Comment by cormullion** [comment]
I got this far before I got an error:

```
Enter a name for this project.  This will be used for filenames:
> Clipper2

Enter a version number for this project:
> 1.0

Do you want to customize the set of compilers? [y/N]: N
			# Step 3: Build for Linux x86_64 {libc=glibc}

You will now be dropped into the cross-compilation environment.
Please compile the package. Your initial compilation target is x86_64-linux-gnu
The $prefix environment variable contains the target directory.
Once you are done, exit by typing `exit` or `^D`

You have the following contents in your working directory:
  - Clipper2
Hints:
  - Clipper2/CPP/CMakeLists.txt

    This file is likely input to CMake. The recommended options for CMake are

      cmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release

    followed by `make` and `make install`. Since the prefix environment
    variable is set already, this will automatically perform the installation
    into the correct directory.


IOError: could not spawn `docker inspect --type=image julia_binarybuilder_rootfs:v2022.4.15-e3d5d5`: no such file or directory (ENOENT)
```

But I don't know what docker is... 🤷

**Comment by aviks** [comment]
> I got this far before I got an error:

**Comment by aviks** [comment]
>I got this far before I got an error:

Presumably you are doing this on the mac? That needs [docker](https://docs.docker.com/desktop/install/mac-install/) installed on your machine. It's actually much easier doing this on a linux machine, if you have access to one.

**Comment by cormullion** [comment]
Yes, MacOS here ... I'll have a look for a Linux box...

**Comment by aviks** [comment]
I'm making some progress here.

**Comment by aviks** [comment]
Ah, OK, so the default CMake rules seem to only build a `.a` file rather than a `.so`. So this will likely need more effort

```
-- Installing: /workspace/destdir/lib/libClipper2.a
-- Installing: /workspace/destdir/lib/libClipper2Z.a
-- Installing: /workspace/destdir/include
-- Installing: /workspace/destdir/include/clipper.offset.h
-- Installing: /workspace/destdir/include/clipper.minkowski.h
-- Installing: /workspace/destdir/include/clipper.h
-- Installing: /workspace/destdir/include/clipper.engine.h
-- Installing: /workspace/destdir/include/clipper.core.h
```

**Comment by aviks** [comment]
Here you go: https://github.com/JuliaPackaging/Yggdrasil/pull/5513

**Comment by cormullion** [comment]
Hey, @aviks that's great - thanks for tackling this! I'm out of my comfort zone here... 🤣
