### ISSUE TITLE
support CoolProp on Apple M1

### ISSUE THREAD

**Issue by longemen3000** [JuliaPackaging/Yggdrasil#5468]
seems that the result binary does not include apple M1 in its dependencies. ref: https://github.com/CoolProp/CoolProp.jl/issues/20

**Comment by longemen3000** [comment]
seems that it only needs a rebuild? the version is the same, and the last commit was two weeks before the launch of apple M1

**Comment by giordano** [comment]
Did you see the pinned issue  #2763?

**Comment by longemen3000** [comment]
the mention of apple was cut short hahaha 
![image](https://user-images.githubusercontent.com/38795484/189779722-10561742-c19d-48a4-8de4-efa2056dbf4f.png)
in particular, i don't see any problems with the constraints imposed by the issue, but i will tag @barche

**Comment by longemen3000** [comment]
(i was thinking on using the standalone binary meanwhile, is that possible)

**Comment by barche** [comment]
I made a PR with 6.4.2, we'll see how it goes :)
