### ISSUE TITLE
SDL2_ttf_jll for aarch64-apple-darwin

### ISSUE THREAD

**Issue by shg** [JuliaPackaging/Yggdrasil#5481]
I'd like to have SDL2_ttf_jll for macOS Apple Silicon since GameZero.jll depends on it.

I am not familiar with Yggdrasil and wonder what I should do for this. I locally tested the existing build_tarballs.jl and it seems it generates aarch64-apple-darwin dylib without a problem.

https://github.com/aviks/GameZero.jl/issues/58

**Comment by giordano** [comment]
Judging by the commit message of https://github.com/JuliaPackaging/Yggdrasil/commit/5d5f68d5115115e06aa2b6e0e6a036a2f44c6b66 this was meant to be built for aarch64-apple-darwin, but apparently I missed to actually do it.

**Comment by shg** [comment]
Thank you very much for the quick reponse!

Actually I just found that I need SDL2_image_jll and its aarch64-apple-darwin build is also missing. However, the build script for this library seems to be out of date and does not work as is. I will make a new issue for this.
