### ISSUE TITLE
Exposing MPI interface

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/Yggdrasil#550]
Now that we have MPICH and Open MPI wrappers, the question arises : how should we build other libraries that require an MPI? 

See #420 and https://github.com/JuliaPackaging/Yggdrasil/pull/313#issuecomment-590113991

Some options:

- Pick one: MPICH will probably be the default for MPI.jl (at least on non-Windows), but this will cause problems if you want to use a cluster-provided MPI which has a different ABI. Users would then need to override all dependencies manually.

- Provide binaries built against common ABI choices: OpenMPI, MPICH and MS MPI. The main downside here is if the cluster-provides MPI doesn’t match the exact library version.

- Provide a shim layer which other MPIs can build against, and let us inject different MPIs (or even Julia’s own parallel machinery) in the backend.

**Comment by giordano** [comment]
I think also @sloede and @dpo may be interested in this discussion.

**Comment by sloede** [comment]
Since Julia is aiming for being a true alternative for HPC (at least as far as I understand), support for using an on-premises MPI installation without too much hassle is essential. Following a typical work flow, I would want to be able to test my code locally on a workstation, then a small cluster, before moving it to a production system. Thus, ideally the solution should be such that I can easily override the actual MPI implementation being used. This need would, however, extend to other libraries as well, eg purpose-built HDF5/NetCDF libs, FFTW with MPI support etc. Therefore I think ultimately the question to be asked (and answered) should include these other libraries as well. 

But focusing on MPI here: Given the HPCs community's aversion to change, I doubt that any solution that requires the cooperation of MPI vendors and/or supercomputer sysadmins will be feasible in practice, at least not before large-scale HPC applications written in Julia gain much more momentum. From a practical perspective I thus see currently only two real options:
- Provide a shim layer as suggested by @simonbyrne, given that this can be realized without having to reimplement the entire MPI API and given that it can be easily compiled on each machine by the user herself.
- Accept the fact that this problem is Really Hard and opt for supporting only the most common and freely available MPI libraries (MPICH, OpenMPI), but provide a canonical (and well documented) way for the user to override the actual implementation used on a given machine, eg through environment variables.

**Comment by staticfloat** [comment]
I think a shim layer is probably the best way to go; are the APIs similar enough that we can have a single API with multiple ABI backends that plug into the various MPI libraries that may exist on a user's machine?

**Comment by staticfloat** [comment]
I think a great first step would be to create:

* Two MPI backend implementations (I think this is already done: MPICH and OpenMPI).

* A client package and test suite that can build against both.

Then, we can experiment with creating something like `MPI_jll` that will intelligently choose which backend to use.  It can provide shim C libraries, and if we get it working well, we would then just tell all users to use `MPI_jll` as the dependency in their BB scripts and Julia libraries, then let `MPI_jll` swap out the backend as necessary to polymorph onto whatever system you're running on.

**Comment by sloede** [comment]
How would one test a client package that can be build against one or both MPI backend implementations (say, a simple parallel PDE solver), if `MPI.jl` explicitly requires `mpicc` (i.e., an external MPI installation + C compiler)? That is, if my client MPI application uses not the jll-provided library but one available on the host system?

The only thing that I see that can be tested is, e.g., another jll-wrapped C library that has an MPI backend as a binary dependency. But a true test of this approach IMHO should require that the client package _itself_ be tested against `MPI_jll`. But maybe I am missing something here, so please feel free to correct me.

**Comment by simonbyrne** [comment]
For the shim, what I was thinking was roughly we define a bunch of shell functions, e.g.
```C
extern (*MPI_Isend_ptr)(const void *buf, int count, MPI_Datatype datatype, int dest, int tag,
              MPI_Comm comm, MPI_Request * request);

int MPI_Isend(const void *buf, int count, MPI_Datatype datatype, int dest, int tag,
              MPI_Comm comm, MPI_Request * request) {
    return (*MPI_Isend_ptr)(buf, count, datatype, dest, tag, comm, request);
}
```
where we define the types (e.g.  `MPI_Comm`) and constants (`MPI_COMM_WORLD`) to match the MPICH ones (since they are they are the simplest, and don't have link-time constants).

Then for MPICH_jll (or any ABI compatible one), the `__init__` would do something like
```julia
unsafe_store!(cglobal((:MPI_Isend_ptr, libmpishim), Ptr{Cvoid}),
                  dlsym(dlopen(libmpi), :MPI_Isend))
```

For OpenMPI_jll, we would need to define something like
```julia
function MPI_Isend_wrapper(buf::Ptr{Cvoid}, count::int, mpich_datatype::MPICH_Datatype, dest::Cint, tag::Cint,
              mpich_comm::MPICH_Comm, mpich_request::Ptr{MPICH_Request})
    datatype = convert(MPI_Datatype, mpich_datatype)
    comm = conver(MPI_Comm, mpich_comm)
    ret = ccall((:MPI_Isend, ...))
    unsafe_store!(mpich_request, convert(MPICH_request, request))
    ret
end

unsafe_store!(cglobal((:MPI_Isend_ptr, libmpishim), Ptr{Cvoid}),
                  @cfunction(MPI_Isend_wrapper,Cint,(...)))
```
This obviously has some downsides:
 - it is going to be a _lot_ of boilerplate, so you would want to generate the wrapper functions
 - the `convert` methods would need to use a dictionary to store the appropriate lookups, which will have non-negligible overhead.

**Comment by staticfloat** [comment]
> we define a bunch of shell functions

Your idea of a "shell" function differs from mine. `bash` would have a hard time parsing that. ;)

> the convert methods would need to use a dictionary to store the appropriate lookups, which will have non-negligible overhead.

I would think we can metaprogram this away; we can generate the `MPI_Isend_wrapper()` methods with the knowledge of what backend we're using at compile-time, right?  There's no real reason to support runtime switching, is there?  We can stay consistent in backend choice after compilation?

Alternatively, we can use 265-style tricks, where we redefine functions and force recompilation of all dependent functions after changing the backend.  That way we can maintain runtime switchability while also generating high-performance code.  I'd be happy to help guide that effort, although I don't understand MPI well enough to know what needs to be wrapped.

**Comment by simonbyrne** [comment]
> I would think we can metaprogram this away; we can generate the `MPI_Isend_wrapper()` methods with the knowledge of what backend we're using at compile-time, right? There's no real reason to support runtime switching, is there? We can stay consistent in backend choice after compilation?

Yes: the idea is that the `MPI_Isend_wrapper` functions are per-MPI implementation, so would go in the _jll file for that implementation.

**Comment by eschnett** [comment]
The MPI API is defined by the standard and is the same for all implementations. The only problem are the constants which are defined in header files and which differ for each implementation. I don't see a need for wrapper functions. It would be necessary to have functions that return the values of the compile-time constants, and these should go into the JLL.

Example of functions to access a compile-time constant:
```
MPI_Type jl_mpi_int() { return MPI_INT; }
MPI_Op jl_mpi_op_sum() { return MPI_OP_SUM; }
```

These functions are called when `MPI.jl` is loaded, and are then known to the Julia JIT compiler.

**Comment by simonbyrne** [comment]
@eschnett This issue isn't about MPI itself, but about binaries which depend on MPI (e.g. Petsc, HDF5). I'm not sure how that would help in this case.

**Comment by simonbyrne** [comment]
After some reconsideration, I think the best solution would be to provide a mechanism where we can build against all the different MPI implementations, similar to how we handle gfortran and libcxx.

**Comment by ViralBShah** [comment]
Is the universe of MPI implementations fixed? Don't people build all kinds of specialized MPIs on their machines? Presumably you would also want the system BLAS on those machines. So, it is a cross product of #MPI implementations x #BLAS implementations (and then the cxx and libgfortran expansions).

**Comment by vchuravy** [comment]
Yeah an you get into the business of MPI implementation X with featureset {Y,T,Z}. I strongly believe that the only correct answer on supercomputers is to fall back onto the system and make that as easy as possible.

**Comment by ViralBShah** [comment]
I suppose we can close this now that we have MPITrampoline.
