### ISSUE TITLE
OpenBLAS32_jll for ARM Mac binaries missing unversioned library aliases

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/Yggdrasil#5548]
On an M1 Mac:
```
shell> ls ~/.julia/artifacts/c5444803422dfcb90ced251156d1d4e0188432d0/lib/
cmake                           libopenblas.0.3.17.dylib        pkgconfig
```

On an x86 Mac
```
shell> ls ~/.julia/artifacts/c5444803422dfcb90ced251156d1d4e0188432d0/lib
cmake                    libopenblas.0.3.17.dylib libopenblas.0.dylib      libopenblas.dylib        pkgconfig
```

The trouble is that certain binaries (TempestRemap) link against libopenblas.dylib instead of the versioned copy.

**Comment by giordano** [comment]
Seems to be a problem specific to 0.3.17, because https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.21%2B0/OpenBLAS32.v0.3.21.aarch64-apple-darwin-libgfortran5.tar.gz has the unversioned library.

**Comment by simonbyrne** [comment]
Unfortunately 0.3.17 is the latest one running on Julia 1.8

**Comment by giordano** [comment]
I'm confused though: you seem to be showing two artifacts directories with the same tree-hash?  Those should have the same content.  It's also suspicious that you have the same artifact on two different platforms

**Comment by giordano** [comment]
Specifically, `c5444803422dfcb90ced251156d1d4e0188432d0` is for x86_64-apple-darwin, not aarch64: https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/blob/163582d8734dbe892c6141c11d7cc7f39d4566a9/Artifacts.toml#L330

**Comment by simonbyrne** [comment]
Ah. I think you're right: it is actually using the x86_64 binaries under Rosetta.

The problem appears to be that the .julia directory wound up in a weird state. When I deleted and re-instantiated the files appeared.
