### ISSUE TITLE
build request: biber

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaPackaging/Yggdrasil#5633]
Biber has pretty straightforward build scripts (e.g. https://github.com/plk/biber/blob/dev/dist/darwin_arm64/build.sh), and having a biber jll would allow Tectonic.jl to not vendor its own artifacts and fix https://github.com/MichaelHatherly/Tectonic.jl/issues/13

**Comment by Roger-luo** [comment]
I tried this, this cannot be done at the moment because we need a JLL for the PAR packager first https://github.com/rschupp/PAR-Packer

**Comment by iagobaapellaniz** [comment]
Why not download the binaries from https://sourceforge.net/projects/biblatex-biber/ ?
Does it make sense at all?
