### ISSUE TITLE
Problem with CUDD_jll

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#5721]
> Julia package CUDD_jll appears to install and compile on the Apple M1 architecture. It would be very helpful to have a basic test that would (1) demonstrate that CUDD_jll really works on Apple M1 and (2) provide clues as to what the user interface is. The interface appears to differ from the older CUDD.jl user interface because the command `initialize_cudd()` isn't recognized (undefined variable). I'm particularly interested in the following commands (from the older CUDD.jl package); initialize_cudd(), as in manager = initialize_cudd(), var1 = Cudd_bddNewVar(manager), Cudd_bddNand(manager, a, a), Cudd_bddAnd(manager, a, b), Cudd_bddOr(manager, a, b). In other words, how do I initialize CUDD_jll, how do I define logical variables, and how do I define the logic primitives Not, And, Or. Any help will be appreciated.

_Originally posted by @drbuckleyjr in https://github.com/JuliaPackaging/Yggdrasil/issues/3024#issuecomment-1286290395_

**Comment by giordano** [comment]
CC: @maleadt

**Comment by maleadt** [comment]
The CU prefix is misleading here 🙂 

> CUDD stands for Colorado University Decision Diagram. It is a package for the manipulation of Binary Decision Diagrams (BDDs), Algebraic Decision Diagrams (ADDs) and Zero-suppressed Binary Decision Diagrams (ZDDs).

CUDD_jl was added by @MaximeBouton

**Comment by drbuckleyjr** [comment]
I am mistaken. CUDD is not compatible with the Apple M1 system. Though CUDD_jll installs and compiles, it is unable to use CUDD which will not compile.

**Comment by MaximeBouton** [comment]
Hi! Yes I added this build recipe, is there something I should update?

**Comment by drbuckleyjr** [comment]
I'm having success using Julia v1.9 on Apple M1. I add CUDD and then try to run Julia code that uses CUDD. When I do a first include("my_code.jl") I get an error message ERROR: LoadError: InitError: cfunction: closures are not supported on this platform. Then, without doing anything else, I do a second include("my_code.jl") and all works well from that point on.

**Comment by drbuckleyjr** [comment]
An easier way to provoke the problem with Julia v1.9 on M1 using CUDD. Once CUDD has been added to Julia, start Julia and invoke "using CUDD". The first time you do this you'll get the ERROR about closures not being supported. Invoke "using CUDD" a second time and all will be well. You don't have to rely on user code.

**Comment by giordano** [comment]
My understanding is that there is nothing wrong (or nothing proven to be wrong) with the binary library offered by `CUDD_jll` on the M1 (I can load the package just fine) and your problems stem from the fact the package [`CUDD.jl`](https://github.com/sisl/CUDD.jl) (which has nothing to do with this repository) uses cfunctions with closures which don't work on ARM architecture because of a limitation of LLVM itself (or how Julia uses LLVM to generate cfunctions with closures: trampolines aren't supported by LLVM on that architecture).

If so, I'd close this issue and you can continue the discussion in `CUDD.jl`, there is nothing we can do about your problems here.

**Comment by giordano** [comment]
Closing in favour of https://github.com/sisl/CUDD.jl/issues/23
