### ISSUE TITLE
[libcleri] dlopen could not load library on macOS Ventura

### ISSUE THREAD

**Issue by jamesgardner1421** [JuliaPackaging/Yggdrasil#5771]
I've just updated macOS and have run into this error:
```julia
julia> using ExtXYZ
[ Info: Precompiling ExtXYZ [352459e4-ddd7-4360-8937-99dcb397b478]
ERROR: LoadError: InitError: could not load library "/Users/jamesgardner/.julia/artifacts/675b083c4c5c7547b978df01a0238c65a0d09aef/lib/libcleri.dylib"
dlopen(/Users/jamesgardner/.julia/artifacts/675b083c4c5c7547b978df01a0238c65a0d09aef/lib/libcleri.dylib, 0x0001): Library not loaded: /workspace/destdir/x86_64-apple-darwin14/lib/libgcc_s.1.dylib
  Referenced from: <055957C4-7BD0-3633-B879-8874D3421202> /Users/jamesgardner/.julia/artifacts/675b083c4c5c7547b978df01a0238c65a0d09aef/lib/libcleri.dylib.0.12.1
  Reason: tried: '/workspace/destdir/x86_64-apple-darwin14/lib/libgcc_s.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/workspace/destdir/x86_64-apple-darwin14/lib/libgcc_s.1.dylib' (no such file), '/workspace/destdir/x86_64-apple-darwin14/lib/libgcc_s.1.dylib' (no such file)
```
Is this an RPATH related issue similar to #3703? The [build script](https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/libcleri/build_tarballs.jl) seems relatively simple but I don't know enough to try to fix it.

**Comment by giordano** [comment]
Works for me on macOS 12:
```julia
julia> using ExtXYZ

julia> versioninfo()
Julia Version 1.6.4
Commit 35f0c911f4 (2021-11-19 03:54 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, westmere)
```
(this is M1 with Rosetta, works as well also on native M1).  Did Ventura break anything? 🙄

**Comment by jamesgardner1421** [comment]
Oh, I'm on intel, with 1.8.2:
```julia
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 4 × Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 4 virtual cores
```
I haven't noticed anything else stop working so far

**Comment by giordano** [comment]
@gbaraldi reported that `libgcc_s.1.dylib` is already loaded when we start julia, so my conclusion is that macOS dynamic loader is broken on Intel machines on macOS Ventura.

**Comment by giordano** [comment]
> so my conclusion is that macOS dynamic loader is broken on Intel machines on macOS Ventura. 

For the benefit of future readers, @gbaraldi managed to create a pure C example to demonstrate the breaking change: https://github.com/gbaraldi/LinkerFailures

**Comment by ludiccc** [comment]
I have a similar problem. I'm not being able to do a precompile() on, for example, NeuralPDE or OrdinaryDiffEq, except if... :

´from a command line I run this:
export DYLD_FALLBACK_LIBRARY_PATH=/Users/****/anaconda3/envs/JuliaProject/lib/
cd /Applications/Julia-1.9.app/Contents/Resources/julia
./julia´

After this, I can do ´import Pkg; Pkg.precompile()´without having any issue.

The problem is that ´julia´is not finding the ´libgcc_s.1.dylib´ on the default locations.

**Comment by giordano** [comment]
Please open a new issue, I'm going to lock this conversation to avoid further messages here. In the new ticket please include a full error message, not including it is as useful as nothing as we have no idea what's the offending package.
