### ISSUE TITLE
CSL bundles a weird libgcc_s.1.dylib on apple-x86_64-libgfortran5

### ISSUE THREAD

**Issue by gbaraldi** [JuliaPackaging/Yggdrasil#5794]
There was a change in soname in gcc12 and I believe there is a fallback lib or something like it. `libgcc_s.1.dylib` links to `libgcc_s.1.1.dylib`, but it has a broken rpath, so it looks at `/workspace/destdir/x86_64-apple-darwin14/lib/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0, reexport)` so it doesn't find it. Which leads to failures. 

Libgfortran doesn't look for the old soname in gcc12 so I imagine we shouldn't ship it at all in this platform

**Comment by giordano** [comment]
It turned out this library is there on purpose, the only problem was the dependency being set incorrectly, fixed manually by #5799
