### ISSUE TITLE
Update SuiteSparse_jll to support the latest SS 6.0.2

### ISSUE THREAD

**Issue by mzy2240** [JuliaPackaging/Yggdrasil#5979]
Considering the version of SS has a major jump recently, it might worth to update the SuiteSparse_jll package to support the latest SS. GrapBLAS has been changed a lot since version 5.10.

**Comment by Wimmerer** [comment]
GraphBLAS isn't in that builder, but I have a patch for this I'll make a PR today

**Comment by chenrui333** [comment]
Any update on this @Wimmerer Thanks!

**Comment by ViralBShah** [comment]
Are there updates to the sparse solvers we use in Julia? GraphBLAS is built separately and can be updated on its own, IIRC.

**Comment by ViralBShah** [comment]
We have SuiteSparse 7 built now.
