### ISSUE TITLE
Provide libXt 

### ISSUE THREAD

**Issue by j-fu** [JuliaPackaging/Yggdrasil#598]
Hi, I am trying to build at least a part of vtk. It needs libXt from Xorg. Maybe someone is more experienced than myself to build that one...

**Comment by giordano** [comment]
I may have a look in the next days, but there are a lot of other dependencies to build too :weary:

**Comment by j-fu** [comment]
I understand completely. Just put it on your list, in the moment it is not urgent. I tried to set it up by myself and got stuck with other missing dependencies (libICE  and more) and had to give up due to my own constrained time. 
Thanks for all the work you already did!

**Comment by giordano** [comment]
Fixed by #603 (`Xorg_xorgproto`), #604 (`Xorg_libICE`), #605 (`Xorg_libSM`), #606 (`Xorg_libXt`)
