### ISSUE TITLE
HiGHS v1.4.0 occasionally hanging after solving simple LP on Windows

### ISSUE THREAD

**Issue by jajhall** [JuliaPackaging/Yggdrasil#5997]
With reference to https://github.com/ERGO-Code/HiGHS/issues/1044

I have an issue that occurs with the executable in 

https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.4.1%2B0/HiGHSstatic.v1.4.1.x86_64-w64-mingw32.tar.gz

when HiGHS v1.4.0 occasionally hangs after solving a simple LP.

I've verified that HiGHS reaches the penultimate line of the driver for the executable version. Suggests a memory deletion issue?

However, I can't recreate it with a local build of HiGHS v1.4.0

On Linux there is no error with valgrind

Is there a Windows expert who can help?

Being able to create the executable in the same way locally as is done in Yggdrasil might help me

**Comment by giordano** [comment]
CC @odow

**Comment by odow** [comment]
We can close this in favor of https://github.com/ERGO-Code/HiGHS/issues/1044. I don't think it's an issue with Yggdrasil, and I can make Julian a debug binary.
