### ISSUE TITLE
Update registry with the latest XM2_jll

### ISSUE THREAD

**Issue by serenity4** [JuliaPackaging/Yggdrasil#6023]
[XML2_jll](https://github.com/JuliaBinaryWrappers/XML2_jll.jl) has been updated two months ago but it seems that the tag bot did not function properly and did not submit a registration request to the General registry. Could someone with access to the JuliaBinaryWrappers organization register it manually (e.g. on [this commit](https://github.com/JuliaBinaryWrappers/XML2_jll.jl/commit/8566c1878446f608eea4257b0b9f3ddaae93aea4))?

There haven't been new releases on `libxml2` since then, otherwise I would have rebuilt it.

**Comment by giordano** [comment]
It's easier to make a dummy edit to the recipe to trigger registration again.

**Comment by giordano** [comment]
I don't know exactly what happened, https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=23476&view=logs&j=60f71599-4723-5634-6345-db90eba373e3&t=f5b3ebd9-bfa5-58e3-3d25-fb59c1f1599b did create the branch https://github.com/JuliaRegistries/General/pull/new/registrator-xml2_jll-02c8fc9c-v2.10.3+0-ebe2b50096 correctly, but `GitHub.jl` failed to create the corresponding pull request.

**Comment by serenity4** [comment]
Thanks! :)
