### ISSUE TITLE
Yggdrasil should set LLVM version suffix

### ISSUE THREAD

**Issue by yhls** [JuliaPackaging/Yggdrasil#611]
Originally introduced for FreeBSD, missing for BinaryBuilder.
JuliaLang/julia#32462
CC @vchuravy

**Comment by giordano** [comment]
I assume this will be fixed by #610?

**Comment by vchuravy** [comment]
No it won't. We need to add ` LLVM_CMAKE += -DLLVM_VERSION_SUFFIX:STRING="jl"` and the question is more if that is the right thing to do for BB.
