### ISSUE TITLE
Compile LLVM with `LLVM_USE_INTEL_JITEVENTS=1`?

### ISSUE THREAD

**Issue by crstnbr** [JuliaPackaging/Yggdrasil#616]
Came up in https://discourse.julialang.org/t/using-the-intel-vtune-profiler-with-julia/34327/.

It seems like LLVM is currently compiled without `LLVM_USE_INTEL_JITEVENTS`. Therefore, the Intel VTune Profiler doesn't work despite having build Julia itself with `USE_INTEL_JITEVENTS` (and setting `ENABLE_JITPROFILING`) as [described in the Julia docs](https://docs.julialang.org/en/latest/manual/profile/#External-Profiling-1).

Would it perhaps be possible to compile LLVM with `LLVM_USE_INTEL_JITEVENTS=1`? Would this have any side effects?

@vchuravy, do you have any idea here?

**Comment by vchuravy** [comment]
Should be fine, we still have to choose to emit them. Probably should turn on the PERF_JITEVENTS as well.

**Comment by crstnbr** [comment]
I don't feel confident adding those two flags, in particular because of all the patching business going on. I guess the relevant file is https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LLVM/common.jl? Could someone else add the appropriate lines or instruct me where/how to do it?

**Comment by mchristianl** [comment]
With the pre-built LLVM comes a log file `logs/LLVM.log` (of the pre-build-process, I guess):

```
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_INTEL_JITEVENTS
    USE_OPROFILE
    USE_PERF
```

So it seems that setting these flags already was intended, but fails. This might be because instead of `USE_INTEL_JITEVENTS` the cmake configuration expects `LLVM_USE_INTEL_JITEVENTS` ?

**Comment by mchristianl** [comment]
>  Could someone else add the appropriate lines or instruct me where/how to do it?

the typo might be in [common.jl:142-246](https://github.com/JuliaPackaging/Yggdrasil/blob/18afba6e6b240a541be08b8475dc2426207bb8f5/L/LLVM/common.jl#L142) 

```
...
    CMAKE_FLAGS+=(-DLLVM_USE_PERF=1)
    CMAKE_FLAGS+=(-DLLVM_USE_OPROFILE=1)
...
if [[ ${target} == *linux* ]] || [[ ${target} == *mingw32* ]]; then
    CMAKE_FLAGS+=(-DLLVM_USE_INTEL_JITEVENTS=1)
fi
```

**Comment by vchuravy** [comment]
Yes indeed that is just a simple typo and my intend was to build with support for those.
I am not sure that `INTEL_JITEVENTS` is supposed to work on windows.

**Comment by mchristianl** [comment]
Thank you. Will this be available for older julia versions or does this only apply to master?

E.g. in julia `v1.3.1` I have in `deps/llvm.mk`

```cmake
LLVM_BB_URL_BASE := https://github.com/JuliaPackaging/Yggdrasil/releases/download/LLVM-v$(LLVM_VER)-$(LLVM_BB_REL)
...
$(eval $(call bb-install,llvm,LLVM,true))
```

where in `deps/Versions.make` is defined

```
LLVM_VER = 6.0.1
LLVM_BB_REL = 7+nowasm
```
