### ISSUE TITLE
[OpenBLAS] CONSISTENT_FPCSR=1 for certified computation

### ISSUE THREAD

**Issue by orkolorko** [JuliaPackaging/Yggdrasil#6214]
It would be interesting to have a build of OpenBLAS with the flag 

`CONSISTENT_FPCSR = 1`

enabled, to allow use of multithreaded BLAS operations in
[IntervalLinearAlgebra](https://github.com/JuliaIntervals/IntervalLinearAlgebra.jl)

At the moment, each thread in OpenBLAS may have a different rounding mode see Issue
https://github.com/JuliaIntervals/IntervalLinearAlgebra.jl/issues/131
and this breaks the algorithms needed for the certified linear algebra computations

I open this issue mainly to understand what would be considered the best course of action and would like opinions on the following idea:

- create a new jll package, called OpenBLASConsistentFPCSR_jll
- use libblastrampoline to switch from OpenBLAS to OpenBLASConsistentFPCSR

Thank you in advance 

P.S. @lucaferranti, do you have any opinion on this?

**Comment by giordano** [comment]
Having a separate package sounds like a good idea. I'm not familiar with this option, I presume enabling it comes with a performance penalty?

**Comment by orkolorko** [comment]
By following discussions on the OpenBLAS github, the issue whether this generates performance penalty is unclear,

https://github.com/xianyi/OpenBLAS/pull/3772

As the thread pool is started, the rounding mode is set on all the threads:

https://github.com/xianyi/OpenBLAS/blob/8e851160d758d9b2bdfd61a1b19663dd4418b351/driver/others/blas_server_omp.c#L388

This should cost 1flop per thread, but probably things are more complicated; it seems even an open discussion in the OpenBLAS community whether to enable or not this option by default.

On one side, it may have some effect on performance (if it is 1flop per thread in a matrix multiplication or BLAS operation, this should be really marginal) on the other side, if for some reason the users are expecting the BLAS computation to respect some rounding mode, this can lead to non-predictable results.

**Comment by lucaferranti** [comment]
> P.S. @lucaferranti, do you have any opinion on this?

I dont have strong opinions on the two options, I presume the separate package could be easier as option? So maybe we can go with that

**Comment by orkolorko** [comment]
So, to go down the separate option package, to build OpenBLASConsistentFPCSR_jll, I think 
the process should be to fork Yggdrasil, and essentially I would copy the setup of OpenBLAS_jll substituting

https://github.com/JuliaPackaging/Yggdrasil/blob/98d5bac874b6eee1a4f10f32a2364241073c8468/O/OpenBLAS/common.jl#L86

with 
`flags=(USE_THREAD=1 GEMM_MULTITHREADING_THRESHOLD=50 NO_AFFINITY=1 CONSISTENT_FPCSR = 1)`

Is it right @giordano? It is the first time I am working with BinaryBuilder and Yggdrasil but this seems to be the process.

**Comment by giordano** [comment]
Fixed by #6215
