### ISSUE TITLE
Build failing when using GMP (libgmpxx) together with CompilerSupportLibraries

### ISSUE THREAD

**Issue by benlorenz** [JuliaPackaging/Yggdrasil#624]
I am trying to build artifacts for a autoconf based package which requires libgmpxx (`GMP_jll`) and libgomp, but `CompilerSupportLibraries_jll` seems to cause problems together with `GMP_jll`.

I have added `expand_cxxstring_abis` for the platforms and `preferred_gcc_version=v"6"` from the GMP build file. Then the build worked but I got warnings that I should add `CompilerSupportLibraries_jll` as dependency.

After adding the `CompilerSupportLibraries_jll` I get the following error:
```
checking for __gmpz_init in -lgmpxx... no
configure: error: GMP C++ library not found. Make sure it was compiled with --enable-cxx
Previous command exited with 1
```
and the config.log contains 
```
/workspace/destdir/lib/libgmpxx.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/workspace/destdir/lib/libgmpxx.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/workspace/destdir/lib/libgmpxx.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/workspace/destdir/lib/libgmpxx.so: undefined reference to `std::__cxx11::numpunct<char> const& std::use_facet<std::__cxx11::numpunct<char> >(std::locale const&)@GLIBCXX_3.4.21'
```

This seems to be caused by `artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libstdc++.so.6.0.19` which is linked into `/workspace/destdir/lib/` and older than the version 6.0.21 from /opt (via gcc 6 option). Removing all `libstdc++` from `destdir/lib` fixes the build and I guess at runtime this should not cause issues as julia ships with a more recent `libstdc++`.

Options:
1. `preferred_gcc_version=v"6"`
2. `expand_cxxstring_abis`
3. `CompilerSupportLibraries_jll`

Tested combinations:
- no options: error about `std::__cxx11::...` symbols.
- (1): warnings about `expand_cxxstring_abis` and `CompilerSupportLibraries_jll`
- (1)+(2): warning about `CompilerSupportLibraries_jll`
- (1)+(3): error about `std::__cxx11::...` symbols.
- (1)+(2)+(3): error about `std::__cxx11::` symbols.
- (2)+(3): error about `std::__cxx11::` symbols.

BinaryBuilder version: `[12aac903] BinaryBuilder v0.2.3 #master`

**Comment by giordano** [comment]
Could you please submit a PR even if it's failing?  It's easier to reason about it having the real code to play with

**Comment by benlorenz** [comment]
Ok, I will do a full build with my workaround in place first (will take a few hours) and report back later.

I just found that this could get fixed by #454.

**Comment by giordano** [comment]
> I just found that this could get fixed by #454.

Honestly, I'm not too optimistic about that PR.

**Comment by benlorenz** [comment]
Pull request in #625, failed build here: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2037&view=results

**Comment by fingolfin** [comment]
@benlorenz note that PR #454 was merged, so perhaps the workarounds can go now? (Not that it's urgent or anything, just sayin')

**Comment by aviks** [comment]
With #625 merged, this can be closed?

**Comment by benlorenz** [comment]
yes, I will remove the workaround in a new pull request soon, it seems to work without it now
