### ISSUE TITLE
Recent MbedTLS artifacts are huge

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#6338]
Older versions of MbedTLS are a few MByte large (less than 10 MB). Recent versions are huge, e.g. 377 MByte for the current version (`fc9e68415873ee933e485edb10e0eb451d726eb8`). Did the build recipe change? It now takes a significant amount of time to download this artifact.

This is on macOS.

The largest item in the artifact are the binaries in the `bin` directories. Were additional binaries added? Are they not stripped? Are they statically linked?

This change might have happened a few weeks ago. The first large artifact I have is from February 11 (`7ae07cfc2a730ea296ffb37f683b435f0c9b19ab`).

**Comment by giordano** [comment]
Are you sure you're looking at the right artifact: https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/tag/MbedTLS-v2.28.2%2B0? (the msan build is very large, but also no one should be using it)

**Comment by giordano** [comment]
That's indeed the artifact of the msan build: https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/blob/b861d6aae93d47a55fab237c53c5a96c94bb7a83/Artifacts.toml#L121. How did you get it?

**Comment by eschnett** [comment]
I was running BinaryBuilder, and I saw that this artifact was downloaded (very slowly). I don't recall exactly what I was building.

If this download is only required for BinaryBuilder then this would be fine.

**Comment by ViralBShah** [comment]
No longer seems to be an issue 

https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/tag/MbedTLS-v2.28.6%2B1
