### ISSUE TITLE
Tree Hash mismatch

### ISSUE THREAD

**Issue by DevasmitDutta** [JuliaPackaging/Yggdrasil#6344]
Hi, I am facing the following trouble in my system macOS Ventura. Any help will be appreciated
<img width="853" alt="Screenshot 2023-03-05 at 11 04 13 PM" src="https://user-images.githubusercontent.com/76597282/222976371-82f6ef5b-b272-494b-99a8-9232463eab1e.png">

**Comment by truedichotomy** [comment]
Having the exact same issue running Julia 1.9 beta 4.

```
julia> versioninfo()
Julia Version 1.9.0-beta4
Commit b75ddb787f (2023-02-07 21:53 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.3.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by giordano** [comment]
You will have to ask MPICH devs why they think having files with clashing names on case insensitive file systems is a good idea.  In the meantime: #6345
