### ISSUE TITLE
`@rpath` not resolved in MPItrampoline

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#6350]
`MPItrampoline_jll` uses `dlopen` to open the library providing the actual MPI implementation. It ships with a default implementation (MPICH) and its respective wrapper `libmpiwrapper.so`. That wrapper depends on `libgcc_s.1.dylib`, and that library is not found at run time under certain conditions.

These conditions are (probably):
- using macOS
- installing Julia via `juliaup`

```
$ otool -L /Users/eschnett/.julia/artifacts/13041af4984510184dffff7629f3be0cc9aad730/lib/libmpiwrapper.so
/Users/eschnett/.julia/artifacts/13041af4984510184dffff7629f3be0cc9aad730/lib/libmpiwrapper.so:
	@rpath/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
```

I can fix this by setting `DYLD_LIBRARY_PATH` when running Julia, as in:
```sh
env DYLD_LIBRARY_PATH=/Users/eschnett/.julia/juliaup/julia-1.9.0-beta4+0.x64.apple.darwin14/lib/julia julia
```

Do you have a suggestion for automating this? Is there, for example, some Yggdrasil magic that I could put onto the file `libmpiwrapper.so` (that is built via `BinaryBuilder`) that would update its `rpath` so that things work with the Juliaup Julia binaries?

**Comment by ViralBShah** [comment]
close?

**Comment by eschnett** [comment]
This used to be a problem on an Intel MacBook that I don't use any more. I cannot reproduce the problem on an ARM MacBook with either of Julia 1.8 ... Julia 1.11.
