### ISSUE TITLE
[FastTransforms] OpenBLAS_jll v0.3.7+8 broke dependencies?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaPackaging/Yggdrasil#641]
I suspect that due to https://github.com/JuliaPackaging/Yggdrasil/pull/632, the stripping of the `0.3.7` from the relative path is impacting dependent JLL packages (because the install_name_tool changes happen at release time rather than at load time). This means that, e.g. FastTransforms_jll v0.2.13+0 is still looking for @rpath/libopenblas64_.0.3.7.dylib even though this doesn't exist anymore.

If this is the case, can a package maintainer please rebuild FastTransforms? It seems that the same build script would be fine because the install_name_tool changes are not manual but instead automatically detected.

I think this is the cause of build failures elsewhere https://github.com/JuliaApproximation/ApproxFun.jl/commit/a4012922d746ee1c5f704e105f892dfa345a0e04

**Comment by dlfivefifty** [comment]
Can I bump this? It's causing a number of breakages

**Comment by giordano** [comment]
> can a package maintainer please rebuild FastTransforms?

You can just open a PR yourself without asking for permission: #651  :wink:

With this PR I get
```
# otool -l libfasttransforms.dylib | grep openblas
         name @rpath/libopenblas64_.dylib (offset 24)
```
With the current build I have:
```
# otool -l libfasttransforms.dylib | grep openblas
         name @rpath/libopenblas64_.0.3.7.dylib (offset 24)
```

Other builders were automatically stripping the version number of OpenBLAS to avoid issues with it.  PR #632 is meant to avoid issues for all libraries without manual intervention, but those library that didn't strip the version number now are having problems

**Comment by giordano** [comment]
Can you please try now?

**Comment by MikaelSlevinsky** [comment]
Works for me, thank you!
