### ISSUE TITLE
New release of CeresSolver_jll.jl v2.1.0 was not tagged correctly on GitHub

### ISSUE THREAD

**Issue by junyuan-chen** [JuliaPackaging/Yggdrasil#6416]
The commit associated with the `General` registry is correct. However, the Git tag associated with the GitHub release here is wrong:  https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl/releases

The default branch for https://github.com/JuliaBinaryWrappers/CeresSolver_jll.jl is somehow still `master`. The commit with the correct content shows up in a newly created `main` branch. The new GitHub release for v2.1.0 points to the v1.14.0 commit on `master`.

**Comment by giordano** [comment]
Git tags have little meanings, they don't matter for the package manager. Next release will be OK.
