### ISSUE TITLE
OpenBLAS package slimming

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPackaging/Yggdrasil#642]
Downloading big jll packages can be problematic with unreliable network connections as described in https://discourse.julialang.org/t/install-binary-package-such-as-openblas-jll-via-very-slow-internet-connection . One way to improve the situation could be trimming the size of the package.

OpenBLAS_jll could be slimmed by (I am referring to the Windows version)
- removing static libs (*.a) files in `lib`-directory 84 MB
- removing `logs/OpenBLAS.log` 5.8 MB

OpenBLAS.v0.3.7.x86_64-w64-mingw32-libgfortran5.tar.gz would go from 27 MB to 8 MB proving a speedup for downloading, and disk space would go s from 123.7 MB to 33.6 MB.

**Comment by giordano** [comment]
The log files are very important. Also, they're plain text, usually they can be compressed pretty well. Static archives are less important instead6

**Comment by davidanthoff** [comment]
If some of this stuff is important to have for the folks that build these packages, couldn't there be to archives created, one that includes things like log files, and a second one that doesn't that is actually deployed to user systems that really only has what is needed?

**Comment by haampie** [comment]
I don't really understand wher you get those numbers @jaakkor2? E.g. https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases has

```
 OpenBLAS.v0.3.7.x86_64-w64-mingw32-libgfortran3.tar.gz
26.4 MB
OpenBLAS.v0.3.7.x86_64-w64-mingw32-libgfortran4.tar.gz
26.6 MB
OpenBLAS.v0.3.7.x86_64-w64-mingw32-libgfortran5.tar.gz
26.4 MB
```

**Comment by haampie** [comment]
With #621's change locally x86_64 + libgfortran.so.4 I get 

```
lib $ du -sh ../../openblas_tmp.tar.gz 
5.2M	../../openblas_tmp.tar.gz
```

:relieved:

**Comment by jaakkor2** [comment]
Fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/621. Thanks!

`OpenBLAS.v0.3.9.x86_64-w64-mingw32-libgfortran5.tar.gz` is 8.84 MB, about 3x improvement.
