### ISSUE TITLE
OCCT build contains 8k files.

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/Yggdrasil#6437]
This seems to be ~8k include files. Feels excessive and can easily occupy a significant amount of a file quote on e.g. a cluster.

**Comment by giordano** [comment]
> Feels excessive

Complain with the developers for the ridiculously large number of header files they generate?

**Comment by KristofferC** [comment]
Do we need to bundle them all was what I was wondering

**Comment by giordano** [comment]
Header files are typically need for compiling downstream packages, so in general the answer is yes?  Splitting the header files in a separate artifact not used just for using the libraries has been proposed in https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/778
