### ISSUE TITLE
LLVM_jll v14.0.6+3 errors with llc() on Julia v1.9.0-rc2 on Ubuntu 

### ISSUE THREAD

**Issue by tshort** [JuliaPackaging/Yggdrasil#6615]
To reproduce:

```jl
using LLVM_jll
run(`$(llc()) --version`)
```
Here's the error:
```jl
/home/tshort/.julia/artifacts/d77d5fbfcf3e53b9c3803917ddda168d67bbca14/tools/llc: symbol lookup error: /home/tshort/.julia/artifacts/d77d5fbfcf3e53b9c3803917ddda168d67bbca14/tools/llc: undefined symbol: LLVMInitializeAVRTargetInfo, version JL_LLVM_14.0
```

It doesn't error on `v14.0.6+2`. It works on macOS with `v1.9.0-rc2`.

**Comment by giordano** [comment]
@vchuravy

**Comment by vchuravy** [comment]
Should be fixed when using 1.9.0, but also grrml @Seelengrab

**Comment by Seelengrab** [comment]
I did not touch Yggdrasil and was not aware there were any additional changes needed other than what @gbaraldi enabled there. I'm not familiar with what needs to be done where in the ecosystem when enabling a new backend, sorry! :bow: Happy to add the required methods though.

**Comment by vchuravy** [comment]
The Yggdrasil recipe change was also for LLVM v14 as used by 1.9
I was only expecting it for LLVM v15.

**Comment by vchuravy** [comment]
Should be fixed on `-rc3`
