### ISSUE TITLE
OpenSSL package slimming

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPackaging/Yggdrasil#668]
OpenSSL.v1.1.1.x86_64-w64-mingw32.tar.gz size is 11 MB, uncompressed on is 102.9 MB.  Slimming possibilities
* not including `share/{doc,man}` would save 86.8 MB
* not including static libs `libs/{libcrypto.a,libssl.a}` would save 5.1 MB

Compressed size would become 2.5 MB, on-disk 11 MB.

**Comment by giordano** [comment]
You're better off directly opening a pull request :wink:

**Comment by jaakkor2** [comment]
I'll give it a try this weekend.

Notes for me
* https://stackoverflow.com/questions/47136654/is-there-a-way-to-install-openssl-without-installing-man-pages `make install_sw`
* https://wiki.openssl.org/index.php/Compilation_and_Installation

**Comment by jaakkor2** [comment]
OpenSSL_jll size on disk now 15.2 MiB (Windows 10), closing the issue.
