### ISSUE TITLE
CUDA JLLs README list too few platforms

### ISSUE THREAD

**Issue by maleadt** [JuliaPackaging/Yggdrasil#6708]
CUDNN_jll is available for (CUDA 11.0, CUDA 12.0) x (linux-x86, windows-x86, linux-aarch, linux-ppc), as can be seen here: https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/tree/main/src/wrappers
The README however only lists CUDA 12 for aarch64: https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/

I guess this is because we invoke `build_platforms` multiple times? https://github.com/JuliaPackaging/Yggdrasil/blob/f53c5e6c747617ed6e847d2da7d54d61db5b8597/C/CUDNN/build_tarballs.jl#L55-L74

Is there a workaround?

**Comment by giordano** [comment]
Issue already tracked by https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/823. No workaround, but https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/639 would allow fixing it.
