### ISSUE TITLE
libsz vs. libSZ

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#6799]
There is a Julia package `libaec_jll` that provides a file `libsz.dylib` and a package `SZ_jll` which provides a file `libSZ.dylib`, and these two file names conflict on case-insensitive Darwin file systems. This problem is, via a long trail of transitive dependencies, the reason that `ADIOS2_jll` currently cannot use `HDF5_jll`.

As work-around I suggest to modify the package `libaec_jll` to not provide the library `libsz.dylib`. That library is there only for backward compatibility, and the new library name is `libaec.dylib`. We would need to modify all users of `libaec_jll` to use the new library name. (Yes, this includes `HDF5_jll`.)

@giordano @mkitti

**Comment by giordano** [comment]
How do they conflict? They shouldn't be in the same directory

**Comment by mkitti** [comment]
The libsz in libaec is supposed to emulate [SZIP](https://support.hdfgroup.org/doc_resource/SZIP/)as used by HDF5/NASA. This is a lossless compressor.

SZ represents https://szcompressor.org/ which is a lossy compression scheme.

Irritatingly both libraries are compressors and thus commonly run in the same circles.

**Comment by eschnett** [comment]
@giordano They both live in `$libdir` when building tarballs. I'm now debugging building `ADIOS2_jll` on Buildkite where this problem doesn't occur. It seems this problem exists only when using macOS as build platform.

**Comment by mkitti** [comment]
This should be an issue for Windows as well, right?

What do you mean by "building tarballs"?

**Comment by giordano** [comment]
> This should be an issue for Windows as well, right?

BinaryBuilder doesn't run on Windows at the moment
