### ISSUE TITLE
Request: build Qhull

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPackaging/Yggdrasil#685]
I'm not sure how much work this would be.  Qhull would be pretty useful for Makie to have a fast, good-looking inbuilt meshing API for vectors of points.

Documentation is at http://www.qhull.org/, and the source is also [on Github](https://github.com/qhull/qhull)

> Qhull computes the convex hull, Delaunay triangulation, Voronoi diagram, halfspace intersection about a point, furthest-site Delaunay triangulation, and furthest-site Voronoi diagram. The source code runs in 2-d, 3-d, 4-d, and higher dimensions. Qhull implements the Quickhull algorithm for computing the convex hull. It handles roundoff errors from floating point arithmetic. It computes volumes, surface areas, and approximations to the convex hull.

It seems to have detailed build instructions in the README.

**Comment by ViralBShah** [comment]
Should be reasonably straightforward.

**Comment by ViralBShah** [comment]
@asinghvi17 Do you want to give it a shot? Or recruit someone from the Makie contributors ecosystem to help out? Folks here will help sort out issues pretty quickly.

**Comment by asinghvi17** [comment]
I can try giving it a shot today.  Might not be able to build locally, though.
