### ISSUE TITLE
Error in MiniQhull

### ISSUE THREAD

**Issue by hessianguo** [JuliaPackaging/Yggdrasil#6856]
Dear all: 

Recently, I install the MiniQhullWrap  and get the following error when I test hte exam

 connectivity = delaunay(dim, numpoints, coordinates)
ERROR: QHULL WRAPPER is not properly loaded
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] macro expansion
   @ ~/.julia/packages/MiniQhull/unUAX/src/load.jl:34 [inlined]
 [3] new_qhull_handler
   @ ~/.julia/packages/MiniQhull/unUAX/src/bindings.jl:4 [inlined]
 [4] _delaunay(dim::Int32, numpoints::Int32, points::Vector{Float64})
   @ MiniQhull ~/.julia/packages/MiniQhull/unUAX/src/MiniQhull.jl:12
 [5] delaunay(dim::Int64, numpoints::Int64, points::Vector{Int64})
   @ MiniQhull ~/.julia/packages/MiniQhull/unUAX/src/MiniQhull.jl:26
 [6] top-level scope
   @ REPL[9]:1

**Comment by giordano** [comment]
Should that be reported to https://github.com/gridap/MiniQhull.jl? We don't maintain that package

**Comment by hessianguo** [comment]
Thanks.
