### ISSUE TITLE
Relax `LibCURL` version bounds

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#6857]
A few packages declare LibCURL dependencies via `Dependency("LibCURL_jll"; compat = "7.73.0")` or similar. This is too restrictive since there is no actual ABI change between versions 7 and 8 of LibCURL. These bounds should be updated to `7.73.0, 8.0.0` or similar.

**Comment by giordano** [comment]
As usual, first of all this should be fixed in the registry
