### ISSUE TITLE
Request: Add double-precision version of FastTree

### ISSUE THREAD

**Issue by murrellb** [JuliaPackaging/Yggdrasil#6895]
(I'm not 100% sure this is the right place for this request - please let me know if not).

I was delighted to see FastTree here: https://github.com/JuliaBinaryWrappers/FastTree_jll.jl

One issue is that, in many applications, we really need the version of FastTree with double-precision branch lengths. This is from their website (http://www.microbesonline.org/fasttree/):
```
Why does FastTree report so many branch lengths of 0.0005 or 0.0001, or even negative branch lengths?
By default, the maximum-likelihood phase of FastTree does not allow branch lengths of less than 0.0005, so unresolvable internal branches often end up with lengths of about 0.0005. (Before FastTree 2.1.7, the limit was 0.0001, so if you are using an older version, you may see many branch lengths of 0.0001 instead.)

If you need to resolve very-short branch lengths accurately, you can use a double-precision version of FastTree. To do this, you need to compile it with -DUSE_DOUBLE and you need to use version 2.1.8 or later, e.g.

gcc -DUSE_DOUBLE -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm
```

Can I request that a version with `-DUSE_DOUBLE` is added?

**Comment by giordano** [comment]
Someone should first tell them to follow https://bssw.io/blog_posts/rethinking-software-variants, it's very complicated to ship two different variants at the same time otherwise.

**Comment by murrellb** [comment]
FastTree is ±2010 software that is extremely popular but also minimally maintained (last update in 2019). I would not expect the author to make any such changes at this point.

**Comment by giordano** [comment]
Do you have an example of downstream package which uses this library?

**Comment by murrellb** [comment]
I do not. I was planning on setting up a Julia package that does, though, which is why I was happy to see this. But for all of my personal use cases I use the double-precision version.
