### ISSUE TITLE
Request: patched LLVM source code

### ISSUE THREAD

**Issue by Gnimuc** [JuliaPackaging/Yggdrasil#692]
Now we already have `Clang_jll`, `libLLVM_jll`, `LLVM_jll` and `LLVM_full_jll`, but packages like Cxx.jl still need to download and patch those LLVM/Clang source code from scratch. It would be perfect if we could ship another artifact `LLVM_src_jll` to provide Julia-compatible LLVM/Clang source code.

**Comment by Gnimuc** [comment]
Hi @vchuravy, how hard is it to ship the patched source code in a new JLL package?

**Comment by vchuravy** [comment]
I would rather take the step and provide the patched source code at JuliaLang/julia

**Comment by Gnimuc** [comment]
LLVM 11+(Julia 1.6+) would be good.

**Comment by vtjnash** [comment]
This would perhaps also be a great way to drop the patches folder and tracking from JuliaLang, since we could download the pre-patched versions of files from here instead.

Or perhaps even better, to switch to managing all of our patches with git / GitHub (like we do for libuv)?

**Comment by vchuravy** [comment]
For LLVM 13: https://github.com/JuliaLang/llvm-project/tree/julia/release/13.x

**Comment by vtjnash** [comment]
https://github.com/llvm/llvm-project/compare/release/13.x...JuliaLang:julia/release/13.x

**Comment by vchuravy** [comment]
https://github.com/llvm/llvm-project/compare/release/12.x...JuliaLang:julia/release/12.x

**Comment by vchuravy** [comment]
@Gnimuc I am unlikely to do LLVM 11 since the process is a bit painful

But if you would like to help, I have been doing:

```
git am --directory=llvm < path to patch
```

The biggest annoyances are patches that are not in mailbox form

**Comment by Gnimuc** [comment]
It's good enough to have LLVM 12 as I'm not currently attempting to rework Cxx.jl for Julia 1.6.
