### ISSUE TITLE
Win32 SuiteSparse build is subtly borked

### ISSUE THREAD

**Issue by vtjnash** [JuliaPackaging/Yggdrasil#7]
It's installing 3 copies of every dll, and loading 2 of each at runtime.

**Comment by staticfloat** [comment]
Can you give more details? What do you mean by three copies, and why would it load two?

**Comment by staticfloat** [comment]
Closed by https://github.com/JuliaPackaging/Yggdrasil/commit/df2e0789fa467ef15e4417ce42d609f44a438a55

**Comment by vtjnash** [comment]
From Slack, it turns out this is not fixed yet: while the SONAME Is now correct, it's still installing the other 2 incorrect copies.

**Comment by ViralBShah** [comment]
Is this still an issue?

**Comment by vtjnash** [comment]
I don’t think it was ever fixed

**Comment by ViralBShah** [comment]
What needs to be done? Which 2 of the 3 need to be deleted?

**Comment by ViralBShah** [comment]
I believe we do a `cp -r` somewhere and it follows the symlinks. I suspect we can delete all the ones with the version numbers attached to them.

```
libamd.2.4.6.dll
libamd.2.dll
libamd.dll
libbtf.1.2.6.dll
libbtf.1.dll
libbtf.dll
libcamd.2.4.6.dll
libcamd.2.dll
libcamd.dll
libccolamd.2.9.6.dll
libccolamd.2.dll
libccolamd.dll
libcholmod.3.0.13.dll
libcholmod.3.dll
libcholmod.dll
libcolamd.2.9.6.dll
libcolamd.2.dll
libcolamd.dll
libklu.1.3.8.dll
libklu.1.dll
libklu.dll
libldl.2.2.6.dll
libldl.2.dll
libldl.dll
librbio.2.2.6.dll
librbio.2.dll
librbio.dll
libspqr.2.0.9.dll
libspqr.2.dll
libspqr.dll
libsuitesparse_wrapper.dll
libsuitesparseconfig.5.4.0.dll
libsuitesparseconfig.5.dll
libsuitesparseconfig.dll
libumfpack.5.7.8.dll
libumfpack.5.dll
libumfpack.dll
```

@giordano Is there an easy way to fix this or should we add some lines to SuiteSparse to delete the unnecessary dlls?

**Comment by giordano** [comment]
> Is there an easy way to fix this or should we add some lines to SuiteSparse to delete the unnecessary dlls?

I think one would need to manually remove the files.  This (untested) might work:
```sh
if [[ "${target}" == *-mingw* ]]; then
    rm ${libdir}/*.*.${dlext}
    rm ${libdir}/*.*.*.${dlext}
fi
```

However, I'm also surprised that two libraries are loaded at a time.  Does that happen with BinaryProvider or the Artifacts sytem?

**Comment by ViralBShah** [comment]
Do the soversions matter on windows?

**Comment by giordano** [comment]
> Do the soversions matter on windows?

No.

`Makefile`s for the various libraries have lines like these:
```make
	( cd $(INSTALL_LIB) ; ln -sf $(SO_TARGET) $(SO_PLAIN) )
	( cd $(INSTALL_LIB) ; ln -sf $(SO_TARGET) $(SO_MAIN) )
```

`SO_MAIN` and `SO_PLAIN` are define in `SuiteSparse_config/SuiteSparse_config.mk`, the comments say all:
```make
ifeq ($(UNAME),Windows)
    # Cygwin Make on Windows
    AR_TARGET = $(LIBRARY).lib
    SO_TARGET  = $(LIBRARY).dll
    # The following two links are just garbage copies of the real target
    # they aren't actually supported by this OS
    SO_MAIN   = $(LIBRARY).$(SO_VERSION).dll
    SO_PLAIN = $(LIBRARY).$(VERSION).dll
    SO_OPTS  += -shared
    SO_INSTALL_NAME = echo
```
