### ISSUE TITLE
undefined reference on ppc when linking libICE

### ISSUE THREAD

**Issue by j-fu** [JuliaPackaging/Yggdrasil#714]
Hi, not sure if this goes here or to BinaryBuilder. The error comes when linking to libICE which
comes from here...

... I am getting:

```
Linking CXX executable ../../bin/vtkProbeOpenGLVersion
cd /workspace/srcdir/build/Rendering/OpenGL2 && /usr/bin/cmake -E cmake_link_script CMakeFiles/vtkProbeOpenGLVersion.dir/link.txt --verbose=true
/opt/bin/powerpc64le-linux-gnu-g++ --sysroot=/opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/    -O3 -DNDEBUG   -Wl,-lc  -Wl,-lc   CMakeFiles/vtkProbeOpenGLVersion.dir/vtkProbeOpenGLVersion.cxx.o  -o ../../bin/vtkProbeOpenGLVersion -Wl,-rpath,/workspace/srcdir/build/lib:/usr/local/lib: ../../lib/libvtkRenderingOpenGL2.so.9.0.0 ../../lib/libvtkRenderingUI.so.9.0.0 ../../lib/libvtkRenderingCore.so.9.0.0 ../../lib/libvtkFiltersCore.so.9.0.0 /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libX11.so /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libGLEW.so /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libXt.so /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libX11.so /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libICE.so /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libSM.so ../../lib/libvtkCommonExecutionModel.so.9.0.0 ../../lib/libvtkCommonDataModel.so.9.0.0 ../../lib/libvtkCommonTransforms.so.9.0.0 ../../lib/libvtkCommonMisc.so.9.0.0 ../../lib/libvtkCommonMath.so.9.0.0 ../../lib/libvtkCommonCore.so.9.0.0 -lpthread ../../lib/libvtksys.so.9.0.0 -ldl -Wl,-rpath-link,/workspace/srcdir/build/lib 
/opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/9.1.0/../../../../powerpc64le-linux-gnu/bin/ld: /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libICE.so: undefined reference to `getentropy@GLIBC_2.25'
collect2: error: ld returned 1 exit status
```
So this may be due to different compiler versions. I am using the newest (gcc9) in order to avoid some errors I detected while cross-compiling. May be something else...

**Comment by giordano** [comment]
> I am using the newest (gcc9) in order to avoid some errors I detected while cross-compiling.

For maximum compatibility, the oldest GCC version, the better.  If you use a too new GCC version, many users won't be able to run your library

**Comment by giordano** [comment]
Is [`Xorg_libICE_jll`](https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl) the libICE you're talking about?  The path `/opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/usr/local/lib/libICE.so` looks suspiciously wrong

**Comment by vchuravy** [comment]
What is your script? We probably need to regenerate your dependency. See #704

**Comment by j-fu** [comment]
https://github.com/j-fu/YggBonsai/blob/master/V/VTKMinimal/build_tarballs.jl

For the source, it's sitting on a recent upstream commit which will go into vtk 9.0.0 final.

**Comment by vchuravy** [comment]
I am rebuilding libICE in https://github.com/JuliaPackaging/Yggdrasil/pull/722

**Comment by j-fu** [comment]
Got stuck for the full set due to github downtime, but switched back gcc version from 9 to 6 resulted in success for this architecture. gcc5 had kind of a compiler internal error on aarch.
For my purpose this is good enough.
