### ISSUE TITLE
Trouble identifying the proper `hash` to specify when using `GitSource` or `ArchiveSource`

### ISSUE THREAD

**Issue by chris-hampel-CA** [JuliaPackaging/Yggdrasil#7335]
This is not an issue with any code. I am requesting clarification on documentation about how to use `GitSource` or `ArchiveSource` to specify the location of the repo to be wrapped. 

When viewing examples of `build_tarballs.jl` files for various repos, I cannot match the `hash` argument supplied to `GitSource` or `ArchiveSource` to any commit hash on the main branch or the released version. 

Could someone explain to me how to identify what the `hash` arg should be for either situation? 

I am asking because my goal is to release a local `_jll` package while I wait for the base pkg managers of the pkg that I contributed to, to release my changes and update their `build_tarballs.jl` file here.

**Comment by giordano** [comment]
Did you read https://docs.binarybuilder.org/stable/FAQ/#What-are-those-numbers-in-the-list-of-sources?-How-do-I-get-them?-1 already?

**Comment by chris-hampel-CA** [comment]
Sorry I missed that. I was only looking at the function definitions https://docs.juliahub.com/BinaryBuilder/WHzgM/0.4.1/reference/#BinaryBuilderBase.ArchiveSource 

For `GitSource`, could the hash be the same as the latest commit hash on a main branch of a repo, for example? Wanting to make sure I understand the description in your link. 

![image](https://github.com/JuliaPackaging/Yggdrasil/assets/92957241/8885e67d-4370-48c6-ab0c-b9ea49dd064b)

Thanks!

**Comment by giordano** [comment]
> Sorry I missed that. I was only looking at the function definitions https://docs.juliahub.com/BinaryBuilder/WHzgM/0.4.1/reference/#BinaryBuilderBase.ArchiveSource

That already explains that the hash is the 64-character SHA256 checksum of the file.  Probably a quick search on the Internet would have given you the same answer :slightly_smiling_face: 

> For GitSource, could the hash be the same as the latest commit hash on a main branch of a repo, for example? Wanting to make sure I understand the description in your link.

We typically prefer to build a tagged version, rather than a random commit in a branch.

I presume this ticket can be closed?

**Comment by chris-hampel-CA** [comment]
I did not find google helpful for the SHA256, but the FAQ link is. 

Yes a random commit would be extreme. I was thinking the commit of the latest on a main branch or that of a released version. 

This can be closed. 

Thanks for the help.

**Comment by chris-hampel-CA** [comment]
Was hoping you might be able to provide some guidance on making a local `_jll` pkg.

I am running a `build_tarballs.jl` file to locally deploy a fork of another pkg to test my downstream changes in another pkg. 

I am using `GitSource` with the url of my fork with the commit hash from the mast branch. 

I then run this command `julia C/CoolProp/build_tarballs.jl --deploy=local` in a terminal, but I receive this error.

![image](https://github.com/JuliaPackaging/Yggdrasil/assets/92957241/fafb8da2-f247-4a80-92df-15f328333c60)

Is there anything that appears incorrect with my setup.

Thanks, Chris

**Comment by barche** [comment]
I have not seen that git error before, but these steps I find easier to locally test binaries:
1. Build your JLL binaries as you do above, but without any deployment
2. In the environment where you want to use the new binaries, do `develop CoolProp_jll`
3. Import or use `CoolProp_jll` and call `CoolProp_jll.dev_jll()`
4. Extract the generated tarball from step 1 into the `override` directory of the devved CoolProp_jll

**Comment by chris-hampel-CA** [comment]
My first issue was that I was using Windows OS; I later found out that it only works with Linux or Mac OS. 

We still had issues using `GitSource` though (don't remember the exact error), so we switched to the `DirectorySource` method where the referenced directory contained our local coolprop repo using `git clone --recursive <local coolprop github link>`. It worked successfully with these steps
