### ISSUE TITLE
lib file for windows

### ISSUE THREAD

**Issue by bharswami** [JuliaPackaging/Yggdrasil#7370]
I need a *.lib file for use with Visual Studio 2022 in Windows. The tar file provided has a *.a file.
Can you provide the corresponding libspral.lib file?

**Comment by imciner2** [comment]
The tarballs produced here are built using the mingw toolchain on a Linux platform, and mingw can't produce an import file for MSVC to use. If you have MSVC installed, you can follow the advice here https://stackoverflow.com/a/9946390 and build one yourself. Note it requires a file defining the exported functions, but upstream SPRAL doesn't seem to provide one, so you will have to write it yourself.

**Comment by bharswami** [comment]
Than ks. 
I am trying to build Spral on windows myself. Can you help me with a bug I encountered?

**Comment by imciner2** [comment]
We are unable to provide help building libraries outside of the Yggdrasil/BinaryBuilder ecosystem here. You should reach out and talk to the upstream developers with any problems you have building their library.
