### ISSUE TITLE
MPITrampoline embeds C++ abi tag, but is not abi-specialized

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/Yggdrasil#7420]
The generic MPITrampoline package that is not C++ ABI specialized has:
```
MPITRAMPOLINE_CC=${MPITRAMPOLINE_CC:-/opt/bin/x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline/x86_64-linux-gnu-gcc}
```

**Comment by simonbyrne** [comment]
@eschnett

**Comment by eschnett** [comment]
MPItrampoline (when built outside Yggdrasil) remembers the C, C++, and Fortran compilers that were used to build it, and uses these compilers and flags by default in the provided `mpicc` compiler wrappers.

Inside Yggdrasil that may well be too restrictive. In this case the work-around is to manually set `MPITRAMPOLINE_CC` etc. in other, MPI-dependent packages before configuring them in the `build_tarballs.jl` script.

The proper solution is probably to post-process the generated compiler wrappers in MPItrampolines `build_tarballs.jl` script and to replace these paths by `cc` etc.

Is there a specific package where this fails that we could use as test case?

**Comment by Keno** [comment]
> Is there a specific package where this fails that we could use as test case?

IIRC I ran into this trying to build Trillinos.
