### ISSUE TITLE
cudnn restricted to CUDA < 5.0

### ISSUE THREAD

**Issue by vpuri3** [JuliaPackaging/Yggdrasil#7471]
```julia
(MyPkg) pkg> st --outdated
Project MyPkg v0.0.1
Status `~/.julia/dev/GeometryLearning.jl/Project.toml`
⌅ [052768ef] CUDA v4.4.1 (<v5.0.0): cuDNN
```

@maleadt, is this expected?

**Comment by maleadt** [comment]
This is not the place to file such an issue; Yggdrasil is unrelated to CUDA.jl or cuDNN.jl

Also, no this is unexpected, as the latest cuDNN.jl supports CUDA 5+: https://github.com/JuliaRegistries/General/blob/d640b9855581e0ab90a558321aa712ba333cf527/C/cuDNN/Compat.toml#L27-L28
