### ISSUE TITLE
Blosc tests fail in Windows 11

### ISSUE THREAD

**Issue by bjarthur** [JuliaPackaging/Yggdrasil#7558]
see https://github.com/JuliaIO/Blosc.jl/issues/90.  please let me know if you need any more info.

**Comment by imciner2** [comment]
What exactly needs to be done here?

**Comment by bjarthur** [comment]
upgrade to blosc v1.21.5 according to https://github.com/JuliaIO/Blosc.jl/issues/90#issuecomment-1773548261
