### ISSUE TITLE
Apple builds for MPICH broke in recent toolchain update

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#7745]
See https://github.com/JuliaPackaging/Yggdrasil/pull/7736.

I saw some recent messages about downgrading `elfutils` in the RootFS. Is this expected to correct this problem?

@gbaraldi

**Comment by eschnett** [comment]
I am now seeing a similar (related?) build error on Apple https://github.com/JuliaPackaging/Yggdrasil/pull/7762 . This time it's with `cmake` (not `configure`) and the option is `-commons` (possibly Fortran-related):
```
[23:05:06] ld64.lld: warning: Option `-commons' is not yet implemented. Stay tuned...
[23:05:06] ld64.lld: error: No LC_DYLD_INFO_ONLY or LC_DYLD_EXPORTS_TRIE found in /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/lib/libgcc_s.1.dylib
[23:05:06] ld64.lld: error: No LC_DYLD_INFO_ONLY or LC_DYLD_EXPORTS_TRIE found in /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/lib/libgcc_ext.10.5.dylib
```
@gbaraldi Do you have some insight here as well?

**Comment by eschnett** [comment]
This approach also seems to work – deleting the new linkers:
```sh
if [[ "${target}" == x86_64-apple-darwin* ]]; then
    # See <https://github.com/JuliaPackaging/Yggdrasil/issues/7745>:
    # Remove the new linkers which don't work yet
    rm /opt/bin/${bb_full_target}/ld64.lld
    rm /opt/bin/${bb_full_target}/ld64.${target}
    rm /opt/bin/${bb_full_target}/${target}-ld64.lld
    rm /opt/${MACHTYPE}/bin/ld64.lld
fi
```

**Comment by ViralBShah** [comment]
Is this still an issue?

**Comment by ViralBShah** [comment]
This seems to be fixed. https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/tag/MPICH-v4.2.2%2B0
