### ISSUE TITLE
[XGBoost] Issues on Mac

### ISSUE THREAD

**Issue by aviks** [JuliaPackaging/Yggdrasil#778]
The latest build of XGBoost built in #657 fails to pass tests on the Mac. The error is as follows:

```
dyld: lazy symbol binding failed: Symbol not found: ___cxa_thread_atexit
  Referenced from: /Users/travis/.julia/artifacts/3ff38e086f3b040acfb66c0e7d42fac2bdc6eea5/lib/libxgboost.dylib
  Expected in: /Users/travis/.julia/artifacts/7c9ef733699a1d86b8a6073ed08a4457e3e790f7/lib/libstdc++.6.dylib

dyld: Symbol not found: ___cxa_thread_atexit
  Referenced from: /Users/travis/.julia/artifacts/3ff38e086f3b040acfb66c0e7d42fac2bdc6eea5/lib/libxgboost.dylib
  Expected in: /Users/travis/.julia/artifacts/7c9ef733699a1d86b8a6073ed08a4457e3e790f7/lib/libstdc++.6.dylib

signal (6): Abort trap: 6
in expression starting at /Users/travis/build/dmlc/XGBoost.jl/test/runtests.jl:8

signal (6): Abort trap: 6
in expression starting at /Users/travis/build/dmlc/XGBoost.jl/test/runtests.jl:8
unknown function (ip: 0x1098c5249)

Allocations: 10016393 (Pool: 10014671; Big: 1722); GC: 11
```
[Full Test Results](https://travis-ci.org/github/dmlc/XGBoost.jl/jobs/670891847?utm_medium=notification&utm_source=github_status) | https://github.com/JuliaPackaging/Yggdrasil/pull/657

@ViralBShah says: there were many scary [error messags in the Mac build](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2228&view=logs&j=0e6f23d3-bbc5-5a5c-1679-8a7f37dad18d&t=62f65e56-6499-50ca-7cf6-50d14fe18c3b&l=57457)

The previous binary builder builds, built by @staticfloat  and available here https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases did work. However, the new version built into the jll as a result of #657 no longer works. It is not clear what has changed. As a short term fix, if we can get those binaries into a `jll`, we could move forward. 

cc: @giordano

**Comment by aviks** [comment]
OK, one strange thing: There was a comment from @staticfloat on https://github.com/dmlc/XGBoost.jl/pull/68 saying  _" on MacOS, we are using clang to build Julia ....   Using gcc on MacOS will cause us to mix C++ stdlibs, and I don't think that's a good thing"_

However, the [build_tarballs.jl even prior to #657](https://github.com/JuliaPackaging/Yggdrasil/blob/ebdaf7658e27460335553e10ff9cfb333a1b468d/X/XGBoost/build_tarballs.jl) doesn't seem to have this special casing for Mac. Elliot, was there any local uncommitted changes when you built these binaries, by any chance?

**Comment by ViralBShah** [comment]
We can just disable openmp and use clang for now.

**Comment by ViralBShah** [comment]
Btw are we ok on using the right commit for the build?

**Comment by giordano** [comment]
> The previous binary builder builds, built by @staticfloat and available here JuliaBinaryWrappers/XGBoost_jll.jl/releases did work

Maybe I'm missing something, but what do you refer to?  I only see v0.82 built last week

**Comment by ViralBShah** [comment]
The build script existed before. I only updated it.

**Comment by giordano** [comment]
Ok, I think the old tarballs Avik was referring to are [here](https://github.com/juliapackaging/yggdrasil/releases/tag/XGBoost-v0.82-2).  Looking at the log in the macOS tarballs, it seems that Clang was used.  [This](https://github.com/JuliaPackaging/Yggdrasil/blob/35ecf31d19a13c2e3f5f49ee486995dee1142bc2/XGBoost/build_tarballs.jl) should be the corresponding build script (visible also in the log).

**Comment by aviks** [comment]
So the new script has 
```
# Because we're using OpenMP, we must use `gcc`
export CC=gcc
export CXX=g++
```
While the script linked by @giordano does not have these lines. 

I am still confused -- does removing these lines make it use clang on mac but gcc everywhere else?

**Comment by giordano** [comment]
> does removing these lines make it use clang on mac but gcc everywhere else?

Yes, by default we use GCC for Linux and Windows, Clang for macOS and FreeBSD

**Comment by ViralBShah** [comment]
Is there a `libc++` issue/PR that should be linked here?

**Comment by aviks** [comment]
Not that i know. This issue can be closed, a new version has been released with clang compiled mac (without openmp) for v0.82
