### ISSUE TITLE
`Poppler_jll` has not been updated in over two years 

### ISSUE THREAD

**Issue by Sbozzolo** [JuliaPackaging/Yggdrasil#7799]
I recently started experimenting with [PDFmerger](https://github.com/scheidan/PDFmerger.jl) to produce a multi-page PDF for summary plots in our CI. It works very well! 

However, some packages are forced to very old versions which have known problems. I see that
```
ERROR: Unsatisfiable requirements detected for package GR_jll [d2c73de3]:
 GR_jll [d2c73de3] log:
[OMITTED]
 ├─restricted by compatibility requirements with Libtiff_jll [89763e89] to versions: 0.51.2-0.72.8 or uninstalled, leaving only versions: 0.51.2-0.56.1 or uninstalled
 │ └─Libtiff_jll [89763e89] log:
 │   ├─possible versions are: 4.0.10-4.6.0 or uninstalled
 │   └─restricted by compatibility requirements with Poppler_jll [9c32591e] to versions: 4.3.0-4.4.0
 │     └─Poppler_jll [9c32591e] log:
 │       ├─possible versions are: 0.87.0-21.9.0 or uninstalled
 │       └─restricted by compatibility requirements with PDFmerger [3beb2ed1] to versions: 21.9.0
 │         └─PDFmerger [3beb2ed1] log:
 │           ├─possible versions are: 0.1.0-0.3.0 or uninstalled
 │           └─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.3.0
```
This cascades into forcing other packages to very old versions. 

Would it be possible to update `Poppler_jll` ~and/or check that its compat is not overly restrictive~?

Thanks in advance.

**Comment by eschnett** [comment]
What does "restrictive compat" mean? The entries I see differ by minor version numbers and should allow using the newest package versions.

**Comment by giordano** [comment]
I presume the problem is Libtiff, because v4.5 is ABI-incompatible with v4.3-4.4: https://github.com/JuliaRegistries/General/pull/86099

**Comment by Sbozzolo** [comment]
> What does "restrictive compat" mean? The entries I see differ by minor version numbers and should allow using the newest package versions.

Ah, right. I applied the rules for `0.X.X` compats to `1.X.X` ones.

`GR_jll` just got updated, as well as `Plots.jl` (https://github.com/JuliaPlots/Plots.jl/commit/806641a8b53da18bb756ed1a94c515f0e858a27e), so I presume my problems will be solve by a new release of `Plots.jl` (or a change in its compat in the registry), given that will allow me to use Libtiff 4.5.1.

Thanks!

Feel free to close the issue, or leave it here (`Poppler_jll` has indeed not been updated in more than 2 years).

**Comment by Sbozzolo** [comment]
Actually, I am still unable to update my depedencies. I cloned and dev the most recent Plots.jl, but I find
```
(examples) pkg> add GR@0.73
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Poppler_jll [9c32591e]:
 Poppler_jll [9c32591e] log:
 ├─possible versions are: 0.87.0-21.9.0 or uninstalled
 ├─restricted by compatibility requirements with PDFmerger [3beb2ed1] to versions: 21.9.0
 │ └─PDFmerger [3beb2ed1] log:
 │   ├─possible versions are: 0.1.0-0.3.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.3.0
 └─restricted by compatibility requirements with Libtiff_jll [89763e89] to versions: uninstalled — no versions left
   └─Libtiff_jll [89763e89] log:
     ├─possible versions are: 4.0.10-4.6.0 or uninstalled
     └─restricted by compatibility requirements with GR_jll [d2c73de3] to versions: 4.5.1
       └─GR_jll [d2c73de3] log:
         ├─possible versions are: 0.51.2-0.73.0 or uninstalled
         └─restricted by compatibility requirements with GR [28b8d3ca] to versions: 0.73.0
           └─GR [28b8d3ca] log:
             ├─possible versions are: 0.35.0-0.73.0 or uninstalled
             ├─restricted to versions 0.69.5-0.73 by Plots [91a5bcdd], leaving only versions: 0.69.5-0.73.0
             │ └─Plots [91a5bcdd] log:
             │   ├─possible versions are: 1.39.1 or uninstalled
             │   └─Plots [91a5bcdd] is fixed to version 1.39.1
             └─restricted to versions 0.73 by an explicit requirement, leaving only versions: 0.73.0
```

Why I don't understand, because `Poppler_jll` should be compatible with `Libtiff_jll` `4.5.1`

**Comment by giordano** [comment]
No, it isn't, see the PR I linked above: https://github.com/JuliaRegistries/General/pull/86099

**Comment by Sbozzolo** [comment]
> No, it isn't, see the PR I linked above: [JuliaRegistries/General#86099](https://github.com/JuliaRegistries/General/pull/86099)

Okay, got it! Now I understand what you meant. I guess it would have been nice to update the `Poppler_jll` repo as well to reflect that change (but I understand it is a lot of busywork)

**Comment by Sbozzolo** [comment]
Thank you! :)
