### ISSUE TITLE
CI in Buildkite errors, out of space?

### ISSUE THREAD

**Issue by MAiNGO-github** [JuliaPackaging/Yggdrasil#7905]
It seems that the CI is experiencing some issues.
Perhaps there are some disk space constraints?

```
git clone -v --reference /cache/repos/https---github-com-JuliaPackaging-Yggdrasil-git -- https://github.com/JuliaPackaging/Yggdrasil.git
[...]
error: unable to write file A/aws_c_io/bundled/patches/win32_sspi_h_missing_macros.patch

fatal: cannot create directory at 'A/aws_c_iot': No space left on device

warning: Clone succeeded, but checkout failed.
```

See ([https://buildkite.com/julialang/yggdrasil/builds/7539#018cd3c7-81c5-45ff-a8df-3cf199e2a06d/137-169](https://buildkite.com/julialang/yggdrasil/builds/7539#018cd3c7-81c5-45ff-a8df-3cf199e2a06d/137-169)) for the full log. But this seems to affect other pull requests as well.

**Comment by giordano** [comment]
Resolved.
