### ISSUE TITLE
[libadwaita] cannot be installed on Julia 1.10 in Windows.

### ISSUE THREAD

**Issue by nhz2** [JuliaPackaging/Yggdrasil#7935]
The `libadwaita` artifact https://github.com/JuliaBinaryWrappers/libadwaita_jll.jl/releases/download/libadwaita-v1.2.0+0/libadwaita.v1.2.0.x86_64-w64-mingw32.tar.gz contains the following symlinks:

```
     "bin/gdk-pixbuf-pixdata" => "/usr/bin/gdk-pixbuf-pixdata"
 "bin/glib-compile-resources" => "/usr/bin/glib-compile-resources"
   "bin/glib-compile-schemas" => "/usr/bin/glib-compile-schemas"
```
These are created in the build script at
https://github.com/JuliaPackaging/Yggdrasil/blob/b9f0d0b88330feca61620106f7155a2c1a2dc25e/L/libadwaita/build_tarballs.jl#L19-L22

This prevents it from being installed on Windows in Julia 1.10 due to stricter artifact integrity checking. Ref: https://github.com/Clemapfel/Mousetrap.jl/issues/55

The build script may be missing the lines in the GTK4 recipe.
https://github.com/JuliaPackaging/Yggdrasil/blob/b9f0d0b88330feca61620106f7155a2c1a2dc25e/G/GTK4/build_tarballs.jl#L93-L94

@jwahlstrand

**Comment by jwahlstrand** [comment]
OK, I was planning to update the versions of GTK4 and libadwaita this weekend and I can remove these symlinks at the same time. If it's more urgent than that, someone else should feel free to do it.

**Comment by Clemapfel** [comment]
Thank you for taking the time to update the jll, I've only had one issue because of this which had a temporary fix so if it takes a few days that is fine
