### ISSUE TITLE
[PARMETIS] Issue installing on Windows

### ISSUE THREAD

**Issue by nhz2** [JuliaPackaging/Yggdrasil#7967]
The `PARMETIS` artifact https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz contains the following symlink:
```julia
 "lib/msmpi.dll" => "../bin/msmpi.dll"
```

<details>

```julia
julia> using Tar: Tar

julia> using Pkg: Pkg, PlatformEngines

julia> using Downloads: download

julia> function tar_get_symlinks(tarball_path::AbstractString)
           symlinks_output = Pair{String,String}[]
           Tar.list(`$(PlatformEngines.exe7z()) x $tarball_path -so`) do header::Tar.Header
               if (header.type == :symlink)
                   push!(symlinks_output, header.path=>header.link)
               end
               nothing
           end
           symlinks_output
       end
tar_get_symlinks (generic function with 1 method)

julia> url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz";

julia> tar_get_symlinks(download(url))
1-element Vector{Pair{String, String}}:
 "lib/msmpi.dll" => "../bin/msmpi.dll"

```

</details>

This prevents it from being installed on Windows in Julia 1.10 due to stricter artifact integrity checking.

This seems very similar to https://github.com/JuliaPackaging/Yggdrasil/pull/7919

CC: @amontoison @vchuravy

**Comment by amontoison** [comment]
We need to recompile PARMETIS without this [symlink](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/PARMETIS/build_tarballs.jl#L34) on Windows.
