### ISSUE TITLE
`CURL_4' not found for Poppler_jll v23 in Julia 1.8

### ISSUE THREAD

**Issue by tpapp** [JuliaPackaging/Yggdrasil#8084]
With Poppler_jll v23.12.0+0 on Julia 1.8, I get the following error in unit tests:

```
/home/runner/.julia/artifacts/c26aa29d2df324fb8b22554ad29bf67e463a1155/bin/pdftocairo: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_4' not found (required by /home/runner/.julia/artifacts/c26aa29d2df324fb8b22554ad29bf67e463a1155/lib/libpoppler.so.133)
```

Note that in Julia 1.10 it works fine. So dies Poppler_jll v22 on 1.8.

**Comment by giordano** [comment]
The problem is that you're somehow using a system library `/lib/x86_64-linux-gnu/libcurl.so.4`, usually this is due to setting LD_LIBRARY_PATH or something like that

**Comment by tpapp** [comment]
Note that 

1. the error message is from CI, running in Github Actions.
2. other versions work fine, so I am not sure what changes between runs.

**Comment by giordano** [comment]
A reproducer would be most helpful, but this works for me
```
(tmp) pkg> st Poppler_jll
Status `/tmp/Project.toml`
  [9c32591e] Poppler_jll v23.12.0+0

julia> using Poppler_jll

julia> success(`$(pdftocairo()) -png test.pdf test.png`)
true
```

**Comment by giordano** [comment]
In my system I can reproduce this only if I do something like
```sh
export LD_PRELOAD=/usr/lib/libcurl.so
```
to forcibly point to system libcurl.

> (also, would you mind reopening the issue?)

There's no evidence there's any bug on our side.

**Comment by tpapp** [comment]
I have updated the repo to print `LD_PRELOAD`, and apparently it is unset on Github actions, too:

https://github.com/tpapp/PopplerMWE.jl/actions/runs/7843905876/job/21405202231

> There's no evidence there's any bug on our side.

With respect, I think it is premature to conclude this. At this point the cause of the bug is not determined.

**Comment by giordano** [comment]
The problem is that `CompilerSupportLibraries_jll.LIBPATH_list` only in Julia v1.8 (which is not maintained anymore) and only on CI (I can't reproduce locally) contains `/lib/x86_64-linux-gnu`.  As I said, nothing to do here.

**Comment by giordano** [comment]
My hunch is that this may have been fixed by https://github.com/JuliaLang/julia/pull/46976.
