### ISSUE TITLE
libcurl - include static build

### ISSUE THREAD

**Issue by genotrance** [JuliaPackaging/Yggdrasil#8086]
https://github.com/JuliaBinaryWrappers/LibCURL_jll.jl only generates dll/so files while all the libcurl dependencies like libssh2 generate static .a files. Please extend the libcurl builder to generate static libraries.

**Comment by giordano** [comment]
> dependencies like libssh2 generate static .a files.

That looks like an oversight, thanks for reporting it, we should delete it as well.
