### ISSUE TITLE
Packages fail to precompile on musl system

### ISSUE THREAD

**Issue by ii8** [JuliaPackaging/Yggdrasil#8336]
I came across this while trying to use Makie, here is the full log: [makieerrors.txt](https://github.com/MakieOrg/Makie.jl/files/14669385/makieerrors.txt)
And here is the original issue on the Makie repo: https://github.com/MakieOrg/Makie.jl/issues/3725

There are a couple of issues I think, libiconv.so is assumed to exist on musl systems and the FFMPEG package has an exploding dependencies problem so completely unrelated things like `Xorg_libXext_jll` end up getting pulled into the environment.

**Comment by giordano** [comment]
You're likely observing https://github.com/JuliaLang/julia/issues/40556. Can't do much about it here.

**Comment by ii8** [comment]
Should I open a separate issue about the ffmpeg dependencies?

**Comment by giordano** [comment]
Why?

**Comment by ii8** [comment]
Because installing ffmpeg causes Xorg_libX11_jll and also other things to be installed which is very odd as they shouldn't be dependencies of ffmpeg, and they aren't on any linux distro AFAIK, certainly not any I've used. And this issue was closed without that being addressed. I'm not even using X so it makes no sense that Xorg things are being installed.

**Comment by giordano** [comment]
> Because installing ffmpeg causes Xorg_libX11_jll and also other things to be installed which is very odd as they shouldn't be dependencies of ffmpeg,

I don't what you're talking about, libx11 and libxext _are_ dependencies of ffmpeg, for example on arch Linux: https://archlinux.org/packages/extra/x86_64/ffmpeg/

> and they aren't on any linux distro AFAIK

Again, no clue what you're talking about, for example on alpine linux: https://pkgs.alpinelinux.org/package/edge/main/x86/libx11

> certainly not any I've used. 

I thought you said you use alpine

> And this issue was closed without that being addressed.

What do you want to address? I said we can't do much about musl dynamic loader being overly strict and not allowing multiple prefixes in a nice way
