### ISSUE TITLE
builder request: Octave

### ISSUE THREAD

**Issue by Krastanov** [JuliaPackaging/Yggdrasil#8397]
Having Octave available in Yggdrasil will make the creation of simple matlab-translation tools a bit easier (OctaveCall.jl akin to PythonCall.jl and MATLAB.jl). Creating this issue here to track potential progress.

**Comment by ViralBShah** [comment]
I suppose this should be straightforward to build, but may need a bit of work to use all the dependencies from Ygg itself.

**Comment by ViralBShah** [comment]
I believe this is not straightforward because the Octave build process does not support cross-compilation.

**Comment by ViralBShah** [comment]
We do have an interface package, and I wonder what it may take to refresh it. https://github.com/JuliaInterop/OctCall.jl

**Comment by imciner2** [comment]
Octave was added inhttps://github.com/JuliaPackaging/Yggdrasil/pull/9729, so closing this.

**Comment by ViralBShah** [comment]
The produced binaries have some issues - but yes at lesat we have the builder.

**Comment by ViralBShah** [comment]
Works:

```
julia> using Octave_jll, OpenBLAS32_jll

julia> withenv("LBT_DEFAULT_LIBS"=>OpenBLAS32_jll.libopenblas_path) do
           run(Octave_jll.octave_cli())
       end
GNU Octave, version 9.3.0
Copyright (C) 1993-2024 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "aarch64-apple-darwin20".

Home page:            https://octave.org
Support resources:    https://octave.org/support
Improve Octave:       https://octave.org/get-involved

For changes from previous versions, type 'news'.

octave:1> rand(2)+rand(2)
ans =

   1.7363   1.2488
   1.1367   1.1966

octave:2> 
```

**Comment by ViralBShah** [comment]
The annoying thing is that I can't do `sprand`, `speye`, `eigs` etc. - which feels like it all the .m files that ship with Octave. Perhaps some kind of a path issue. However, the heavy lifting is done, and all the BLAS etc. works.

**Comment by giordano** [comment]
Minor nitpick: I warmly recommend using [`addenv`](https://docs.julialang.org/en/v1/base/base/#Base.addenv) over [`withenv`](https://docs.julialang.org/en/v1/base/base/#Base.withenv), the former is thread-safe, the latter isn't. I personally had bad experiences with `withenv`, if the process dies unexpectedly, you can end up with a broken ENV which breaks everything.
