### ISSUE TITLE
HiGHSstatic_jll.jl raises error on missing libz.dll library

### ISSUE THREAD

**Issue by tengels** [JuliaPackaging/Yggdrasil#8408]
Seems to be occurring for previous versions 1.6.0 and 1.6.1 as well (1.5.3 does work).

> The code execution cannot proceed because libz.dll was not found. Reinstalling the program might fix this problem.

Executing the executable using Python (3.12) via the pulp module (2.8.0) on Windows 10 (x64).

**Comment by giordano** [comment]
@odow

**Comment by odow** [comment]
I'll take a look

**Comment by odow** [comment]
```
(base) oscar@Oscars-MBP HiGHSstatic.v1.7.0.x86_64-apple-darwin % otool -L bin/highs
bin/highs:
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.3.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

Ah. Even though it's meant to be a static build, we're still linking to libz.

**Comment by tengels** [comment]
I can confirm all works as expected with new build. Thank you very much for the quick (re)action!
