### ISSUE TITLE
OpenSSH_jll is outdated and has known security issues

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#8436]
We should update the package build recipe. See https://github.com/JuliaPackaging/Yggdrasil/pull/7196 for an attempt that worked but failed on Windows.

**Comment by fingolfin** [comment]
Perhaps this windows port of openssh could be used? https://github.com/PowerShell/openssh-portable

**Comment by ViralBShah** [comment]
Is this still relevant?

**Comment by eschnett** [comment]
OpenSSH_jll has been updated in the mean time.
