### ISSUE TITLE
`CUDA_full_jll` has `include` and `lib64` as symlinks

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#844]
This is the content of the `CUDA_full_jll` directory on my disk:
```
% ls -lh 
total 104K
drwxr-xr-x 3 mose mose 4.0K Apr 12 17:26 bin
-r--r--r-- 1 mose mose  59K Apr 12 17:26 EULA.txt
drwxr-xr-x 6 mose mose 4.0K Apr 12 17:26 extras
lrwxrwxrwx 1 mose mose   28 Apr 12 17:26 include -> targets/x86_64-linux/include
lrwxrwxrwx 1 mose mose   24 Apr 12 17:26 lib64 -> targets/x86_64-linux/lib
drwxr-xr-x 2 mose mose 4.0K Apr 12 17:26 logs
drwxr-xr-x 3 mose mose 4.0K Apr 12 17:26 nvml
drwxr-xr-x 7 mose mose 4.0K Apr 12 17:26 nvvm
drwxr-xr-x 7 mose mose 4.0K Apr 12 17:26 nvvmx
drwxr-xr-x 4 mose mose 4.0K Apr 12 17:26 share
drwxr-xr-x 2 mose mose 4.0K Apr 12 17:26 src
drwxr-xr-x 3 mose mose 4.0K Apr 12 17:26 targets
drwxr-xr-x 2 mose mose 4.0K Apr 12 17:26 tools
-r--r--r-- 1 mose mose   21 Apr 12 17:26 version.txt
```
`include` and `lib64` are symlinks, which  means that when building a library that depends on `CUDA_full_jll` and other JLL packages that also have directories with the same names, these artifacts will fail to be mounted because `CUDA_full_jll` will try to create a symlink on an existing directory.  This issue has been spotted by @innerlee.

Note: pull request #770 works because the only other dependency, `CompilerSupportLibraries_jll`, doesn't have `include/` nor `lib64/`.

CC: @maleadt

**Comment by maleadt** [comment]
> `include` and `lib64` are symlinks, which means that when building a library that depends on `CUDA_full_jll` and other JLL packages that also have directories with the same names, these artifacts will fail to be mounted because `CUDA_full_jll` will try to create a symlink on an existing directory. This issue has been spotted by @innerlee.

Ah, interesting. NVIDIA packages it up like that, assuming you extract the tarball in, e.g., `/opt/cuda` or `/usr/local/cuda` where these conflicts doesn't happen. The entire layout isn't really intended to be extracted at the root of anything, e.g. containing unexpected toplevel directories like `nvvm` or `extras`, so maybe the best solution would be to move CUDA's contents in `CUDA_full_jll` to `$prefix/cuda`? Would hurt discoverability, though, so maybe it's better to resolve those symlinks (which only occur with the Linux builds anyway).

**Comment by giordano** [comment]
> maybe the best solution would be to move CUDA's contents in `CUDA_full_jll` to `$prefix/cuda`? Would hurt discoverability, though, so maybe it's better to resolve those symlinks

Yes, the first solution would be "cleaner" and maybe somewhat closer to what developers using CUDA normally do, but would also make it more likely the need to specify search path of headers and libs -- not a big deal though, we often have to do this anyway.  Resolving the symlinks would also be good.  I'm happy with both solutions.
