### ISSUE TITLE
update tectonic_jll to 0.15.0

### ISSUE THREAD

**Issue by fkastner** [JuliaPackaging/Yggdrasil#8487]
There's a new version of [`tectonic`](https://github.com/tectonic-typesetting/tectonic/releases/tag/tectonic%400.15.0) that in particular links to OpenSSL 3.x. This fixes a problem on newer Linuxes where `libssl.so.1.1` could not be found.

I have no experience with BinaryBuilder, but the last PR (#7087) makes it seem like I only have to update the version number in that script. Is that all that is needed?

**Comment by giordano** [comment]
> This fixes a problem on newer Linuxes where libssl.so.1.1 could not be found.

Can you please elaborate on what this means?

> it seem like I only have to update the version number in that script. Is that all that is needed?

Well, no, you also have to update the source, which I just realised was completely missed in that PR (and I didn't spot it).

**Comment by fkastner** [comment]
I get
```
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
and seeing [tectonic#1025](https://github.com/tectonic-typesetting/tectonic/issues/1025) as well as this [stackoverflow question](https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory/72633324#72633324) I thought this has something to do with OpenSSL. But I could also be completely wrong.

**Comment by giordano** [comment]
> I get

You don't explain what you're doing, what commands your trying to run.

**Comment by fkastner** [comment]
Ok, so actually I was investigating a problem with the Franklin.jl demos page ([Franklin.jl#1077](https://github.com/tlienart/Franklin.jl/issues/1077)).
When I try to "compile" (`optimize(minify=false, prerender=false)`) that page I get the above error:
```
→ evaluating code [_ceval_5] in (index.md)
/home/kastner/.julia/artifacts/ddbf999b089a7d8b8aadf1b24722b7e9ade6e5b7/bin/tectonic: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
So I assumed that this must be a tectonic problem, found the GH discussion linked above and figured updating tectonic would fix it.

Now that I tried to create a MWE, actually there is no error.
Tectonic is used here through [`TikzPictures.jl`](https://github.com/JuliaTeX/TikzPictures.jl) and the following works for me without error:
```julia
#] add TikzPictures
using TikzPictures
tikzUseTectonic(true)
tp = TikzPicture("\\draw (0,0) -- (10,10);\n\\draw (10,0) -- (0,10);\n\\node at (5,5) {tikz \$\\sqrt{\\pi}\$};", options="scale=0.25", preamble="")
save(SVG("test.svg"),tp)
```

Unfortunately, I don't have time right now to investigate this further.

**Comment by ViralBShah** [comment]
It isn't straightforward: https://github.com/JuliaPackaging/Yggdrasil/pull/9232
