### ISSUE TITLE
GitSource caching preventing updating to new upstream releases

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#851]
GitSource URLs don't seem to be able to pull in newly tagged versions. @giordano believes it may be the result of caching. See the discussion in:

https://github.com/JuliaPackaging/Yggdrasil/pull/837#issuecomment-612641835

**Comment by ViralBShah** [comment]
@giordano Is this still an issue?

**Comment by giordano** [comment]
I don't think so, I believe that has been the only time we've seen that kind of behaviour

**Comment by fingolfin** [comment]
Can this be closed?
