### ISSUE TITLE
[SuiteSparse] Conditional loading dynamic libraries

### ISSUE THREAD

**Issue by inkydragon** [JuliaPackaging/Yggdrasil#8526]
xref: JuliaLang/julia#53211

Is it possible to do conditional loading of dynamic libraries?
Specifically for SuiteSparse, load `libcholmod`, `librbio`, `libspqr`, `libumfpack` only if `Base.USE_GPL_LIBS` is true.

Since [SuiteSparse_jll.jl](https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl) is dynamically generated, I'm not sure which file to modify.

Another, more aggressive, approach is to split SuiteSparse based on modules, one jll per module.

**Comment by giordano** [comment]
If you're asking for Julia code in the Julia repository, you should open an issue there. Here we only generate the tarballs that are used there, the "jlls" used by Julia itself are maintained in its repository, not here.
