### ISSUE TITLE
include not defined

### ISSUE THREAD

**Issue by blegat** [JuliaPackaging/Yggdrasil#858]
Following the README, I tried the following with Julia v1.4 but got `include not defined`
```
$ julia --color=yes generate_buildjl.jl C/Coin-OR/CSDP/build_tarballs.jl JuliaBinaryWrappers/CSDP_jll.jl CSDP-v6.2.0+4 

[ Info: Build tarballs script: C/Coin-OR/CSDP/build_tarballs.jl
[ Info: Repo name: JuliaBinaryWrappers/CSDP_jll.jl
[ Info: Tag name: CSDP-v6.2.0+4
ERROR: LoadError: LoadError: UndefVarError: include not defined
Stacktrace:
 [1] top-level scope at string:1
 [2] include_string(::Module, ::String, ::String) at ./loading.jl:1080
 [3] include_string(::Module, ::String) at ./loading.jl:1084
 [4] top-level scope at /home/blegat/git/Yggdrasil/generate_buildjl.jl:210
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] exec_options(::Base.JLOptions) at ./client.jl:288
 [7] _start() at ./client.jl:484
in expression starting at string:1
in expression starting at /home/blegat/git/Yggdrasil/generate_buildjl.jl:210
```

**Comment by giordano** [comment]
I had this problem some time ago, I don't remember the workaround I used though :grimacing:

**Comment by blegat** [comment]
The error comes from this line:
https://github.com/JuliaPackaging/Yggdrasil/blob/800edf4ae4008f449c7ebaf4bd3a32ae62caa29f/C/Coin-OR/CSDP/build_tarballs.jl#L1
As a workaround, I replaced the `include` line by the content of the file locally and it worked.

**Comment by giordano** [comment]
Right, we use `include_string`, and when using it `include` is not defined.  I probably I had the same issue with a similar builder that was including another file.

**Comment by fingolfin** [comment]
anything to be done here or can this be closed?

**Comment by giordano** [comment]
Yeah, let's close it, [`generate_buildjl.jl`](https://github.com/JuliaPackaging/Yggdrasil/blob/b12374bad946d5132082d9961379b0be2a95b370/generate_buildjl.jl) should hopefully not even be needed anymore.
