### ISSUE TITLE
Builds with big static libraries, big logs, or big docs

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/Yggdrasil#864]
Here is a list of some builds that bundle:

Static libraries:

- [x] `lib265`
- [ ] `libcrypto`, `libssl`
- [x] `libfdk-aac`
- [ ] `libtiff`
- [ ] `libvpx`
- [ ] `libturbojpeg`, `libjpeg`
- [x] `libvorbisenc`
- [x] `libvorbis`
- [x] `libzstd`
- [x] `libzmq`
- [x] `libmp3lame`
- [x] `libass`
- [ ] `libbz2`
- [ ] `libopenspecfun`

Docs:

- [ ] `libxml2` (2.7 MB)
- [ ] `libtiff` (1.4 MB)
- [ ] `libogg` (570 kb)
- [x] `libvorbis` (840 kb)

Logs:

- [x] `FFMPEG` (3.2 MB)
- [x] `OpenBLAS` (8 MB)
- [ ] `ImageMagick` (311 kB)
- [ ] `Arpack` (463 kB)

**Comment by KristofferC** [comment]
It's quite easy to see these by using a program like windirstat, k4dirstat, disk inventory x etc:

![image](https://user-images.githubusercontent.com/1282691/79255713-0fdc4500-7e87-11ea-8a4d-4264514944b2.png)

**Comment by ViralBShah** [comment]
Note that some packages are meant to be only `BuildDependency`s and have only static libraries.

**Comment by ViralBShah** [comment]
Can BB simply not ship the logs at all?

**Comment by giordano** [comment]
The log are sometime precious for debugging

**Comment by ViralBShah** [comment]
Presumably we can store them elsewhere and not ship them to every user?

**Comment by jaakkor2** [comment]
How about the import libraries on Windows (*.dll.a) ? Are they needed in some use scenario?
My system has those 4% of packages+artifacts size.  These are from artifacts directory with size > 1 MB
```
  "libopenblas64_.dll.a" => 5660794
             "libgeos.dll.a" => 3605936
           "libcrypto.dll.a" => 2840812
            "libipopt.dll.a" => 2191024
   "libMagick++-6.Q16.dll.a" => 2030248
             "libx264.dll.a" => 1474428
     "libspatialindex.dll.a" => 1164128
             "libxml2.dll.a" => 1069626
```

**Comment by giordano** [comment]
I think they're needed to build libraries that link to them

**Comment by giordano** [comment]
After https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/755, uncompressed `logs/` directory for `x86_64-apple-darwin14-libgfortran4` in [`v0.3.9+4`](https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.9%2B4/OpenBLAS.v0.3.9.x86_64-apple-darwin14-libgfortran4.tar.gz) is down to 464 KiB, from 7.8 MiB in [`v0.3.9+2`](https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.9%2B2/OpenBLAS.v0.3.9.x86_64-apple-darwin14-libgfortran4.tar.gz).

**Comment by giordano** [comment]
#1006 halved the size of the tarballs of all packages involved excluding x264 (there was already no static archive in there)

**Comment by KristofferC** [comment]
Feel free to close this whenever you think it is in a good enough state right now.
