### ISSUE TITLE
ALSA + FFMPEG compatibility issue

### ISSUE THREAD

**Issue by ssfrr** [JuliaPackaging/Yggdrasil#8714]
Users have been [reporting some issues](https://github.com/JuliaAudio/PortAudio.jl/issues/126) with installing PortAudio.jl, which I think are related to an update to FFMPEG that isn't reflected in the ALSA build.

`alsa_plugins_jll` loads `libasound_module_pcm_a52.so`, and that that library seems to be dependent on `libavcodec.so.58`, which it's not finding.

It looks like the [latest version of FFMPEG_jll](https://github.com/JuliaBinaryWrappers/FFMPEG_jll.jl/blob/main/src/wrappers/x86_64-linux-gnu.jl) builds `libavcodec.so.60`, so maybe `alsa_plugins_jll` needs to be updated to match.

I'm  pretty out of touch with how the binary build system works these days, is it just a matter of kicking off a new build for `alsa_plugins_jll`?

**Comment by giordano** [comment]
> I'm pretty out of touch with how the binary build system works these days, is it just a matter of kicking off a new build for alsa_plugins_jll?

Not just that, but the recipe must also specify appropriate compat bounds for the dependencies, otherwise you'll have the same problem later.

**Comment by tp2750** [comment]
I'll like to help fix this. 
Merge request https://github.com/JuliaPackaging/Yggdrasil/pull/8863 makes `alsa_plugin` build again by setting a compat to the last version of FFMPEG that provides `libasound_module_pcm_a52.so`.

I also needed to restrict the architectures. It looks like it only works for the architectures supported by julia 1.0.

This might not be the cleanest solution, but it was what I could figure out.

**Comment by ViralBShah** [comment]
Gave it a look and updated alsa to 1.2.12. I'm completely stumped by the [alsa-plugins build](https://github.com/JuliaPackaging/Yggdrasil/pull/9105) trying to link to libcrypto.so.3.

**Comment by tp2750** [comment]
Thanks a lot @ViralBShah . It works for me now.
