### ISSUE TITLE
Regenerate "old" JLLs?

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/Yggdrasil#876]
The code generated for JLL packages has improve substantially in the past few months. I noticed this when I tried to use Readline_jll: there is no`Readline_jll.artifact_dir` in there, unlike e.g. with GMP_jll. Also the generated README in https://github.com/JuliaBinaryWrappers/Readline_jll.jl is  less useful than the one in e.g. https://github.com/JuliaBinaryWrappers/GMP_jll.jl, as it does not list the actual products exported by the JLL.

In this particular case, I submitted PR #875 in the hopes that this will (once merged) "fix" this particular instance of the issue.

But I wonder if it would make sense to regenerate the .git repos of a bunch of the oldest JLLs, even if they had no other change, just to get their plumbing up to date? 

My naive idea would be to iterate through all https://github.com/JuliaBinaryWrappers repos, and re-run the code generating their content; if there is no diff, then all is fine. Otherwise, increment the version of the JLL and update it.

**Comment by ViralBShah** [comment]
Is it ok to close this one?
