### ISSUE TITLE
Build cminpack

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#8779]
https://github.com/devernay/cminpack.  Ref: https://github.com/sglyon/MINPACK.jl/pull/16#issuecomment-2118540308

**Comment by imciner2** [comment]
Actually, looking at the repo, maybe @sglyon can say what the settings for building MINPACK should be?

**Comment by sglyon** [comment]
It’s has been a while (7 years) , but my compilation notes are here: https://github.com/sglyon/MINPACK.jl/blob/master/notes.md
