### ISSUE TITLE
[MMG_jll] General registry Compat.toml update

### ISSUE THREAD

**Issue by ovanvincq** [JuliaPackaging/Yggdrasil#8918]
The compat section of `MMG_jll` is limited to the version 6 of `SCOTCH_jll.jl`

Is it possible to update to the version 7 of `SCOTCH_jll.jl` ?

My initial problem is that it is not possible to simultaneously install latest versions of `Gmsh.jl` and `MUMPS.jl`:
- `Gmsh.jl` v0.3 requires `gmsh_jll.jl` that requires `MMG_jll.jl` that requires `SCOTCH_jll.jl` v6
- `MUMPS.jl` v1.4 requires `MUMPS_jll.jl` that requires `SCOTCH_jll.jl` v7

Thanks,

**Comment by Komal0103** [comment]
Hello, I have been facing the same problem while running Gmsh, SuperLUDIST and MUMPS in the same project. Did you find any workarounds to this issue?
Thank you in advance!

**Comment by ovanvincq** [comment]
It is possible to install Gmsh and MUMPS by installing the packages in this order (test on windows and wsl):
```
add https://github.com/JuliaBinaryWrappers/MMG_jll.jl
add SCOTCH_jll.jl
add Gmsh
add MUMPS
```

This is possible because the version of SCOTCH_jll is not imposed in the original MMG_jl package (unlike those in the general registry)

Note that MUMPS 1.4.1 does not seems to work on windows and I installed version 1.4.0.

**Comment by ViralBShah** [comment]
SCOTCH is at v7 now.
