### ISSUE TITLE
`zlib_jll` broken reference on Mac OSX

### ISSUE THREAD

**Issue by ThomasChaffey** [JuliaPackaging/Yggdrasil#9252]
I had a broken reference to the `zlib` c library on Mac OS X 14.5.

```
julia> Zlib_jll.libz_path
"/usr/lib/libz.1.dylib"
```
The file/link returned didn't exist, and furthermore `/usr/lib` is protected by SIP, so difficult to fix the link.

Editing the following line in `Zlib_jll.jl/src/wrappers/x86_64-apple-darwin.jl`:

```
JLLWrappers.@declare_library_product(libz, "@rpath/libz.1.dylib")
```
to
```
JLLWrappers.@declare_library_product(libz, "/usr/local/lib/libz.1.dylib")
```
fixed the issue (with `zlib` installed using Homebrew).  Happy to create a pull request, I only haven't as this seems a bit hackish.

**Comment by giordano** [comment]
> I had a broken reference to the `zlib` c library on Mac OS X 14.5.
> 
> ```
> julia> Zlib_jll.libz_path
> "/usr/lib/libz.1.dylib"
> ```

How did you install Julia?  It looks unlikely that with the official binaries you get that.

**Comment by ThomasChaffey** [comment]
I installed Julia with Homebrew, `brew install julia`.

**Comment by giordano** [comment]
That looks like an issue with their distribution, then.  I ***strongly*** recommend using [Juliaup](https://julialang.org/downloads/), which allows you to keep multiple Julia versions side-by-side and automatically upgrade to newer versions, if you want it, or if you really want to stick to Homebrew, at least use the Cask recipe which uses the official binaries.
