### ISSUE TITLE
Allow updating the wrapper of a package without rebuilding the tarballs

### ISSUE THREAD

**Issue by giordano** [JuliaPackaging/Yggdrasil#938]
Sometimes we need to update the wrappers of a JLL package, but not the tarballs.  It would be nice to be able to avoid building the tarballs if not necessary, to save the users downloading a new tarball that is functionally equivalent to the existing one.

We could have a cookie like `[no build]` or anything else in the commit message that would tell our azure pipeline to not build the tarballs but just regenerate the wrappers, without modifying `Artifacts.toml`.  We can access the content of the commit message with [`Build.SourceVersionMessage`](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) (I'm not sure whether this is the merge commit or the tip of the branch that we want to merge) or with an appropriate call to `git`.

**Comment by fingolfin** [comment]
See also #876, I guess?
