### ISSUE TITLE
Outdated configure options for PCRE2

### ISSUE THREAD

**Issue by Micket** [JuliaPackaging/Yggdrasil#940]
https://github.com/JuliaPackaging/Yggdrasil/blob/fa23939d4956d31f4eab12db0d33f693687d4142/P/PCRE2/build_tarballs.jl#L26-L27

Neither `--enable-utf` or `--enable-unicode-properties` exist anymore(?) as far as I can tell. The build logs state the same.
`--enable-unicode`  exists, but, it is already on by default.

**Comment by giordano** [comment]
Good to know, but in practice they shouldn't hurt, do they?

**Comment by Micket** [comment]
They are just ignored AFAIK, but it's mostly just confusing and misleading to anyone reading this (like I had to, for the issues above).
