### ISSUE TITLE
Fails to "download and install the macOS SDK" because I "have not agreed to the Xcode license terms" -- but no way to do so?

### ISSUE THREAD

**Issue by fingolfin** [JuliaPackaging/Yggdrasil#948]
I want to add a new recipe to Yggdrasil; of course I want to test it before submitting. For that I need to build it. I thought I'd start by first trying to build an existing recipe, then work my way up.

For this I set up a pristine user account, with Julia 1.4.1, changed into the Zlib director, and did `julia build_tarballs.jl`. After a lengthy download, it failed with an error as it failed to "download and install the macOS SDK". This failed because I "have not agreed to the Xcode license terms".

But I never even was asked to agree to them. What do I have to do to get past this?

Here is the full output of a second run (so all artifacts are by now downloaded) which shows the problem.

```
HOSTNAME:~/Yggdrasil/Z/Zlib (git:master)$ julia build_tarballs.jl
┌ Warning: Using a pair as source is deprecated, use ArchiveSource instead
└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/o9Hrl/src/Sources.jl:212
[ Info: Building for i686-linux-gnu, x86_64-linux-gnu, aarch64-linux-gnu, armv7l-linux-gnueabihf, powerpc64le-linux-gnu, i686-linux-musl, x86_64-linux-musl, aarch64-linux-musl, armv7l-linux-musleabihf, x86_64-apple-darwin14, x86_64-unknown-freebsd11.1, i686-w64-mingw32, x86_64-w64-mingw32
┌ Warning: Unable to run unprivileged containers on this system! This may be because your kernel does not support mounting overlay filesystems within user namespaces. To work around this, we will switch to using privileged containers. This requires the use of sudo. To choose this automatically, set the BINARYBUILDER_RUNNER environment variable to "privileged" before starting Julia.
└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/o9Hrl/src/UserNSRunner.jl:103
[ Info: Running privileged container via `sudo`, may ask for your password:
[sudo] password for mhorn:
┌ Error: This is not an interactive Julia session, so we will not prompt you
│ to download and install the macOS SDK.  Because you have not agreed
│ to the Xcode license terms, we will not be able to build for MacOS.
└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/o9Hrl/src/Rootfs.jl:193
ERROR: LoadError: macOS SDK not installable
```

**Comment by giordano** [comment]
https://juliapackaging.github.io/BinaryBuilder.jl/dev/FAQ/#What-is-this-I-hear-about-the-macOS-SDK-license-agreement?-1

**Comment by fingolfin** [comment]
Thanks, that helped. I made https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/768 to perhaps make this easier for the next guy :-)
