### ISSUE TITLE
Update MongoC_jll compat?

### ISSUE THREAD

**Issue by PhyX-Meow** [JuliaPackaging/Yggdrasil#9666]
It still depends on openssl 1.0, and this prevents a lot of packages in my project dependences that depend on openssl 3.x to update :(

**Comment by giordano** [comment]
You're welcome to submit a PR to update mongoc to a newer version, which means to adapt
https://github.com/JuliaPackaging/Yggdrasil/blob/5a69b8cf66233993cfdb437f1b3da20c21444d6b/M/MongoC/build_tarballs.jl#L6
https://github.com/JuliaPackaging/Yggdrasil/blob/5a69b8cf66233993cfdb437f1b3da20c21444d6b/M/MongoC/build_tarballs.jl#L12
and change
https://github.com/JuliaPackaging/Yggdrasil/blob/5a69b8cf66233993cfdb437f1b3da20c21444d6b/M/MongoC/build_tarballs.jl#L76
to `compat="3.0.8"`
