### ISSUE TITLE
MPICH_jll not working

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/Yggdrasil#980]
```
julia> using MPICH_jll, Libdl

julia> dlopen(libmpi)
ERROR: could not load library "@rpath/libmpi.12.dylib"
dlopen(@rpath/libmpi.12.dylib, 1): image not found
Stacktrace:
 [1] #dlopen#3(::Bool, ::typeof(dlopen), ::String, ::UInt32) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Libdl/src/Libdl.jl:109
 [2] dlopen at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
 [3] top-level scope at REPL[2]:1
```
cc @giordano

**Comment by giordano** [comment]
You maybe want to do
```julia
dlopen(MPICH_jll.libmpi_path)
```
?

**Comment by giordano** [comment]
Note that `dlopen(MPICH_JLL.libmpi_path)` is exactly what the [wrapper does](https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/blob/b2ef87d95938e36814d03e1270b2eec29323133e/src/wrappers/x86_64-apple-darwin14-libgfortran4.jl#L115).

For the record, now we have documentation about the JLL packages and the variables they define: https://juliapackaging.github.io/BinaryBuilder.jl/dev/jll/#LibraryProduct-1.  This should hopefully make clear the difference between `libmpi` and `libmpi_path`

**Comment by simonbyrne** [comment]
I can't use `libmpi` in a `ccall` either:
```
julia> buf = Array{UInt8}(undef, 8192); buflen = Ref{Cint}();

julia> ccall((:MPI_Get_library_version, libmpi), Cint, (Ptr{UInt8}, Ref{Cint}), buf, buflen)
ERROR: error compiling top-level scope: could not load library "@rpath/libmpi.12.dylib"
dlopen(@rpath/libmpi.12.dylib, 1): image not found
caused by [exception 1]
could not load library "@rpath/libmpi.12.dylib"
dlopen(@rpath/libmpi.12.dylib, 1): image not found
```

**Comment by giordano** [comment]
Ok, that's more strange.  Has mpi been loaded already?  Check with
```julia
filter!(p -> occursin("mpi", p), Libdl.dllist())
```

**Comment by simonbyrne** [comment]
Yes, it looks like `using MPICH_jll` loads the homebrew ones:
```
julia> using Libdl

julia> filter!(p -> occursin("mpi", p), Libdl.dllist())
1-element Array{String,1}:
 "/usr/lib/system/libcompiler_rt.dylib"

julia> using MPICH_jll

julia> filter!(p -> occursin("mpi", p), Libdl.dllist())
5-element Array{String,1}:
 "/usr/lib/system/libcompiler_rt.dylib"
 "/usr/local/Cellar/mpich/3.3.2/lib/libmpifort.12.dylib"
 "/usr/local/Cellar/mpich/3.3.2/lib/libmpi.12.dylib"
 "/usr/local/Cellar/mpich/3.3.2/lib/libpmpi.12.dylib"
 "/usr/local/Cellar/mpich/3.3.2/lib/libmpicxx.12.dylib"
```

**Comment by giordano** [comment]
That's fascinating :confused:   What's the value of `MPICH_jll.artifact_dir` and `MPICH_jll.libmpi_path` for you?

**Comment by giordano** [comment]
What the...

**Comment by simonbyrne** [comment]
I'm an idiot: I had forgotten I had set the Overrides.toml

**Comment by simonbyrne** [comment]
But I wonder why it didn't work correctly?

**Comment by giordano** [comment]
I _think_ because homebrew doesn't set the id of `lib/libpmpi.12.dylib` to `@rpath/libpmpi.12.dylib`.  See for example the file `$(MPICH_jll.artifact_dir)/logs/fix_identity_mismatch_libpmpi.12.dylib.log`.  But we need @staticfloat for an explanation, he knows better how loading works.

**Comment by staticfloat** [comment]
Yes, sadly, in order for this kind of linking to work on MacOS, the DYLIB_ID must be the same.  We set everything to `@rpath/<dylib_filename>` on MacOS to make this easy no matter the location, but if Homebrew doesn't do that (and they may have good reasons not to) then it won't work; we need to change one of the two sides; either the dependency or the dependee.
