### ISSUE TITLE
XML2 build without thread support

### ISSUE THREAD

**Issue by Para7etamol** [JuliaPackaging/Yggdrasil#9847]
Hi there,

as far I can see, libxml2-wrapper is build without using --with-threads so i lacks thread support.

I think threads should be supported. At least for me that would fit very well :-)

Greetings
Oliver

**Comment by eschnett** [comment]
According to the configure script, `--with-threads` is the default?

**Comment by Para7etamol** [comment]
Ok, so I misunderstood 

`--with-threads          multithreading support (on)`

.... 

I was confused because I missed that thread support  can be disabled by  "--without-threads". Therefor I tought that it is only enabled when the option is given. But it isnt't ... omg ... time to go to sleep :-) 

Thanks.
