### ISSUE TITLE
Qhull_jll versions

### ISSUE THREAD

**Issue by thchr** [JuliaPackaging/Yggdrasil#9889]
The latest registered version of Qhull_jll is 8.0.1003+0, but in the past, another versioning scheme was used, which included the registered versions
- [2020.2.0+0](https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/commit/66d55c2967e58b5a0d9e5ab510f436d7234364f7)
- [2019.1.0+2](https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/commit/c3244cd6e0158a397a8695ba0eefc6742da6bbd6)
- [2019.1.0+1](https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/commit/21aa305cfefb866020b1371c3602c59096b61dd7)
- [2019.1.0+0](https://github.com/JuliaBinaryWrappers/Qhull_jll.jl/commit/a9ea3261489652a256af85a2aeb7819bb7bd3d6f)

Even though these versions predate 8.0.1003+0, they are are nominally more recent in semver, since 2020>8. As a result, Pkg thinks that any dependency using Qhull_jll is being held back. Is there any way to strip the 2020 and 2019 versions from the list of available versions?

**Comment by eschnett** [comment]
The way to handle this is to add an arbitrary constant to the version number. We should re-release 8.0.1003 as 10008.0.1003.

**Comment by thchr** [comment]
I suppose that works also (although it has the downside that it will require updates to all dependents of Qhull_jll; there's probably not that many though).

Maybe @stevengj has an opinion, cf. earlier adjustments of the versioning scheme in https://github.com/JuliaPackaging/Yggdrasil/pull/3662?

**Comment by eschnett** [comment]
Well, dependencies would not need to update anything to remain at the current status quo.

**Comment by thchr** [comment]
Sure, my aim with this issue was just to initiate the least number of changes in the ecosystem necessary to fix the annoying current situation - but maybe that number just ≥2 and not 1, as I had hoped it could be.

**Comment by ViralBShah** [comment]
I just ran into this a few days ago as well, and we should definitely fix it.
